(function(g){var window=this;'use strict';var Eo=function(x){x.publish("cardstatechange",x.s5()&&x.Lc()?1:0)},zN=function(x,n){var Z=g.QO(n),F=Z?n:arguments;
for(Z=Z?0:1;Z<F.length;Z++){if(x==null)return;x=x[F[Z]]}return x},r92=function(x){var n=g.c3(x);
x=g.xd(x);return new g.wq(n.x,n.y,x.width,x.height)},Ro2=function(x,n,Z){var F;
return F=g.yy(x,n,function(){g.BA(F);Z.apply(x,arguments)},{})},m1=function(x){x=g.zc(x);
delete W_[x];g.c6(W_)&&oI&&oI.stop()},t$u=function(){oI||(oI=new g.eP(function(){DFz()},20));
var x=oI;x.isActive()||x.start()},DFz=function(){var x=g.Gc();
g.W6(W_,function(n){A92(n,x)});
g.c6(W_)||t$u()},GN=function(x,n,Z,F){g.Gm.call(this);
if(!Array.isArray(x)||!Array.isArray(n))throw Error("Start and end parameters must be arrays");if(x.length!=n.length)throw Error("Start and end points must be the same length");this.L=x;this.N=n;this.duration=Z;this.V=F;this.coords=[];this.progress=this.O=0;this.U=null},A92=function(x,n){n<x.startTime&&(x.endTime=n+x.endTime-x.startTime,x.startTime=n);
x.progress=(n-x.startTime)/(x.endTime-x.startTime);x.progress>1&&(x.progress=1);x.O=1E3/(n-x.U);x.U=n;xkk(x,x.progress);x.progress==1?(x.Z=0,m1(x),x.onFinish(),x.QK()):x.isPlaying()&&x.fi()},xkk=function(x,n){typeof x.V==="function"&&(n=x.V(n));
x.coords=Array(x.L.length);for(let Z=0;Z<x.L.length;Z++)x.coords[Z]=(x.N[Z]-x.L[Z])*n+x.L[Z]},n8s=function(x,n){g.Xm.call(this,x);
this.coords=n.coords;this.x=n.coords[0];this.y=n.coords[1];this.z=n.coords[2];this.duration=n.duration;this.progress=n.progress;this.fps=n.O;this.state=n.Z},l3=function(x,n,Z,F,k){GN.call(this,n,Z,F,k);
this.element=x},Cm=function(x,n,Z,F,k){if(n.length!=2||Z.length!=2)throw Error("Start and end points must be 2D");
l3.call(this,x,n,Z,F,k)},Z4z=function(x){return Math.pow(x,3)},Fvz=function(x){return 3*x*x-2*x*x*x},fm=function(x){return x.baseUrl||null},wZ=function(x,n){return g.HN(g.NK(x,n),Z=>!!Z)},i4o=function(x,n,Z){function F(jT){var pn=jT.hovercardButton;
if(!pn)return null;pn=pn.subscribeButtonRenderer;if(!pn)return null;var tg=J(pn.unsubscribedButtonText),fY=J(pn.subscribedButtonText);if(pn.subscribed){var lI=J(pn.subscriberCountWithUnsubscribeText);var VR=J(pn.subscriberCountText)}else lI=J(pn.subscriberCountText),VR=J(pn.subscriberCountWithSubscribeText);var bO=null;return jT.signinEndpoint&&((bO=zN(jT,"signinEndpoint","webNavigationEndpointData","url"))||(bO=g.O(pn.signInEndpoint?.commandMetadata,g.W7)?.url),!bO)?null:tg&&(fY||bO)?{subscribed:pn.subscribed,
subscribeText:tg,subscribeCount:lI,unsubscribeText:fY,unsubscribeCount:VR,enabled:pn.enabled,signinUrl:bO,classic:jT.useClassicSubscribeButton}:null}
function k(jT){if(jT){var pn=[],tg=jT.videoId;tg&&pn.push("v="+tg);(tg=jT.playlistId)&&pn.push("list="+tg);(jT=jT.startTimeSeconds)&&pn.push("t="+jT);return"/watch?"+pn.join("&")}}
function J(jT){if(!jT)return null;var pn=jT.simpleText;return pn?pn:jT.runs?g.NK(jT.runs,tg=>tg.text).join(""):null}
n=n.endscreenElementRenderer;if(!n)return null;var Y=n.style,v=n.endpoint||{},L=null,S=null,T=!1,U=null,h=null,u=null,d=null,m=!1,P=null,H=null,N=null,b=null,M=null,nn=null;if(Y==="VIDEO")g.O(v,g.xz)?L=g.O(v,g.xz).url:(nn=g.O(v,g.WL),L=k(nn)),S=!1,U=x,n.thumbnailOverlays?(T=n.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,h=J(T.text),T=T.style==="LIVE"):h=J(n.videoDuration);else if(Y==="PLAYLIST")g.O(v,g.xz)?L=g.O(v,g.xz).url:(nn=g.O(v,g.WL),L=k(nn)),S=!1,U=x,u=J(n.playlistLength);else if(Y===
"CHANNEL"){if(m=zN(v,"browseEndpoint","browseId"))d=m,L=`/channel/${d}`;S=!1;U="new";(m=!!n.isSubscribe)?P=F(n):H=J(n.subscribersText)}else Y==="WEBSITE"?((N=zN(v,"urlEndpoint","url"))&&(L=N),S=!0,U="new",N=n.icon.thumbnails[0].url):Y==="CREATOR_MERCHANDISE"&&(n.productPrice&&(b=J(n.productPrice)),n.additionalFeesText&&(M=J(n.additionalFeesText)),(S=zN(v,"urlEndpoint","url"))&&(L=S),S=!0,U="new");x=zN(n,"title","accessibility","accessibilityData","label");var yO=n.endpoint?n.endpoint.clickTrackingParams:
null,mq="";if(n.metadata){let jT=J(n.metadata);jT&&(mq=jT)}return{id:`element-${Z}`,type:Y,title:J(n.title),metadata:mq,callToAction:J(n.callToAction),I0:n.image,iconUrl:N,left:Number(n.left),width:Number(n.width),top:Number(n.top),aspectRatio:Number(n.aspectRatio),startMs:Math.floor(Number(n.startMs)),endMs:Math.floor(Number(n.endMs)),videoDuration:h,yw:T,playlistLength:u,channelId:d,subscribeButton:P,subscribersText:H,isSubscribe:m,targetUrl:L||null,Hf:S,sessionData:yO?{itct:yO}:null,td:U,Ov:x?
x:null,isPlaceholder:n.isPlaceholder,impressionUrls:wZ(n.impressionUrls||[],fm),tk:wZ(n.hovercardShowUrls||[],fm),clickUrls:wZ(v.loggingUrls||[],fm),visualElement:g.qy(n.trackingParams),productPrice:b,additionalFeesText:M,watchEndpoint:nn||null}},P_=function(x,n){var Z={startMs:Math.floor(Number(x.startMs)),
impressionUrls:wZ(x.impressionUrls||[],fm),elements:wZ(x.elements||[],(F,k)=>i4o(n,F,k))};
x.trackingParams&&(Z.visualElement=g.qy(x.trackingParams));return Z},jW=function(x){return x.player.J().playerStyle==="creator-endscreen-editor"},k6k=function(x){return x.player.getVideoData().B7?"current":x.Y?"new":"current"},qv=function(x,n,Z=!0){x.player.fH("creatorendscreen");
x.B&&(x.B.dispose(),x.B=null,x.V.dispose(),x.V=null);for(var F of Object.values(x.L))F.dispose();x.L={};x.O={};x.G.length>0&&(x.G.forEach(k=>{k.dispose()}),x.G.length=0);
x.Z&&(g.WC(x.Z,"ytp-ce-element-show"),x.Z.setAttribute("aria-hidden","true"));x.N=0;if((x.endscreen=n)&&n.elements){Z&&JSt(x);Z=[];F=new g.Zu(n.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});Z.push(F);x.player.J().B||(x.B=new g.t({D:"div",W:"ytp-ce-shadow"}),g.KD(x.player,x.B.element,4),x.V=new g.Ks(x.B,200));for(F=0;F<n.elements.length;++F){let k=n.elements[F],J=Yfi(x,k);if(!J){g.AQ(new g.gm("buildEndscreenElement null",k));continue}x.L[k.id]=J;x.O[k.id]=k;g.KD(x.player,
J.element,4);let Y=new g.Zu(k.startMs,k.endMs,{id:"ytp-ce-element-"+k.id,namespace:"creatorendscreen"});Z.push(Y);v86(x,J,k)}x.player.Zr(Z);x.jG()}},Lv$=function(x){var n=x.player.getVideoData(),Z=n.videoId;
x.U&&x.U.abort();Z={method:"POST",onFinish:k=>{var J=x.U=null;k.status===200&&(k=k.responseText,k.substring(0,3)===")]}"&&(k=k.substring(3),J=JSON.parse(k),J=P_(J,k6k(x))));qv(x,J)},
urlParams:{v:Z},withCredentials:!0};x.Y&&(Z.urlParams.ptype="embedded");var F=n.IN;F&&(Z.postParams={ad_tracking:F});if(n=g.z8R(n))if(n=g.HR(n),n=g.Iv(n))x.U=g.sT(n,Z)},JSt=function(x){var n=g.$b(),Z=g.Om();
Z&&n&&x.endscreen.visualElement&&g.cS(g.u4)(void 0,Z,n,x.endscreen.visualElement)},Yfi=function(x,n){var Z=null;
switch(n.type){case "VIDEO":x={D:"div",sR:["ytp-ce-element","ytp-ce-video"],A:{tabindex:"0","aria-label":n.Ov||"","aria-hidden":"true"},j:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-covering-image",A:II(n)},{D:"div",W:"ytp-ce-covering-shadow-top"},{D:"a",W:"ytp-ce-covering-overlay",A:{href:gZ(x,n.targetUrl),tabindex:"-1"},j:[{D:"div",sR:["ytp-ce-video-title","ytp-webkit-ellipsis"],A:{dir:g.Vq(n.title||"")},UR:n.title},{D:"div",W:n.yw?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
UR:n.videoDuration||void 0}]}]};Z=new g.t(x);break;case "PLAYLIST":x={D:"div",sR:["ytp-ce-element","ytp-ce-playlist"],A:{tabindex:"0","aria-label":n.Ov||"","aria-hidden":"true"},j:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-covering-image",A:II(n)},{D:"div",W:"ytp-ce-covering-shadow-top"},{D:"a",W:"ytp-ce-covering-overlay",A:{href:gZ(x,n.targetUrl),tabindex:"-1"},j:[{D:"div",sR:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],A:{dir:g.Vq(n.title||"")},UR:n.title},{D:"div",W:"ytp-ce-playlist-count",
j:[{D:"div",W:"ytp-ce-playlist-icon"},{D:"div",W:"ytp-ce-playlist-count-text",UR:n.playlistLength||void 0}]}]}]};Z=new g.t(x);break;case "CHANNEL":Z={D:"div",sR:["ytp-ce-element","ytp-ce-channel",n.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],A:{tabindex:"0","aria-label":n.Ov||"","aria-hidden":"true"},j:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-expanding-overlay",j:[{D:"div",W:"ytp-ce-expanding-overlay-hider"},{D:"div",W:"ytp-ce-expanding-overlay-background"},{D:"div",W:"ytp-ce-expanding-overlay-content",
j:[{D:"div",W:"ytp-ce-expanding-overlay-body",j:[{D:"div",W:"ytp-ce-expanding-overlay-body-padding",j:[{D:"a",sR:["ytp-ce-channel-title","ytp-ce-link"],A:{href:gZ(x,n.targetUrl),target:"_blank",tabindex:"-1",dir:g.Vq(n.title||"")},UR:n.title},n.subscribeButton?{D:"div",W:"ytp-ce-subscribe-container",j:[{D:"div",W:"ytp-ce-channel-subscribe"}]}:"",n.subscribersText?{D:"div",W:"ytp-ce-channel-subscribers-text",A:n.Ov?{"aria-hidden":"true"}:{},UR:n.subscribersText}:"",n.metadata?{D:"div",sR:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],UR:n.metadata}:""]}]}]}]},{D:"div",W:"ytp-ce-expanding-image",A:II(n)}]};Z=new g.t(Z);let k=g.r5(document,"div","ytp-ce-channel-subscribe",Z.element)[0];if(n.subscribeButton&&n.channelId){g.Eu(k,"ytp-ce-subscribe-button");let J;if(x.player.J().B){var F=null;J=n.sessionData.itct}else F="endscreen",J=null;F=new g.pA(n.subscribeButton.subscribeText,n.subscribeButton.subscribeCount,n.subscribeButton.unsubscribeText,n.subscribeButton.unsubscribeCount,!!n.subscribeButton.enabled,
!!n.subscribeButton.classic,n.channelId,!!n.subscribeButton.subscribed,F,J,x.player,!1);k.appendChild(F.element);x.G.push(F)}break;case "WEBSITE":x={D:"div",sR:["ytp-ce-element","ytp-ce-website"],A:{tabindex:"0","aria-label":n.Ov||"","aria-hidden":"true"},j:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-expanding-overlay",j:[{D:"div",W:"ytp-ce-expanding-overlay-hider"},{D:"div",W:"ytp-ce-expanding-overlay-background"},{D:"div",W:"ytp-ce-expanding-overlay-content",j:[{D:"div",W:"ytp-ce-expanding-overlay-body",
j:[{D:"div",W:"ytp-ce-expanding-overlay-body-padding",j:[{D:"div",W:"ytp-ce-website-title",A:{dir:g.Vq(n.title||"")},UR:n.title},{D:"div",W:"ytp-ce-website-metadata",UR:n.metadata},{D:"a",sR:["ytp-ce-website-goto","ytp-ce-link"],A:{href:gZ(x,n.targetUrl),target:"_blank",tabindex:"-1"},UR:n.callToAction}]}]}]}]},{D:"div",W:"ytp-ce-expanding-image",A:II(n)},{D:"div",W:"ytp-ce-expanding-icon",A:SfJ(n.iconUrl)}]};Z=new g.t(x);break;case "CREATOR_MERCHANDISE":Z="",n.productPrice&&(Z={D:"div",W:"ytp-ce-merchandise-price-container",
j:[{D:"div",W:"ytp-ce-merchandise-price",UR:n.productPrice}]},n.additionalFeesText&&Z.j.push({D:"div",W:"ytp-ce-merchandise-additional-fees",UR:n.additionalFeesText})),x={D:"div",sR:["ytp-ce-element","ytp-ce-merchandise"],A:{tabindex:"0","aria-label":n.Ov||"","aria-hidden":"true"},j:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-expanding-overlay",j:[{D:"div",W:"ytp-ce-expanding-overlay-hider"},{D:"div",W:"ytp-ce-expanding-overlay-background"},{D:"div",W:"ytp-ce-expanding-overlay-content",
j:[{D:"div",W:"ytp-ce-expanding-overlay-body",j:[{D:"div",W:"ytp-ce-expanding-overlay-body-padding",j:[{D:"div",W:"ytp-ce-merchandise-title",A:{dir:g.Vq(n.title||"")},UR:n.title},Z,{D:"div",W:"ytp-ce-merchandise-metadata",UR:n.metadata},{D:"a",sR:["ytp-ce-merchandise-goto","ytp-ce-link"],A:{href:gZ(x,n.targetUrl),target:"_blank",tabindex:"-1"},UR:n.callToAction}]}]}]}]},{D:"div",W:"ytp-ce-expanding-image",A:II(n)},{D:"div",W:"ytp-ce-merchandise-invideo-cta-container",j:[{D:"div",W:"ytp-ce-merchandise-invideo-cta",
UR:n.callToAction||void 0}]}]},Z=new g.t(x)}n.isPlaceholder&&g.Eu(Z.element,"ytp-ce-placeholder");return Z},v86=function(x,n,Z){function F(){Y(1)}
function k(){Y(-1)}
n.listen("mouseenter",()=>{$J(x,n,Z)});
n.listen("mouseleave",()=>{Oo(x,n,Z)});
x.player.J().B||n.listen("click",()=>{g.Eu(n.element,"ytp-ce-element-hover")});
n.listen("click",v=>{Tgi(x,Z,v)});
n.listen("keypress",v=>{Tgi(x,Z,v)});
n.listen("focus",()=>{$J(x,n,Z)});
n.listen("blur",()=>{Oo(x,n,Z)});
n.listen("touchstart",()=>{$J(x,n,Z)});
var J=g.R3("ytp-ce-expanding-overlay-hider",n.element);J&&n.X(J,"touchstart",v=>{v.stopPropagation();g.WC(n.element,"ytp-ce-element-hover");g.WC(n.element,"ytp-ce-force-expand")});
n.listen("keydown",v=>{x.Ze=v.keyCode===9&&!v.shiftKey});
var Y=v=>{x.N+=v;x.N>0?(g.Eu(n.element,"ytp-ce-force-expand"),H_(x,Z.id,!0)):(g.WC(n.element,"ytp-ce-force-expand"),g.WC(n.element,"ytp-ce-element-hover"),H_(x,Z.id,!1))};
J=v=>{v&&(n.listen("blur",()=>{v.style.display!="none"&&x.Ze&&v.focus()}),n.X(v,"focus",F),n.X(v,"blur",k))};
J(g.R3("ytp-sb-subscribe",n.element));J(g.R3("ytp-sb-unsubscribe",n.element));n.listen("focus",F);n.listen("blur",k)},Nv=function(x,n,Z){function F(){J||(k++,k===n.length&&(Y.stop(),Z&&Z()))}
if(!n||n.length===0||jW(x))Z&&Z();else{n=Ukt(x,n);var k=0,J=!1,Y=new g.eP(()=>{J=!0;Z&&Z()},1E3,x);
Y.start();for(x=0;x<n.length;x++)g.Jj(n[x],F)}},II=function(x){if(x.I0)var n=x.I0.thumbnails;
return SfJ(n?n[n.length-1].url:null)},gZ=function(x,n){x=x.player.J();
if(n){if(n.startsWith("//"))return x.protocol+":"+n;if(n.startsWith("/"))return g.PU(x)+n}else return"";return n},SfJ=function(x){return x?{style:"background-image: url("+x+")"}:{}},$J=function(x,n,Z){g.X6(n.element,"ytp-ce-element-hover")||(Z.type==="VIDEO"||Z.type==="PLAYLIST"?g.Eu(n.element,"ytp-ce-element-hover"):x.player.J().B?(new g.eP(()=>{g.Eu(n.element,"ytp-ce-element-hover")},200)).start():g.Eu(n.element,"ytp-ce-element-hover"),Nv(x,Z.tk),H_(x,Z.id,!0))},Oo=function(x,n,Z){g.WC(n.element,
"ytp-ce-element-hover");
g.WC(n.element,"ytp-ce-force-expand");H_(x,Z.id,!1)},Tgi=function(x,n,Z){if(n.targetUrl&&(!Z||Z.type!=="keypress"||Z.keyCode===13)){for(var F=Z.target;F&&!g.X6(F,"ytp-ce-element");){g.X6(F,"subscribe-label")&&b3(x,n);
if(g.X6(F,"ytp-ce-channel-subscribe"))return;F=F.parentElement||null}if(!F||g.X6(F,"ytp-ce-element-hover")){Z.preventDefault();Z.stopPropagation();if(F=x.L[n.id])Oo(x,F,n),F.element.blur();if(Z.ctrlKey||Z.metaKey||n.td==="new")b3(x,n),x.player.sendVideoStatsEngageEvent(17,void 0),x.player.pauseVideo(),Z=g.HR(gZ(x,n.targetUrl)),Z=g.Iv(Z),g.zb(Z,void 0,n.sessionData);else{let k=g.WU(x.player.J())||x.player.getVideoData().B7,J=()=>{var Y=gZ(x,n.targetUrl),v=n.sessionData,L=n.watchEndpoint,S=g.AC(Y);
k&&S&&(S.v||S.list)?x.player.Iu(S.v,v,S.list,!1,void 0,L||void 0):g.Ei(Y,v)};
b3(x,n,()=>{x.player.sendVideoStatsEngageEvent(17,J)})}}}},H_=function(x,n,Z){x.B&&(Z?x.V.show():x.V.hide());
for(let F of Object.keys(x.L))F!==n&&g.mu(x.L[F].element,"ytp-ce-element-shadow-show",Z)},b3=function(x,n,Z){Nv(x,n.clickUrls,Z);
(x=g.Om())&&n.Hf&&g.zf(x,n.visualElement)},Ukt=function(x,n){var Z=x.player.getVideoData().clientPlaybackNonce;
x=x.player.getCurrentTime().toFixed(2);Z={CPN:Z,AD_CPN:Z,MT:x};x=[];for(let F=0;F<n.length;F++)x.push(uVt(n[F],Z));return x},uVt=function(x,n){return x.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,Z=>{var F=unescape(Z);
F=F.substring(1,F.length-1);return n[F]?escape(n[F]):Z})},hDe=function(x){return typeof x==="string"?x:""},pm=function(x,n,Z){for(let F in n)if(n[F]===x)return x;
return Z},Km=function(x){if(!x)return null;
var n=g.HR(hDe(x.value));n=g.Iv(n);if(!n)return null;var Z=pm(x.target,eDu,"current");if(Z==null)x=null;else{var F=x.show_link_icon;x=new ySl(n,Z,F==="true"||F==="false"?F==="true":!0,x.pause_on_navigation!=null?x.pause_on_navigation:!0)}return x},dkk=function(x){if(!x)return null;
var n=pm(x.type,sAe),Z=pm(x.trigger,Bgt);x=x.url;x=Array.isArray(x)&&x.length?x[0]:x;x=Km(x?x:null);return n?new as6(n,Z,x):null},QAo=function(x,n){return g.Ru(x.action,n)},Mv=function(x,n){x="background-image: url("+x+");";
var Z=[];n&&Z.push(n);return{D:"div",W:"iv-card-image",A:{style:x},j:Z}},rZ=function(x){return x.customMessage?c_("div","iv-card-message",x.customMessage):""},RI=function(x){if(!x.metaInfo||x.metaInfo.length===0)return"";
var n=[];for(let Z of x.metaInfo)n.push(c_("li","",Z));return{D:"ul",W:"iv-card-meta-info",j:n}},Db=function(x,n,Z,F){if(F)for(let k of n)x.Z(k,F,Z.id,Z.sessionData,Z.lw.click,5)},c_=function(x,n,Z){n?typeof n==="string"?n={"class":n}:Array.isArray(n)&&(n={"class":n.join(" ")}):n={};
n.dir=g.Vq(Z);return{D:x,A:n,UR:Z}},Xjz=function(x){if(!x.customMessage)return"";
var n=["iv-card-action","iv-card-primary-link"],Z={};x.OE&&(n.push("iv-card-action-icon"),Z.style="background-image: url("+x.OE+");");Z.dir=g.Vq(x.customMessage);var F=[{D:"span",UR:x.customMessage}];x.showLinkIcon&&(F.push("\u00a0"),F.push({D:"span",W:"iv-card-link-icon"}));return{D:"div",sR:n,A:Z,j:F}},E8u=function(x){var n;
(n=x)&&!(n=x.length>1?x.charAt(0)==="/"&&x.charAt(1)!=="/":x==="/")&&(n=x.replace(/^(https?:)?\/\//,"").split("/",1),n=!n||n.length<1||!n[0]?[]:n[0].toLowerCase().split(".").reverse(),n=n[0]==="com"&&n[1]==="youtube"||n[0]==="be"&&n[1]==="youtu");return n?x.indexOf("/redirect?")===-1:!1},zD6=function(x,n){return n?n:E8u(x)?"current":"new"},tm=function(x,n,Z,F,k,J,Y){x.context.Z.listen(n,"click",v=>{x.r$(Z,F,k,J||[],Y||0,v)});
x.context.Z.listen(n,"touchstart",()=>{x.AZ=!1});
x.context.Z.listen(n,"touchmove",()=>{x.AZ=!0})},Wvt=function(x){if(g.O(x,g.xz)?.url)return g.O(x,g.xz).url;
if((x=g.O(x,g.WL))&&x.videoId){let n="/watch?v="+x.videoId;x.playlistId&&(n+="&list="+x.playlistId);x.index&&(n+="&index="+x.index);x.startTimeSeconds&&(n+="&t="+x.startTimeSeconds);return n}return null},Am=function(x,n,Z){return{cG:(x.impressionLoggingUrlsV2s||[]).map(F=>F.baseUrl||""),
click:(Z.loggingUrls||[]).map(F=>F.baseUrl||""),
close:(n.dismissLoggingUrlsV2s||[]).map(F=>F.baseUrl||""),
L_:(n.impressionLoggingUrlsV2s||[]).map(F=>F.baseUrl||""),
xI:(n.clickLoggingUrlsV2s||[]).map(F=>F.baseUrl||"")}},Fo=function(x,n){if(n.onClickCommand&&g.O(n.onClickCommand,g.t7q)?.targetId==="engagement-panel-error-corrections"){x.K=n;
var Z=!0}else Z=!1;if(!Z||o8z(x,n))if(Z=mkl(x,n)){var F={nV:n,l9:Z.element,XN:!1};if(n.onClickCommand)x.S.C("web_infocards_teaser_show_logging_fix")&&(x.LT||lsk(x),xB(x,n.id),Z=x.findLastIndex(F),g.Tu(x.cards,Z,0,F));else{x.isInitialized||G6s(x);xB(x,n.id);let k=x.findLastIndex(F);g.Tu(x.cards,k,0,F);Z.kP(x.L,k);x.w$()}n.autoOpen?x.addCueRange(n.startMs,0x8000000000000,n.id,()=>{x.B||(x.Z=F,n2(x),CtJ(x,F),Zq(x,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(Z=x.context.S.getCurrentTime()*1E3,Z<5E3&&Z>n.startMs&&
fsk(x,F),x.addCueRange(n.startMs,n.startMs+1,n.id,()=>{fsk(x,F)}),n2(x))}},ic=function(x){x.B&&(x.X9.hide(),x.ie.L(),g.WC(x.context.S.getRootNode(),g.EG.IV_DRAWER_OPEN),x.B=!1,Eo(x.S),x.V&&x.V.stop(),x.V=new g.eP(()=>{x.ue&&(x.ue.focus(),x.ue=null)},330),x.V.start())},wj$=function(x,n){n=n.data;
n.autoOpenMs&&x.addCueRange(n.autoOpenMs,0x8000000000000,"",()=>{Zq(x,"YOUTUBE_DRAWER_AUTO_OPEN")});
n.autoCloseMs&&x.addCueRange(n.autoCloseMs,0x8000000000000,"",()=>{ic(x)});
var Z=n.headerText;g.hM(x.Zc,Z);x.G&&x.G.setAttribute("data-tooltip-title",Z);n.eventId&&(x.eventId=n.eventId);x.oW=g.qy(n.trackingParams);x.N=g.qy(n.closeTrackingParams);x.Aq=g.qy(n.iconTrackingParams)},kB=function(x,n,Z){var F=-1,k=-1;
for(let J=0;J<x.length;J++){if(x[J].height===n||x[J].width===Z)return x[J];((x[J].height||0)<n||(x[J].width||0)<Z)&&(F<0||(x[F].height||0)<(x[J].height||0)||(x[F].width||0)<(x[J].width||0))?F=J:((x[J].height||0)>=n||(x[J].width||0)>=Z)&&(k<0||(x[k].height||0)>(x[J].height||0)||(x[k].width||0)>(x[J].width||0))&&(k=J)}return x[k>=0?k:F]},Jl=function(x,n,Z,F){return{feature:Z.feature?Z.feature:"cards",
src_vid:x.context.videoData.videoId,annotation_id:n,ei:x.context.videoData.eventId||"",itct:F.trackingParams||""}},VBJ=function(x,n){var Z=n.cardId?n.cardId:`cr:${x.O}`,F=x.S.J().experiments.yF("enable_error_corrections_infocard_web_client");
if(!n.content&&n.teaser.simpleCardTeaserRenderer&&F){F=n.teaser.simpleCardTeaserRenderer;var k=n.icon?n.icon.infoCardIconRenderer:null;if(F.channelAvatar&&F.channelAvatar.thumbnails&&F.channelAvatar.thumbnails.length>0)var J=kB(F.channelAvatar.thumbnails,22,22).url;n={id:Z,timestamp:x.O,type:"simple",teaserText:g.w3(F.message),teaserDurationMs:Number(n.cueRanges[0].teaserDurationMs),startMs:Number(n.cueRanges[0].startCardActiveMs),autoOpen:!!n.autoOpen,sessionData:{},sponsored:!1,lw:{},cq:null,p9:F.trackingParams?
g.qy(F.trackingParams):null,Aq:k&&k.trackingParams?g.qy(k.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,OE:null,title:"",customMessage:"",url:null,onClickCommand:F.onTapCommand||null,zH:J};Fo(x,n)}else if(n.content?.simpleCardContentRenderer){if(!n.cueRanges.length)return;J=n.content?.simpleCardContentRenderer;F=n.teaser.simpleCardTeaserRenderer;k=n.icon?n.icon.infoCardIconRenderer:null;n={id:Z,timestamp:x.O,type:"simple",teaserText:g.w3(F.message),teaserDurationMs:Number(n.cueRanges[0].teaserDurationMs),
startMs:Number(n.cueRanges[0].startCardActiveMs),autoOpen:!!n.autoOpen,sessionData:Jl(x,Z,n,J),sponsored:!1,lw:Am(J,F,J.command),cq:J.trackingParams?g.qy(J.trackingParams):null,p9:F.trackingParams?g.qy(F.trackingParams):null,Aq:k&&k.trackingParams?g.qy(k.trackingParams):null,imageUrl:kB(J.image.thumbnails,290,290).url,displayDomain:J.displayDomain?g.w3(J.displayDomain):null,showLinkIcon:!!J.showLinkIcon,OE:null,title:J.title?g.w3(J.title):"",customMessage:J.callToAction?g.w3(J.callToAction):"",url:g.O(J.command,
g.xz).url?Km({pause_on_navigation:!x.context.videoData.isLivePlayback,target:"new",value:g.O(J.command,g.xz).url}):null,onClickCommand:null};Fo(x,n)}else if(n.content?.collaboratorInfoCardContentRenderer){if(!n.cueRanges.length)return;J=n.content?.collaboratorInfoCardContentRenderer;F=n.teaser.simpleCardTeaserRenderer;k=n.icon?n.icon.infoCardIconRenderer:null;n={id:Z,timestamp:x.O,type:"collaborator",teaserText:g.w3(F.message),teaserDurationMs:Number(n.cueRanges[0].teaserDurationMs),startMs:Number(n.cueRanges[0].startCardActiveMs),
autoOpen:!!n.autoOpen,sessionData:Jl(x,Z,n,J),sponsored:!1,lw:Am(J,F,J.endpoint),cq:J.trackingParams?g.qy(J.trackingParams):null,p9:F.trackingParams?g.qy(F.trackingParams):null,Aq:k&&k.trackingParams?g.qy(k.trackingParams):null,channelId:g.O(J.endpoint,g.XB).browseId,customMessage:J.customText?g.w3(J.customText):null,profileImageUrl:kB(J.channelAvatar.thumbnails,290,290).url,title:J.channelName?g.w3(J.channelName):"",metaInfo:[J.subscriberCountText?g.w3(J.subscriberCountText):""],url:Km({pause_on_navigation:!x.context.videoData.isLivePlayback,
target:"new",value:g.O(J.endpoint,g.XB).canonicalBaseUrl?g.O(J.endpoint,g.XB).canonicalBaseUrl:`/channel/${g.O(J.endpoint,g.XB).browseId}`}),onClickCommand:null};Fo(x,n)}else if(n.content?.playlistInfoCardContentRenderer){if(!n.cueRanges.length)return;J=n.content?.playlistInfoCardContentRenderer;F=n.teaser.simpleCardTeaserRenderer;k=n.icon?n.icon.infoCardIconRenderer:null;n={id:Z,timestamp:x.O,type:"playlist",teaserText:g.w3(F.message),teaserDurationMs:Number(n.cueRanges[0].teaserDurationMs),startMs:Number(n.cueRanges[0].startCardActiveMs),
autoOpen:!!n.autoOpen,sessionData:Jl(x,Z,n,J),sponsored:!1,lw:Am(J,F,J.action),cq:J.trackingParams?g.qy(J.trackingParams):null,p9:F.trackingParams?g.qy(F.trackingParams):null,Aq:k&&k.trackingParams?g.qy(k.trackingParams):null,AD:kB(J.playlistThumbnail.thumbnails,258,290).url,customMessage:J.customMessage?g.w3(J.customMessage):null,playlistVideoCount:g.w3(J.playlistVideoCount),title:J.playlistTitle?g.w3(J.playlistTitle):"",metaInfo:[J.channelName?g.w3(J.channelName):"",J.videoCountText?g.w3(J.videoCountText):
""],url:Km({pause_on_navigation:!x.context.videoData.isLivePlayback,target:"new",value:Wvt(J.action)}),onClickCommand:null};Fo(x,n)}else if(n.content?.videoInfoCardContentRenderer){if(!n.cueRanges.length)return;J=n.content?.videoInfoCardContentRenderer;F=n.teaser.simpleCardTeaserRenderer;k=n.icon?n.icon.infoCardIconRenderer:null;n={id:Z,timestamp:x.O,type:"video",teaserText:g.w3(F.message),teaserDurationMs:Number(n.cueRanges[0].teaserDurationMs),startMs:Number(n.cueRanges[0].startCardActiveMs),autoOpen:!!n.autoOpen,
sessionData:Jl(x,Z,n,J),sponsored:!1,lw:Am(J,F,J.action),cq:J.trackingParams?g.qy(J.trackingParams):null,p9:F.trackingParams?g.qy(F.trackingParams):null,Aq:k&&k.trackingParams?g.qy(k.trackingParams):null,AD:kB(J.videoThumbnail.thumbnails,258,290).url,videoDuration:J.lengthString?g.w3(J.lengthString):null,customMessage:J.customMessage?g.w3(J.customMessage):null,title:J.videoTitle?g.w3(J.videoTitle):"",metaInfo:[J.channelName?g.w3(J.channelName):"",J.viewCountText?g.w3(J.viewCountText):""],isLiveNow:!!J.badge,
url:Km({pause_on_navigation:!x.context.videoData.isLivePlayback,target:"new",value:Wvt(J.action)}),onClickCommand:null};Fo(x,n)}x.O++},Pt2=function(x,n){return g.Ru(x.cards,Z=>Z.nV.id===n)},n2=function(x){g.mu(x.S.getRootNode(),"ytp-cards-shopping-active",jA2(x))},xB=function(x,n){if(n=Pt2(x,n))n===x.Z&&(x.Z=null),x.S.removeCueRange(n.nV.id),g.U3(n.l9),g.Ze(x.cards,n),x.w$(),n2(x)},Zq=function(x,n,Z){if(!x.B){x.X9.show();
x.C6=new g.eP(()=>{g.Eu(x.context.S.getRootNode(),g.EG.IV_DRAWER_OPEN)},0);
x.C6.start();x.ie.X(x.L,"mousewheel",k=>{x.VF.start();k.preventDefault();k=k||window.event;var J=0;k.type=="MozMousePixelScroll"?J=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?J=k.detail:J=k.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=J)x.L.scrollTop+=k});
x.B=!0;var F=g.Om();F&&x.oW&&x.N&&g.XI(F,[x.oW,x.N]);n={TRIGGER_TYPE:n};for(let k of x.cards)k.XN||(k.XN=!0,qf2(x.context.logger,k.nV.lw.cG,n)),F&&g.XI(F,[k.nV.cq]);Eo(x.S);Z&&(x.V=new g.eP(()=>{x.ue=x.G;x.jq.focus()},330),x.V.start())}},G6s=function(x){g.zm(x.q6(),[g.EG.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.KD(x.S,x.U,5);x.DU();x.G=g.R3("ytp-cards-button",x.S.getRootNode());x.jq=g.R3("iv-drawer-close-button",x.U);x.isInitialized=!0},lsk=function(x){x.Ze.push(g.X9("iv-teaser-shown",x.G1,x));
x.Ze.push(g.X9("iv-teaser-hidden",x.YH,x));x.Ze.push(g.X9("iv-teaser-clicked",x.SG,x));x.LT=!0},o8z=function(x,n){x.K=n;
var Z=x.S.getVideoData();if(!Z)return!1;Z=g.Ao(Z.getWatchNextResponse());if(Z?.markersMap)for(let k=0;Z?.markersMap.length>k;k++){var F=Z?.markersMap[k];if(F.key==="ERROR_CORRECTION_MARKERS"&&(F=F.value?.markers)&&F.length>0)return n.startMs=g.O(F[0],g.zuI)?.timeRangeStartMillis||0,x.K=null,!0}return!1},mkl=function(x,n){switch(n.type){case "simple":x=x.cw;
var Z=n.displayDomain?{D:"div",W:"iv-card-image-text",UR:n.displayDomain}:void 0;var F=Xjz(n);Z={D:"div",sR:["iv-card"],j:[{D:"a",W:"iv-click-target",A:{href:n.url?n.url.Z()||"":""},j:[Mv(n.imageUrl,Z),{D:"div",W:"iv-card-content",j:[c_("h2",void 0,n.title),F]}]}]};Z=new g.t(Z);Db(x,g.c8("iv-click-target",Z.element),n,n.url);n=Z;break;case "collaborator":x=x.cw;Z={D:"div",sR:["iv-card","iv-card-channel"],j:[{D:"a",sR:["iv-click-target"],A:{href:n.url.Z()||"","data-ytid":n.channelId},j:[Mv(n.profileImageUrl),
{D:"div",W:"iv-card-content",j:[rZ(n),{D:"h2",W:"iv-card-primary-link",UR:n.title},RI(n)]}]}]};Z=new g.t(Z);Db(x,g.c8("iv-click-target",Z.element),n,n.url);n=Z;break;case "playlist":x=x.cw;Z={D:"div",sR:["iv-card","iv-card-playlist"],j:[{D:"a",W:"iv-click-target",A:{href:n.url.Z()||""},j:[Mv(n.AD,{D:"div",W:"iv-card-image-overlay",j:[{D:"span",W:"iv-card-playlist-video-count",UR:n.playlistVideoCount}]}),{D:"div",W:"iv-card-content",j:[rZ(n),c_("h2","iv-card-primary-link",n.title),RI(n)]}]}]};Z=new g.t(Z);
Db(x,g.c8("iv-click-target",Z.element),n,n.url);n=Z;break;case "productListing":x=x.cw;var k=n.offers.length!=0;Z=["iv-card"];F="";var J=Xjz(n);k&&(Z.push("iv-card-product-listing"),F="iv-card-primary-link",J=n.offers[0],k=[],J.price&&k.push({D:"div",W:"iv-card-offer-price",UR:J.price}),J.merchant&&k.push({D:"div",W:"iv-card-offer-merchant",UR:J.merchant}),J={D:"div",j:k});k=n.url?n.url.Z()||"":"";Z={D:"div",sR:Z,A:{tabindex:"0"},j:[{D:"a",sR:["iv-card-image","iv-click-target"],A:{style:"background-image: url("+
n.imageUrl+");",href:k,"aria-hidden":"true",tabindex:"-1"}},{D:"div",W:"iv-card-content",j:[n.sponsored?{D:"div",W:"iv-card-sponsored",j:["Sponsored",{D:"div",W:"iv-ad-info-container",j:[{D:"div",W:"iv-ad-info",UR:"{{adInfo}}"},{D:"div",W:"iv-ad-info-icon-container",j:[{D:"div",W:"iv-ad-info-icon"},{D:"div",W:"iv-ad-info-callout"}]}]}]}:"",{D:"a",W:"iv-click-target",A:{href:k},j:[c_("h2",F,n.title),J]}]}]};Z=new g.t(Z);F=g.Yf("span");g.hM(F,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
Z.setContent(F,"adInfo");Db(x,g.c8("iv-click-target",Z.element),n,n.url);n=Z;break;case "video":x=x.cw;Z=n.isLiveNow?{D:"span",sR:["yt-badge","yt-badge-live"],UR:"LIVE NOW"}:null;Z={D:"div",sR:["iv-card","iv-card-video"],j:[{D:"a",W:"iv-click-target",A:{href:n.url?.Z()||""},j:[Mv(n.AD,n.videoDuration?{D:"span",W:"iv-card-video-duration",UR:n.videoDuration}:void 0),{D:"div",W:"iv-card-content",j:[rZ(n),c_("h2","iv-card-primary-link",n.title),RI(n),Z]}]}]};Z=new g.t(Z);Db(x,g.c8("iv-click-target",Z.element),
n,n.url);n=Z;break;default:return null}return n},fsk=function(x,n){if(!g.X6(x.S.getRootNode(),"ytp-cards-teaser-shown")){if(x.Z!==n){var Z=g.Om(),F=x.Z?x.Z.nV.Aq:x.Aq;
Z&&F&&g.EA(Z,[F]);x.Z=n;n2(x)}(Z=x.isInitialized&&x.q6().style.display=="none")||(Z=x.context.S.getPlayerState(),F=Z===0&&x.context.S.getCurrentTime()===0,Z=!(Z===1||Z===3||F));Z||n.nV.teaserDurationMs&&x.S.TA(!0,{teaserText:n.nV.teaserText,durationMs:n.nV.teaserDurationMs,onClickCommand:n.nV.onClickCommand,zH:n.nV.zH??null});x.RW.isActive()||((!x.B||!x.VF.isActive()&&x.Pw)&&CtJ(x,n),x.RW.start(910+n.nV.teaserDurationMs))}},jA2=function(x){return x.Z?x.Z.nV.type==="productListing":x.S.C("enable_wn_infocards")?
!!x.cards?.length&&g.cN(x.cards,n=>n.nV.type==="productListing"):g.cN(x.cards,n=>n.nV.type==="productListing")},CtJ=function(x,n){x.Y.Vd?(n=new GN([0,
x.L.scrollTop],[0,n.l9.offsetTop],600,Fvz),x.context.B.listen(n,"animate",Z=>{x.L.scrollTop=Z.y}),x.context.B.listen(n,"finish",Z=>{x.L.scrollTop=Z.y}),n.play()):(x.Y.Jh(!0),x.L.scrollTop=n.l9.offsetTop,x.Y.Jh(!1))},YB=function(x){return x.Z&&x.Z.nV?x.Z.nV:x.cards[0]&&x.cards[0].nV?x.cards[0].nV:null},Ist=function(x){var n=x.annotation.data;
"start_ms"in n&&"end_ms"in n&&x.addCueRange(Number(n.start_ms),Number(n.end_ms),x.annotation.id,()=>{x.show()},()=>{x.hide()})},g8o=function(x,n){var Z=r92(n).width;
g.px(n,Z);Z=new Cm(n,[Z,n.offsetTop],[Z-Z,n.offsetTop],200,Z4z);g.G(x,Z);x.context.B.listen(Z,"begin",()=>{g.nq(n,!0)});
Z.play()},vO=function(x,n,Z){Z.stopPropagation();
$ku(x);O4e(x,n);x.Z.focus()},H4k=function(x){var n=x.annotation.data;
if(x.annotation.style==="cta")var Z=6;else if(x.annotation.style==="video"||x.annotation.style==="playlist")Z=7;x.O=n.collapsedelay_ms||x.O;var F=["iv-promo","iv-promo-inactive"];x.q6().setAttribute("aria-hidden","true");x.q6().setAttribute("aria-label","Promotion");x.q6().tabIndex=0;var k=x.annotation.Xw(),J=n.image_url;if(J){var Y=x.createElement({D:"div",sR:["iv-promo-img","iv-click-target"]});J=x.createElement({D:"img",A:{src:J,"aria-hidden":"true"}});Y.appendChild(J);n.video_duration&&!n.is_live?
(J=x.createElement({D:"span",W:"iv-promo-video-duration",UR:n.video_duration}),Y.appendChild(J)):n.playlist_length&&(J=x.createElement({D:"span",W:"iv-promo-playlist-length",UR:n.playlist_length.toString()}),Y.appendChild(J));k&&tm(x,Y,k,x.annotation.id,n.session_data,void 0,Z)}k?(J=x.createElement({D:"a",W:"iv-promo-txt"}),g.KY(J,k.Z()),x.Z=J):x.Z=x.createElement({D:"div",W:"iv-promo-txt"});switch(x.annotation.style){case "cta":case "website":var v=x.createElement({D:"p",j:[{D:"strong",UR:n.text_line_1}]});
var L=x.createElement({D:"p",j:[{D:"span",W:"iv-promo-link",UR:n.text_line_2}]});if(J=n.text_line_3){F.push("iv-promo-website-card-cta-redesign");var S=x.createElement({D:"button",sR:["iv-promo-round-expand-icon","ytp-button"]});J=x.createElement({D:"button",sR:["iv-button","iv-promo-button"],j:[{D:"span",W:"iv-button-content",UR:J}]});var T=x.createElement({D:"div",W:"iv-promo-button-container"});T.appendChild(J);k&&tm(x,x.q6(),k,x.annotation.id,n.session_data,void 0,Z)}g.Eu(x.Z,"iv-click-target");
k&&tm(x,x.Z,k,x.annotation.id,n.session_data,void 0,Z);break;case "playlist":case "video":v=x.createElement({D:"p",j:[{D:"span",UR:n.text_line_1}]}),L=x.createElement({D:"p",j:[{D:"strong",UR:n.text_line_2}]}),n.is_live&&(v=L,L=x.createElement({D:"span",sR:["yt-badge","iv-promo-badge-live"],UR:"LIVE NOW"})),g.Eu(x.Z,"iv-click-target"),k&&tm(x,x.Z,k,x.annotation.id,n.session_data,void 0,Z),F.push("iv-promo-video")}v&&x.Z.appendChild(v);L&&x.Z.appendChild(L);x.N.appendChild(x.Z);T&&x.N.appendChild(T);
Z=x.createElement({D:"div",W:"iv-promo-actions"});x.L=x.createElement({D:"button",sR:["iv-promo-expand","ytp-button"]});x.L.title="Expand";x.context.Z.listen(x.L,"click",U=>{vO(x,5E3,U)});
Z.appendChild(x.L);g.nq(x.L,!1);x.context.Z.listen(x.q6(),"mouseover",x.VF,x);x.context.Z.listen(x.q6(),"mouseout",x.cw,x);x.context.Z.listen(x.q6(),"touchend",U=>{vO(x,5E3,U)});
x.B=x.createElement({D:"button",sR:["iv-promo-close","ytp-button"]});x.B.title="Close";x.context.Z.listen(x.B,"click",x.annotation.style==="cta"&&n.text_line_3?x.K:x.Ze,x);Z.appendChild(x.B);g.zm(x.q6(),F);Y&&(g.Lx(x.q6(),Y),S&&Y.appendChild(S));g.Lx(x.q6(),x.N);g.Lx(x.q6(),Z)},L2=function(x){x.U&&(g.hg.clearTimeout(x.U),x.U=null)},$ku=function(x){x.V.stop();
x.isCollapsed&&(g.ow(x.q6(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),x.isCollapsed=!1,x.Z&&x.Z.removeAttribute("aria-hidden"),g.nq(x.L,!1),g.nq(x.B,!0))},O4e=function(x,n){x.U||(x.U=g.dl(function(){L2(this);
Ngk(this)},n,x))},Ngk=function(x){x.isCollapsed||x.G||x.U||(g.Eu(x.q6(),"iv-promo-collapsed"),x.isCollapsed=!0,x.V.start())},qf2=function(x,n,Z){n&&(Z?SF(x,n.map(F=>g.kN(F,Z))):SF(x,n))},SF=function(x,n,Z,F){var k=1,J=void 0,Y=-1;
if(Z){let v=!1;J=()=>{k--;k||v||(clearTimeout(Y),v=!0,Z())};
Y=setTimeout(()=>{v=!0;Z()},1E3)}for(let v of n||[])k++,g.Jj(v,J);
F&&(k++,F!==0&&x.S.sendVideoStatsEngageEvent(F,J))},b4k=function(x){return x==="annotation-editor"||x==="live-dashboard"},pj6=function(x){x.U&&(x.player.removeEventListener("videodatachange",x.U),x.U=null)},Kvz=function(x){x=x.createElement({D:"div",
sR:["annotation","annotation-type-custom"]});g.nq(x,!1);return x},Un=function(x,n){var Z=!1,F=n.getElementsByTagName("annotations");
if(F&&!(F.length<1)&&(F=F[0].getAttribute("itct"))){var k=g.Om();if(k){var J=g.$b();J&&g.cS(g.UA)(void 0,k,J,[g.qy(F)])}}n=n.getElementsByTagName("annotation");for(F=0;F<n.length;F++){var Y=MBk(x,n[F]);k=null;try{a:{if(!Y){k=null;break a}var v=Y.id;J=/.+/;let u=typeof v==="string"&&J!=null&&v!=null&&v.match(J)?v:"",d=pm(Y.type,cSs),m=pm(Y.style,rSl),P=hDe(Y.data),H=P.length!==0?JSON.parse(P):{};b:{var L=Y.action;J=dkk;if(L==null){var S=null;break b}if(g.QO(L)){Y=[];for(let b of L){let M=J(b);M&&Y.push(M)}S=
Y;break b}let N=J(L);S=N?[N]:[]}J=S;k=u&&d?new RDJ(u,d,m,J,H):null}}catch(u){}if(k)if(k.type==="branding"||k.type==="promotion"){J=x;Y=k;var T=Kvz(J),U=null;switch(Y.type){case "branding":if(J.player.J().k6)break;J.player.C("web_player_overlay_positioned_layout")?(T.setAttribute("data-overlay-order","11"),J.player.tF(T,4,!0)):J.L.element.appendChild(T);U=new Dk6(T,TD(J),Y);break;case "promotion":g.KD(J.player,T,4),U=new tBt(T,TD(J),Y)}U&&U.Hw();U&&(g.G(x,U),x.O[k.id]=U)}else if(k.type==="card"||k.type===
"drawer"){x.Z||(x.Z=ASz(x),g.G(x,x.Z));if(k.type==="card"){T=x.Z;var h=(Z=k)&&Z.data&&Z.data.card_type;k=Z.data;if(h)switch(J=k.tracking||{},J={cG:J.impression,click:J.click,close:J.close,L_:J.teaser_impression,xI:J.teaser_click},Y=k.tracking_params||{},U=null,h){case "collaborator":Z={id:Z.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,
lw:J,cq:Y.card?g.qy(Y.card):null,p9:Y.teaser?g.qy(Y.teaser):null,Aq:Y.icon?g.qy(Y.icon):null,channelId:k.channel_id,customMessage:k.custom_message?k.custom_message:null,profileImageUrl:k.image_url,title:k.title,metaInfo:k.meta_info,url:Km({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};Fo(T,Z);break;case "playlist":Z={id:Z.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,
autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,lw:J,cq:Y.card?g.qy(Y.card):null,p9:Y.teaser?g.qy(Y.teaser):null,Aq:Y.icon?g.qy(Y.icon):null,AD:k.image_url,playlistVideoCount:k.playlist_video_count,customMessage:k.custom_message?k.custom_message:null,title:k.title,metaInfo:k.meta_info,url:Km({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};Fo(T,Z);break;case "productListing":k.signin_url&&(U=Km({target:"current",
value:k.signin_url}));h=[];let u=k.offers||[];for(let d=0;d<u.length;d++)h.push(new xVi(g.hA(u[d].merchant),g.hA(u[d].price)));Z={id:Z.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,lw:J,cq:Y.card?g.qy(Y.card):null,p9:Y.teaser?g.qy(Y.teaser):null,Aq:Y.icon?g.qy(Y.icon):null,imageUrl:k.image_url,displayDomain:k.display_domain?k.display_domain:
null,showLinkIcon:!!k.show_link_icon,OE:k.button_icon_url?k.button_icon_url:null,title:k.title,customMessage:k.custom_message?k.custom_message:null,url:Km({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),NZZ:U,OMF:k.signin_title?k.signin_title:void 0,PIW:k.signin_message?k.signin_message:void 0,offers:h,onClickCommand:null};Fo(T,Z);break;case "simple":Z={id:Z.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,
startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,lw:J,cq:Y.card?g.qy(Y.card):null,p9:Y.teaser?g.qy(Y.teaser):null,Aq:Y.icon?g.qy(Y.icon):null,imageUrl:k.image_url,displayDomain:k.display_domain?k.display_domain:null,showLinkIcon:!!k.show_link_icon,OE:k.button_icon_url?k.button_icon_url:null,title:k.title,customMessage:k.custom_message?k.custom_message:null,url:Km({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};
Fo(T,Z);break;case "video":Z={id:Z.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,lw:J,cq:Y.card?g.qy(Y.card):null,p9:Y.teaser?g.qy(Y.teaser):null,Aq:Y.icon?g.qy(Y.icon):null,AD:k.image_url,videoDuration:k.video_duration||null,customMessage:k.custom_message?k.custom_message:null,title:k.title,metaInfo:k.meta_info,isLiveNow:!!k.is_live_now,
url:Km({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null},Fo(T,Z)}}else wj$(x.Z,k);Z=!0}}Z&&(Eo(x.player),x.Y())},n0z=function(x){var n=x.player.J();
x=x.player.getVideoData();return(n.annotationsLoadPolicy||x.annotationsLoadPolicy)===1&&!x.Tv||n.Pw.get(x.videoId)||x.vL()||g.S6(x)?!0:!1},Zt6=function(x,n){n=!n.isCued()&&!n.Z(1024);
x.L.Jh(n);x.B.Jh(n)},JRe=function(x,n){var Z=n.videoId,F=J=>{var Y=x.loadNumber;
x.N=null;x.loaded&&x.loadNumber===Y&&x.player.getVideoData().videoId===Z&&(J=g.YL(J)&&J.responseXML?J.responseXML:null)&&(Un(x,J),g.Eu(x.player.getRootNode(),"iv-module-loaded"))};
g.bH()&&(F=F3u(x,F));var k={format:"XML",onFinish:F,onError:()=>{x.N=null},
urlParams:{}};n.isPharma&&(k.urlParams.pharma="1");k.method="POST";k.withCredentials=!0;(F=x.player.J().Pw.get(Z))&&itz(k,F);F=F&&F.fb;if(!n.B3||F)x.U=()=>{if(!x.K)x.onVideoDataChange(k);var J=x.player.getVideoData();J?.Wo()&&!x.Ze&&kTu(x,J)},x.player.addEventListener("videodatachange",x.U)},uc=function(x,n){var Z=!1;
x.Z||(x.Z=ASz(x),g.G(x,x.Z));for(var F of n.cards||[])F.cardRenderer&&(VBJ(x.Z,F.cardRenderer),Z=!0);Z&&(x.player.getVideoData()?.Wo()||(Z=x.Z,F=n.headerText?g.w3(n.headerText):"",g.hM(Z.Zc,F),Z.G&&Z.G.setAttribute("data-tooltip-title",F),Z.context.videoData.eventId&&(Z.eventId=Z.context.videoData.eventId),Z.oW=n.trackingParams?g.qy(n.trackingParams):null,Z.N=n.closeButton.infoCardIconRenderer.trackingParams?g.qy(n.closeButton.infoCardIconRenderer.trackingParams):null,Z.Aq=n.icon.infoCardIconRenderer.trackingParams?
g.qy(n.icon.infoCardIconRenderer.trackingParams):null,x.Y()),Eo(x.player))},kTu=function(x,n){if(n=n.getWatchNextResponse()?.cards?.cardCollectionRenderer)x.Ze=!0,uc(x,n),n.headerText&&x.Sb&&(n=g.w3(n.headerText),x.Sb.setAttribute("data-tooltip-title",n))},F3u=function(x,n){return(...Z)=>{x.MX()||x.Hw.push(g.YN.Us(()=>{n(...Z)}))}},itz=function(x,n){x.method="POST";
x.postParams=x.postParams||{};n.fb&&(x.postParams.ic_coll=n.fb);n.NT&&(x.postParams.ic_track=n.NT)},MBk=function(x,n){var Z={};
for(var F of n.attributes)Z[F.name]=F.nodeValue;for(F=0;F<n.childNodes.length;F++){let J=n.childNodes[F];if(!g.Xr(J)||J.nodeType!=1)continue;var k=void 0;if(Z[J.tagName])k=Z[J.tagName];else if(J.tagName==="data"){J.childNodes.length>0&&(k=J.childNodes[0].nodeValue,Z[J.tagName]=typeof k==="string"?k.trim():k);continue}else k=[],Z[J.tagName]=k;J&&J.tagName==="TEXT"?J.childNodes.length===1&&J.childNodes[0].nodeType===3?k.push(J.childNodes[0].nodeValue):k.push(""):J&&k.push(MBk(x,J))}return Z},TD=function(x){if(!x.G){let n=
new YOz(x);
g.G(x,n);let Z=new g.M8(x);g.G(x,Z);x.G=new v0e(n,Z,x.player.J(),x.player.getVideoData(),x.logger,x.player,x.Oc)}return x.G},L3z=function(x){var n=x.player.getVideoData();
if(n.bv){var Z=x.player.J().Pw.get(n.videoId);if(Z){var F={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(k,J,Y)=>{k=x.loadNumber;J=n.videoId;x.loaded&&x.loadNumber===k&&x.player.getVideoData().videoId===J&&(Y=g.YL(Y)&&Y.responseXML?Y.responseXML:null)&&Un(x,Y)}};
g.bH()&&(F.onFinish=F3u(x,F.onFinish));F.postParams={ic_only:"1"};itz(F,Z);x.K=!0;g.sT(n.bv,F)}}},ASz=function(x){var n=new g.t({D:"div"});
g.nq(n.element,!1);var Z=new SOs(x.player,n.element,TD(x));g.G(Z,n);n.kP(x.L.element);Z.Hw();return Z},TWs=function(x,n,Z,F,k){if(!x.player.J().k6){var J=[];
n.navigationEndpoint&&g.O(n.navigationEndpoint,g.XB)&&g.O(n.navigationEndpoint,g.XB).browseId&&J.push(new as6("openUrl","click",new ySl(`/channel/${g.O(n.navigationEndpoint,g.XB).browseId}`,"new",!0,!0)));var Y=n.watermark.thumbnails[0];F={channel_name:n.channelName,end_ms:n.endTimeMs,image_height:Y.height,image_type:1,image_url:Y.url,image_width:Y.width,is_mobile:!1,session_data:{annotation_id:Z,ei:k,feature:"iv",itct:n.trackingParams,src_vid:F},start_ms:n.startTimeMs};if(n.subscribeButton&&g.O(n.subscribeButton,
g.HL)){F.channel_id=g.O(n.subscribeButton,g.HL).channelId;n=g.O(n.subscribeButton,g.HL);Y=k=null;n.subscribed?(n.subscriberCountWithUnsubscribeText&&(k=g.w3(n.subscriberCountWithUnsubscribeText)),n.subscriberCountText&&(Y=g.w3(n.subscriberCountText))):(n.subscriberCountText&&(k=g.w3(n.subscriberCountText)),n.subscriberCountWithSubscribeText&&(Y=g.w3(n.subscriberCountWithSubscribeText)));let v=g.O(n.signInEndpoint?.commandMetadata,g.W7)?.url||"";n={subscribeText:g.w3(n.unsubscribedButtonText),subscribeCount:k||
"",unsubscribeText:g.w3(n.subscribedButtonText),unsubscribeCount:Y||"",enabled:n.enabled||!1,classic:!1,subscribed:n.subscribed||!1,feature:"iv",signInUrl:v};F.standalone_subscribe_button_data=n}J=new RDJ(Z,"branding","branding",J,F);F=Kvz(x);x.player.C("web_player_overlay_positioned_layout")?(F.setAttribute("data-overlay-order","11"),x.player.tF(F,4,!0)):x.L.element.appendChild(F);J=new Dk6(F,TD(x),J);J.Hw();g.G(J,J);x.O[Z]=J}};
g.BH.prototype.TA=g.iI(43,function(x,n){var Z=g.sU(this.PD());Z&&Z.TA(x,n)});
var W_={},oI=null;g.wv(GN,g.Gm);g.W=GN.prototype;g.W.getDuration=function(){return this.duration};
g.W.play=function(x){if(x||this.Z==0)this.progress=0,this.coords=this.L;else if(this.isPlaying())return!1;m1(this);this.startTime=x=g.Gc();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.U=this.startTime;this.progress||this.Ac();this.Ey("play");this.isPaused()&&this.Ey("resume");this.Z=1;var n=g.zc(this);n in W_||(W_[n]=this);t$u();A92(this,x);return!0};
g.W.stop=function(x){m1(this);this.Z=0;x&&(this.progress=1);xkk(this,this.progress);this.onStop();this.QK()};
g.W.pause=function(){this.isPlaying()&&(m1(this),this.Z=-1,this.Ey("pause"))};
g.W.Bw=function(){this.Z==0||this.stop(!1);this.Ey("destroy");GN.ji.Bw.call(this)};
g.W.destroy=function(){this.dispose()};
g.W.fi=function(){this.Ey("animate")};
g.W.Ey=function(x){this.dispatchEvent(new n8s(x,this))};
g.wv(n8s,g.Xm);g.wv(l3,GN);l3.prototype.B=function(){};
l3.prototype.fi=function(){this.B();l3.ji.fi.call(this)};
l3.prototype.QK=function(){this.B();l3.ji.QK.call(this)};
l3.prototype.Ac=function(){this.B();l3.ji.Ac.call(this)};
g.wv(Cm,l3);Cm.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var YOz=class extends g.sO{constructor(x){super();this.L=x||window;this.Z=[]}listen(x,n,Z,F){Z=(0,g.WN)(Z,F||this.L);x=g.yy(x,n,Z);this.Z.push(x);return x}EM(x,n,Z,F){Z=(0,g.WN)(Z,F||this.L);x=Ro2(x,n,Z);this.Z.push(x);return x}nx(x){g.BA(x);g.Ze(this.Z,x)}removeAll(){g.BA(this.Z);this.Z.length=0}Bw(){this.removeAll();super.Bw()}};var yRe=class extends g.Oe{constructor(x){super(x);this.U=this.endscreen=null;this.L={};this.O={};this.V=this.B=null;this.G=[];this.Z=null;this.Ze=!0;this.N=0;x=x.J();this.Y=g.ho(x)||x.VF==="profilepage";this.events=new g.EE(this);g.G(this,this.events);this.events.X(this.player,g.OY("creatorendscreen"),this.onCueRangeEnter);this.events.X(this.player,g.HK("creatorendscreen"),this.onCueRangeExit);this.events.X(this.player,"resize",this.jG);this.events.X(window,"focus",this.K);this.load();var n=g.Yf("STYLE");
(g.M3("HEAD")[0]||document.body).appendChild(n);this.addOnDisposeCallback(()=>{g.U3(n)});
n.sheet&&(n.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),n.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!jW(this)){var x=g.WOh(this.player.getVideoData());x?(x=P_(x,k6k(this)),qv(this,x,!1)):Lv$(this)}}unload(){qv(this,null);this.U&&(this.U.abort(),this.U=null);super.unload()}SC(x,n){return jW(this)?x==="loadCustomEndscreenRenderer"?(x=P_(n,"new"),qv(this,x),!0):null:null}getOptions(){return jW(this)?["loadCustomEndscreenRenderer"]:[]}jG(){if(this.endscreen&&this.endscreen.elements){var x=this.player.getVideoContentRect();if(x&&x.width!==0&&x.height!==0){var n=this.player.getPlayerSize();
if(n&&n.width!==0&&n.height!==0){var Z=x.width/x.height;var F=0;var k=-1;for(var J=0;J<UVe.length;J++){var Y=Math.abs(n.width-UVe[J]);if(k===-1||F>=Y)k=J,F=Y}F=uhl[k];this.B&&g.jd(this.B.element,"outline-width",Math.max(n.width,n.height)+"px");for(n=0;n<this.endscreen.elements.length;++n){J=this.endscreen.elements[n].id;k=this.L[J];Y=this.O[J];if(!k||!Y)continue;let L=Y.width*Z/Y.aspectRatio;var v=Math.round(Y.width*x.width);J=Math.round(L*x.height);let S=x.left+Math.round(Y.left*x.width),T=x.top+
Math.round(Y.top*x.height);g.AM(k.element,v,J);g.px(k.element,S,T);g.ow(k.element,hak);v>256||J>256?g.Eu(k.element,"ytp-ce-large-round"):v>96||J>96?g.Eu(k.element,"ytp-ce-medium-round"):g.Eu(k.element,"ytp-ce-small-round");g.ow(k.element,eao);v=Y.left+Y.width/2;Y=Y.top+L/2;g.Eu(k.element,v<=.5&&Y<=.5?"ytp-ce-top-left-quad":v>.5&&Y<=.5?"ytp-ce-top-right-quad":v<=.5&&Y>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ow(k.element,uhl);g.Eu(k.element,F);(k=g.r5(document,"div","ytp-ce-expanding-overlay-body",
k.element)[0])&&g.jd(k,"height",`${J}px`)}}}}}onCueRangeEnter(x){if(this.endscreen)if(x.getId()==="ytp-ce-in-endscreen")Nv(this,this.endscreen.impressionUrls),(x=g.Om())&&this.endscreen.visualElement&&g.QD(x,this.endscreen.visualElement),this.Z&&(g.Eu(this.Z,"ytp-ce-element-show"),this.Z.removeAttribute("aria-hidden"),this.player.s5()?g.Eu(this.Z,"ytp-ce-hide-button-lower"):g.WC(this.Z,"ytp-ce-hide-button-lower"));else{x=x.getId().substring(15);var n=this.L[x],Z=this.O[x];g.Eu(n.element,"ytp-ce-element-show");
n.element.removeAttribute("aria-hidden");n=this.player.getRootNode();g.Eu(n,"ytp-ce-shown");Nv(this,Z.impressionUrls);(n=g.Om())&&g.QD(n,Z.visualElement);this.player.J().Ze&&g.Wf(this.player,"endscreenelementshown",x)}}onCueRangeExit(x){if(x.getId()==="ytp-ce-in-endscreen")this.Z&&(g.WC(this.Z,"ytp-ce-element-show"),this.Z.setAttribute("aria-hidden","true"));else{x=x.getId().substring(15);var n=this.L[x];g.WC(n.element,"ytp-ce-element-show");n.element.setAttribute("aria-hidden","true");n=this.player.getRootNode();
g.WC(n,"ytp-ce-shown");this.player.J().Ze&&g.Wf(this.player,"endscreenelementhidden",x)}}K(x){x.target===window&&(new g.eP(()=>{for(let n of Object.values(this.L))g.ow(n.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Jh(x){for(let n of Object.values(this.L))x?n.element.setAttribute("hidden",""):n.element.removeAttribute("hidden")}PJ(x){this.Z&&this.player.getRootNode().removeChild(this.Z);
x&&(g.Eu(x,"ytp-ce-hide-button-container"),this.Z=x,g.KD(this.player,this.Z,4))}},UVe=[346,426,470,506,570,640,853,1280,1920],uhl="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),eao=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],hak=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var ySl=class{constructor(x,n,Z,F){this.value=x;this.target=n;this.showLinkIcon=Z;this.L=F}Z(){return this.value?this.value:null}},eDu={b6:"current",yg:"new"};var as6=class{constructor(x,n,Z){this.type=x;this.trigger=n;this.url=Z}},sAe={CLOSE:"close",Ke:"openUrl",SUBSCRIBE:"subscribe"},Bgt={Sw:"click",CLOSE:"close",T5:"hidden",LU$:"rollOut",cZU:"rollOver",O6e:"shown"};var RDJ=class{constructor(x,n,Z,F,k){this.id=x;this.type=n;this.style=Z;this.data=k;this.action=F||[]}Xw(){var x=QAo(this,n=>n.type==="openUrl"&&n.url!=null);
return x?x.url:null}},rSl={Dj:"anchored",SB:"branding",CHANNEL:"channel",ak:"cta",Au:"highlightText",ze:"label",PLAYLIST:"playlist",POPUP:"popup",eyF:"speech",SUBSCRIBE:"subscribe",Gje:"title",VIDEO:"video",d6$:"website"},cSs={SB:"branding",hw:"card",Aw:"drawer",R_:"highlight",wv:"marker",sZ:"promotion",TEXT:"text",KbR:"widget"};var sE6=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
BWJ=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var a4J=class{constructor(x,n){this.context=x;this.Z=n}};var xVi=class{constructor(x,n){this.merchant=x;this.price=n}};var dV2=class extends g.sO{constructor(x,n){super();this.element=x;this.context=n;this.AZ=!1;this.n6=new Map;this.tZ=new Map;this.context.S.addEventListener(g.OY("annotations_module"),Z=>{(Z=this.n6.get(Z))&&Z.apply(this)});
this.context.S.addEventListener(g.HK("annotations_module"),Z=>{(Z=this.tZ.get(Z))&&Z.apply(this)})}addCueRange(x,n,Z,F,k){x=new g.Zu(x,n,{id:Z,
namespace:"annotations_module"});F&&this.n6.set(x,F);k&&this.tZ.set(x,k);this.context.S.Zr([x],1)}Hw(){this.context.L.subscribe("resize",this.w$,this)}q6(){return this.element}r$(x,n,Z,F,k,J){if(this.AZ)return!1;J&&(J.stopPropagation(),J.preventDefault());this.navigate(x,Z,F,k);return!1}show(){}hide(){}destroy(){g.U3(this.q6())}w$(){}navigate(x,n,Z,F){var k=x.Z();if(k){var J=zD6(k,x.target),Y=()=>{x.L&&this.context.S.pauseVideo();var v=this.context.videoData.B7||!1,L=g.AC(k||"");v&&L&&(L.v||L.list)?
this.context.S.Iu(L.v,n,L.list,!1):g.zb(k||"",J==="current"?"_top":void 0,n)};
J==="new"&&(Y(),Y=null);SF(this.context.logger,Z,Y,F);E8u(k)||(Z=g.Om(),F=n.itct,Z&&F&&g.zf(Z,g.qy(F)))}}Bw(){this.n6.clear();this.tZ.clear();super.Bw()}createElement(x){x=new g.t(x);g.G(this,x);return x.element}};var SOs=class extends dV2{constructor(x,n,Z){super(n,Z);this.S=x;this.eventId=null;this.LT=this.Pw=this.fT=this.B=this.isInitialized=!1;this.cards=[];this.jq=this.G=this.ue=this.V=this.C6=this.Z=null;this.Ze=[];this.K=this.N=this.Aq=this.oW=null;this.O=0;this.VF=new g.eP(()=>{},Z.hZ.Rf?4E3:3E3);
g.G(this,this.VF);this.RW=new g.eP(()=>{});
g.G(this,this.RW);this.cw=new a4J(Z,(F,k,J,Y,v,L)=>{tm(this,F,k,J,Y,v,L)});
this.Y=new g.t({D:"div",W:"iv-drawer",A:{id:"iv-drawer"},j:[{D:"div",W:"iv-drawer-header",A:{"aria-role":"heading"},j:[{D:"span",W:"iv-drawer-header-text"},{D:"button",sR:["iv-drawer-close-button","ytp-button"],A:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",W:"iv-drawer-content"}]});g.G(this,this.Y);this.U=this.Y.element;this.X9=new g.Ks(this.Y,330);g.G(this,this.X9);this.Zc=g.R3("iv-drawer-header-text",this.U);this.L=g.R3("iv-drawer-content",this.U);this.addCueRange(0,Z.videoData.lengthSeconds*
1E3,"",()=>{this.fT&&Zq(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.fT=this.B)&&ic(this)});
this.ie=new g.EE(this);g.G(this,this.ie);this.S.addEventListener("videodatachange",this.s0.bind(this))}s0(){this.K&&Fo(this,this.K)}isAvailable(){var x;if(x=!!this.cards.length)(x=this.S.getRootNode())?(x=g.xd(x),x=173<x.width&&173<x.height):x=!1;return x}w$(){var x=this.isAvailable();g.nq(this.q6(),x);g.mu(this.context.S.getRootNode(),g.EG.IV_DRAWER_ENABLED,x);Eo(this.S)}destroy(){this.S.TA(!1);try{this.S.getRootNode().removeChild(this.U)}catch(x){}g.E0(this.Ze);this.ie.L();this.C6&&this.C6.dispose();
this.V&&this.V.dispose();super.destroy()}DU(){this.context.Z.listen(g.R3("iv-drawer-close-button",this.U),"click",this.kH,this);this.context.Z.listen(this.L,"touchend",()=>{this.VF.start()});
this.context.Z.listen(this.L,"scroll",this.WD,this);this.context.L.subscribe("onHideControls",()=>{this.Pw=!0});
this.context.L.subscribe("onShowControls",()=>{this.Pw=!1});
this.context.L.subscribe("onVideoAreaChange",()=>{this.Pw=g.X6(this.S.getRootNode(),"ytp-autohide")});
this.Ze.push(g.X9("iv-button-shown",this.yd,this));this.Ze.push(g.X9("iv-button-hidden",this.M6,this));lsk(this)}findLastIndex(x){if(this.cards.length===0)return 0;var n=g.DQ(this.cards,Z=>x.nV.startMs>Z.nV.startMs||x.nV.startMs===Z.nV.startMs&&x.nV.timestamp>=Z.nV.timestamp?!0:!1);
return n===-1?0:n+1}kH(){if(this.B){SF(this.context.logger,YB(this).lw.close);var x=g.Om();x&&this.N&&g.zf(x,this.N);ic(this)}}WD(){g.mu(this.U,"iv-drawer-scrolled",this.L.scrollTop>0)}yd(){var x=g.Om(),n=YB(this);n=n?n.Aq:this.Aq;x&&n&&g.XI(x,[n])}M6(){var x=g.Om(),n=YB(this);n=n?n.Aq:this.Aq;x&&n&&g.EA(x,[n])}G1(){var x=YB(this);SF(this.context.logger,x.lw.L_);var n=g.Om();if(n&&x)if(this.S.C("web_infocards_teaser_show_logging_fix")){let Z=[];x.p9&&Z.push(x.p9);x.Aq&&Z.push(x.Aq);Z.length>0&&g.XI(n,
Z)}else g.XI(n,[x.p9,x.Aq])}YH(){var x=g.Om(),n=YB(this);x&&n&&g.EA(x,[n.p9])}SG(x){var n=YB(this),Z=g.Om();this.Z?x?(x=this.context.logger,SF(x,n.lw.xI),x.S.sendVideoStatsEngageEvent(4,void 0),Z&&n.p9&&g.zf(Z,n.p9)):(x=this.context.logger,SF(x,n.lw.xI),x.S.sendVideoStatsEngageEvent(4,void 0),Z&&n.Aq&&g.zf(Z,n.Aq)):(x=this.context.logger,SF(x,n.lw.xI),x.S.sendVideoStatsEngageEvent(4,void 0),Z&&this.Aq&&g.zf(Z,this.Aq))}};var QEk=class extends dV2{constructor(x,n,Z){super(x,n);this.annotation=Z;this.isActive=!1}Hw(){super.Hw();Ist(this)}show(){super.show();var x=g.Om(),n=this.annotation.data;x&&n&&(n=n.session_data)&&g.XI(x,[g.qy(n.itct)])}hide(){super.hide();var x=g.Om(),n=this.annotation.data;x&&n&&(n=n.session_data)&&g.EA(x,[g.qy(n.itct)])}};var Dk6=class extends QEk{constructor(x,n,Z){super(x,n,Z);this.Z=null;this.L=!1}show(){if(!this.isActive){super.show();if(!this.L){g.Eu(this.q6(),"iv-branding");let x=this.annotation.data;this.Z=this.createElement({D:"img",sR:["branding-img","iv-click-target"],A:{"aria-label":"Channel watermark",src:x.image_url,width:x.image_width,height:x.image_height}});g.nq(this.Z,!1);let n=this.createElement({D:"button",sR:["branding-img-container","ytp-button"]});n.appendChild(this.Z);this.q6().appendChild(n);
let Z=this.annotation.Xw();Z&&tm(this,n,Z,this.annotation.id,x.session_data);this.L=!0}g.nq(this.q6(),!0);this.isActive=!0;if(this.Z){try{g8o(this,this.Z)}catch{}g.Eu(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",`${this.Z.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.nq(this.q6(),!1),this.isActive=!1,g.WC(this.context.S.getRootNode(),"ytp-branding-shown"))}destroy(){g.WC(this.context.S.getRootNode(),
"ytp-branding-shown");super.destroy()}};var v0e=class{constructor(x,n,Z,F,k,J,Y){this.Z=x;this.B=n;this.hZ=Z;this.videoData=F;this.logger=k;this.S=J;this.L=Y}};var tBt=class extends QEk{constructor(x,n,Z){super(x,n,Z);this.G=this.isCollapsed=this.Y=!1;this.O=5E3;this.L=this.B=this.Z=this.U=null;this.N=this.createElement({D:"div",sR:["iv-promo-contents"]});this.V=new g.eP(()=>{this.Z.setAttribute("aria-hidden","true");g.nq(this.B,!1);g.nq(this.L,!0)},700,this);
g.G(this,this.V)}show(){this.isActive||(super.show(),this.Y||(H4k(this),this.Y=!0),g.nq(this.q6(),!0),g.dl(function(){g.WC(this.q6(),"iv-promo-inactive")},100,this),this.q6().removeAttribute("aria-hidden"),this.isActive=!0,L2(this),$ku(this),O4e(this,this.O))}hide(){this.isActive&&(g.Eu(this.q6(),"iv-promo-inactive"),this.isActive=!1,this.q6().setAttribute("aria-hidden","true"))}r$(x,n,Z,F,k,J){return this.isCollapsed?!1:super.r$(x,n,Z,F,k,J)}VF(x){this.G=!0;
vO(this,500,x)}cw(){this.G=!1;Ngk(this)}Ze(x){x.stopPropagation();this.hide()}K(x){x.stopPropagation();L2(this);this.isCollapsed=!0;g.Eu(this.q6(),"iv-promo-collapsed-no-delay");this.V.start()}destroy(){this.V.dispose();super.destroy()}};var Xc$=class{constructor(x){this.S=x}};g.T1("annotations_module",class extends g.Oe{constructor(x){super(x);this.Ze=this.K=!1;this.loadNumber=0;this.O={};this.logger=new Xc$(this.player);this.V=new g.EE(this);this.N=this.U=null;this.events=new g.EE(this);this.Sb=this.G=this.Z=null;this.Hw=[];g.G(this,this.V);this.V.X(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.V.X(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.V.X(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.V.X(this.player,"resize",Z=>{this.publish("resize",Z)});
this.V.X(this.player,"presentingplayerstatechange",Z=>{this.publish("presentingplayerstatechange",Z)});
this.subscribe("presentingplayerstatechange",this.VF,this);this.subscribe("resize",this.Y,this);this.player.J().Pw.subscribe("vast_info_card_add",this.cw,this);g.G(this,this.events);this.w$=this.createElement({D:"div",W:"video-custom-annotations"});this.L=new g.t({D:"div",sR:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.L);g.KD(this.player,this.L.element,4);this.L.hide();this.B=new g.t({D:"div",sR:["ytp-iv-video-content"]});g.G(this,this.B);x=this.createElement({D:"div",W:"video-annotations"});
x.appendChild(this.w$);this.B.element.appendChild(x);this.Gu()?this.load():this.player.C("web_fix_annotations")&&(this.U=()=>{this.loaded||this.MX()||!this.Gu()||(pj6(this),this.load())},this.player.addEventListener("videodatachange",this.U));
var n=this.createElement({D:"style"});(g.M3("HEAD")[0]||document.body).appendChild(n);this.addOnDisposeCallback(()=>{g.U3(n)});
if(x=n.sheet){for(let Z of sE6)x.insertRule(Z,0);for(let Z of BWJ)x.insertRule(Z,0)}}SC(x,n){if(!b4k(this.player.J().playerStyle))return null;switch(x){case "loadCustomAnnotationsXml":return(x=g.nJ(n))&&Un(this,x),!0;case "removeCustomAnnotationById":return n&&this.Z&&(xB(this.Z,n),Eo(this.player)),!0}return null}getOptions(){return b4k(this.player.J().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}Gu(){var x=this.player.getVideoData(),n=x.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return x.B7||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.C("web_fix_annotations")?n0z(this)?n?.isWatermarkEnforced===!0?!0:n?.isAnnotationsEnabled??!1:!1:n0z(this)}Y(){if(this.B){var x=this.player.YP().getVideoContentRect(!0);g.AM(this.B.element,x.width,x.height);g.px(this.B.element,x.left,x.top)}if(this.Z){var n=this.player.Px();x=this.Z;n=n.width;g.mu(x.U,"iv-drawer-small",n<=426);g.mu(x.U,"iv-drawer-big",n>=1280)}}VF(x){Zt6(this,x.state);x.state.Z(2)&&(this.s5()&&this.Lc()&&this.player.getPresentingPlayerType()!==
2&&this.zA(!1),this.TA(!1))}load(){super.load();Zt6(this,this.player.getPlayerStateObject());this.loadNumber++;var x=this.player.getVideoData();JRe(this,x);g.KD(this.player,this.B.element,4);this.Y();var n=g.S6(x),Z=x.vL();if(this.player.C("web_fix_annotations")){if(n&&(n.featuredChannel&&TWs(this,n.featuredChannel,n.annotationId||"branding",x.videoId||null,x.eventId||null),n=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,n?.isWatermarkEnforced&&!n?.isAnnotationsEnabled))return;
Z&&uc(this,Z)}else Z&&uc(this,Z),n&&n.featuredChannel&&TWs(this,n.featuredChannel,n.annotationId||"branding",x.videoId||null,x.eventId||null);this.Sb=g.R3("ytp-cards-button",this.player.getRootNode());x.Wo()&&kTu(this,x)}onVideoDataChange(){}unload(){this.player.fH("annotations_module");for(let x of Object.keys(this.O))this.O[x].destroy();this.G=null;this.Z&&(this.Z.destroy(),this.Z=null,Eo(this.player));this.K=!1;this.N&&(this.N.abort(),this.N=null);this.Ze=!1;this.O={};this.L.hide();super.unload();
this.B.detach();pj6(this)}cw(x){x===this.player.getVideoData().videoId&&(this.loaded?L3z(this):this.load())}s5(){return this.Z?.isAvailable()||this.Ze}Lc(){return!!this.Z&&this.Z.B}zA(x,n=!1,Z){this.s5();this.Z&&(x?Z?Zq(this.Z,Z,n):Zq(this.Z,"YOUTUBE_DRAWER_AUTO_OPEN",n):ic(this.Z))}TA(x,n){this.player.publish(x?"cardsteasershow":"cardsteaserhide",n)}Bw(){this.player.J().Pw.unsubscribe("vast_info_card_add",this.cw,this);g.WC(this.player.getRootNode(),g.EG.IV_DRAWER_OPEN);var x=this.Hw,n=g.YN;for(let Z=
0,F=x.length;Z<F;Z++)n.oC(x[Z]);this.Hw.length=0;super.Bw()}createElement(x){x=new g.t(x);g.G(this,x);return x.element}});g.T1("creatorendscreen",yRe);})(_yt_player);
