(function(g){var window=this;'use strict';var zai=async function(x,n,Z){x.L=g.sT(n,Z)},hl=function(x){x.isActive()||x.start()},W36=function(x,n){var Z=new g.KS;
Z.languageCode=x.languageCode;Z.languageName=x.languageName;Z.name=x.name;Z.displayName=x.displayName;Z.kind=x.kind;Z.isDefault=!1;Z.Z=x.Z;Z.isTranslateable=x.isTranslateable;Z.vssId=x.vssId;Z.url=x.url;Z.translationLanguage=n;x.xtags&&(Z.xtags=x.xtags);x.captionId&&(Z.captionId=x.captionId);return Z},eF=function(x,n){return n?x.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},o0i=function(x){return g.WU(x)||x.C("web_enable_caption_language_preference_stickiness")},mV2=async function(x,n){x=
x+"|"+n;
n=await g.Cz();if(!n)throw g.k$("gct");return(await g.h0(n)).get("captions",x)},GT2=function(x,n,Z){mV2(x,n).then(F=>{F&&Z(F.trackData,new g.KS(F.metadata))})},yM=function(x){if(!l4J.test(x))throw Error("'"+x+"' is not a valid hex color");
x.length==4&&(x=x.replace(Cgk,"#$1$1$2$2$3$3"));x=x.toLowerCase();x=parseInt(x.slice(1),16);return[x>>16,x>>8&255,x&255]},f4s=function(){var x={},n="suggest_correction"in g.fs?g.fs.suggest_correction:"Edit caption";
n=n||"";for(let Z in x){let F=()=>String(x[Z]);
n=n.replace(new RegExp("\\$\\{"+Z+"\\}","gi"),F);n=n.replace(new RegExp("\\$"+Z,"gi"),F)}return n},sn=function(){return g.WA("yt-player-caption-display-settings")},wce=function(x,n){var Z=g.sk(x.segments,n);
Z>=0||Z<0&&(-Z-1)%2===1||(Z=-Z-1,Z>0&&n-x.segments[Z-1]===1&&Z<x.segments.length&&x.segments[Z]-n===1?(g.nk(x.segments,Z),g.nk(x.segments,Z-1)):Z>0&&n-x.segments[Z-1]===1?x.segments[Z-1]=n:Z<x.segments.length&&x.segments[Z]-n===1?x.segments[Z]=n:(g.Tu(x.segments,Z,0,n),g.Tu(x.segments,Z+1,0,n)))},Vce=function(x){return x.Z&&x.Z.V?x.Z.V+x.player.Qd()<x.player.getCurrentTime():!1},Pgz=function(x,n){if(x.policy.ra&&x.player.qa()){var Z=g.DP(n,x.policy,{});
Z.set("pot",x.player.qa());Z=Z.Xw()}else Z=g.DP(n,x.policy,{}).Xw();var F={format:"RAW",withCredentials:!0};if(x.policy.w$){F.method="POST";let Y=n.U;Y&&Object.keys(Y).length>0?F.postBody=g.X8(Y,g.$G):F.postBody=(0,g.ge)([120,0])}x.V&&(F.responseType="arraybuffer");var k=++x.Hw,J=(0,g.K)();x.L=g.XK(Z,F,3,100,-1,Y=>{Y.errorCode==="net.timeout"&&x.player.L6("capnt",{rn:k++})}).then(Y=>{if(x.policy.Tv&&k%100===1){var v=(0,g.K)();
x.player.L6("caprsp",{rn:k,ms:v-J,kb:(Y.xhr.responseText.length/1024).toFixed()})}a:{Y=Y.xhr;x.MX();if(x.B){var L=!(x.V?Y.response:Y.responseText)||Y.status>=400;if(v=g.j1g(Y)){Y=g.DP(x.B,x.policy,{});x.B.NL(Y,v);Pgz(x,x.B);break a}L?x.player.L6("capfail",{status:Y.status}):(g.c5("fcb_r",(0,g.K)(),x.player.getVideoData()?.Y||""),v=x.B.g$[0],L=v.mU,x.G!=null&&x.O!==L&&(x.V?x.G(Y.response,(v.segmentStartTime+x.player.Qd())*1E3):x.G(Y.responseText,(v.segmentStartTime+x.player.Qd())*1E3),x.O=L))}x.B=
null;x.L=null}}).wE(Y=>{x.B=null;
x.L=null;x.player.L6("capfail",{rn:k,status:Y.xhr?.status})});
x.B=n;wce(x.U,x.B.g$[0].mU)},jEk=function(x,n){return n!=null&&n in x.L.Z?x.L.Z[n]:null},qOl=function(x,n,Z){var F=[];
for(let k in x.L.Z){if(!x.L.Z.hasOwnProperty(k))continue;let J=x.L.Z[k];if(g.hX(J,Z||null)){let Y=J.info.captionTrack;Y&&Y.languageCode===n&&F.push(J)}}return F.length?F[0]:null},I42=function(x,n){var Z=[];
for(let k in x.L.Z){if(!x.L.Z.hasOwnProperty(k))continue;var F=x.L.Z[k];if(g.hX(F,n||null)){let J=F.info.id,Y=J,v=`.${J}`,L="",S="";if(F=F.info.captionTrack)J=F.languageCode,Y=F.displayName,v=F.vssId,L=F.kind,S=F.id;Z.push(new g.KS({id:k,languageCode:J,languageName:Y,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:L,captionId:S}))}}return Z},g0l=function(x,n,Z,F){var k=n/360*16;
n>=x&&(x=640,F>Z*1.3&&(x=480),k=Z/x*16);return k},$V$=function(x){var n=1+.25*(x.fontSizeIncrement||0);
if(x.offset===0||x.offset===2)n*=.8;return n},Otl=function(x,n){var Z="vertical-rl";
x.Z.GQ===1&&(Z="vertical-lr");g.f1&&(Z=Z==="vertical-lr"?"tb-lr":"tb-rl");g.jd(n,"-o-writing-mode",Z);g.jd(n,"-webkit-writing-mode",Z);g.jd(n,"writing-mode",Z);g.jd(n,"text-orientation","upright");g.Eu(n,"ytp-vertical-caption");x.L.params.Yp===3&&(g.jd(n,"text-orientation",""),g.jd(n,"transform","rotate(180deg)"))},Hto=function(x,n){var Z={},F=n.background?n.background:x.Z.KH.background;
if(n.backgroundOpacity!=null||n.background){var k=n.backgroundOpacity!=null?n.backgroundOpacity:x.Z.KH.backgroundOpacity;F=yM(F);Z.background="rgba("+F[0]+","+F[1]+","+F[2]+","+k+")";x.C6&&(Z["box-decoration-break"]="clone",Z["border-radius"]=`${x.n6*.375}px`)}if(n.fontSizeIncrement!=null||n.offset!=null)Z["font-size"]=`${x.tZ*$V$(n)}px`;F=1;k=n.color||x.Z.KH.color;if(n.color||n.textOpacity!=null)k=yM(k),F=n.textOpacity==null?x.Z.KH.textOpacity:n.textOpacity,k="rgba("+k[0]+","+k[1]+","+k[2]+","+F+
")",Z.color=k,Z.fill=k;var J=n.charEdgeStyle;J===0&&(J=void 0);if(J){k=`rgba(34, 34, 34, ${F})`;let L=`rgba(204, 204, 204, ${F})`;n.aS&&(L=k=n.aS);let S=x.tZ/16/2,T=Math.max(S,1);var Y=Math.max(2*S,1),v=Math.max(3*S,1);let U=Math.max(5*S,1);F=[];switch(J){case 4:for(;v<=U;v+=S)F.push(`${Y}px ${Y}px ${v}px ${k}`);break;case 1:Y=window.devicePixelRatio>=2?.5:1;for(J=T;J<=v;J+=Y)F.push(`${J}px ${J}px ${k}`);break;case 2:F.push(`${T}px ${T}px ${L}`);F.push(`-${T}px -${T}px ${k}`);break;case 3:for(v=0;v<
5;v++)F.push(`0 0 ${Y}px ${k}`)}Z["text-shadow"]=F.join(", ")}k="";switch(n.fontFamily){case 1:k='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:k='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:k='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:k='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:k='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:k=g.OT()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:k='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}k&&(Z["font-family"]=k);k=n.offset;k==null&&(k=x.Z.KH.offset);switch(k){case 0:Z["vertical-align"]="sub";break;case 2:Z["vertical-align"]="super"}n.fontFamily===7&&(Z["font-variant"]="small-caps");n.bold&&(Z["font-weight"]="bold");n.italic&&(Z["font-style"]="italic");n.underline&&
(Z["text-decoration"]="underline");n.FV&&(Z.visibility="hidden");n.LK===1&&x.U&&(Z["text-combine-upright"]="all",Z["text-orientation"]="mixed",k=g.fS||g.Zi,x.L.params.Yp===3?Z.transform=k?"rotate(90deg)":"rotate(180deg)":k&&(Z.transform="rotate(-90deg)"));if(n.textEmphasis===1||n.textEmphasis===2||n.textEmphasis===3||n.textEmphasis===4||n.textEmphasis===5)if(g.fS)Z["font-weight"]="bold";else switch(Z["text-emphasis-style"]="filled circle",Z["text-emphasis-color"]="currentcolor",Z["webkit-text-emphasis"]=
"filled circle",n.textEmphasis){case 4:case 3:Z["text-emphasis-position"]="under left";Z["webkit-text-emphasis-position"]="under left";break;case 5:case 2:Z["text-emphasis-position"]="over right",Z["webkit-text-emphasis-position"]="over right"}return Z},NWl=function(x,n){if(x.X9&&n.length===0)return 0;
x=1;for(let Z=0;Z<n.length;Z++){let F=n[Z];typeof F.text==="string"&&(x+=F.text.split("\n").length-1,F.append||Z===0||x++)}return x},BO=function(x){x=x.split("px");
return x.length>0?(x=Number(x[0]))?x:0:0},K3o=function(x,n,Z){x.oW=x.oW||!!Z;
var F={};Object.assign(F,x.Z.KH);Object.assign(F,Z||n.Z);Object.assign(F,x.Oc.KH);(Z=!x.V)&&bt2(x);var k=x.ue&&x.Pw&&g.De(F,x.Pw)?x.ue:pct(x,F),J=typeof n.text==="string",Y=J?n.text.split("\n"):[n.text];for(let L=0;L<Y.length;L++){var v=L>0||!n.append;let S=Y[L];v&&!Z?(bt2(x),k=pct(x,F)):v&&Z&&(Z=!1);S&&(k.appendChild(J?g.v3(S):S),J||S.tagName!=="RUBY"||S.childElementCount!==4||g.fS||!g.$f(S.children[2],"text-emphasis")||(v=x.U?"padding-right":"padding-top",g.$f(S.children[2],"text-emphasis-position")&&
(v=x.U?"padding-left":"padding-bottom"),g.Z3?g.jd(k,v,"1em"):g.jd(k,v,"0.5em")))}x.Pw=F;x.ue=k;x.N.push(n)},bt2=function(x){if(x.V){var n=x.V;
if(x.C6){var Z=x.Z.textAlign;Z===0?(n=n.firstElementChild)&&g.jd(n,{"border-bottom-left-radius":"0"}):Z===1&&(n=n.lastElementChild)&&g.jd(n,{"border-bottom-right-radius":"0"})}}x.V=g.Yf("SPAN");g.jd(x.V,{display:"block"});g.Eu(x.V,"caption-visual-line");x.B.appendChild(x.V)},pct=function(x,n){var Z=g.Yf("SPAN");
g.jd(Z,{display:"inline-block","white-space":"pre-wrap"});g.jd(Z,Hto(x,n));Z.classList.add("ytp-caption-segment");x.V.appendChild(Z);x.C6&&x.B.children.length>1&&(x=x.Z.textAlign,x===0?Z.previousElementSibling||g.jd(Z,{"border-top-left-radius":"0"}):x===1&&g.jd(Z,{"border-top-right-radius":"0"}));Z.previousElementSibling&&(g.jd(Z.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.jd(Z,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return Z},
cRu=function(x,n,Z){if(x===255&&n===255||!x&&!n)return{JS:x,
Fj:n,result:0};x=Mce[x];n=Mce[n];if(x&128){var F;if(F=!(n&128))F=n,F=Z.lP()&&Z.Fj===F;if(F)return{JS:x,Fj:n,result:1}}else if(n&128&&1<=x&&x<=31)return{JS:x,Fj:n,result:2};return{JS:x,Fj:n,result:3}},Ra2=function(x,n,Z,F){n===255&&Z===255||!n&&!Z?(++x.B===45&&x.reset(),x.U.L.clear(),x.V.L.clear()):(x.B=0,rRi(x.U,n,Z,F))},DVl=function(x,n){x.Z.sort((Z,F)=>{var k=Z.time-F.time;
return k===0?Z.order-F.order:k});
for(let Z of x.Z)x.time=Z.time,Z.type===0?Ra2(x,Z.Mo,Z.fm,n):Z.type===1&&x.L&496&&rRi(x.V,Z.Mo,Z.fm,n);x.Z.length=0},Zjl=function(x,n){switch(x){case 0:return tci[(n&127)-32];
case 1:return AR$[n&15];case 2:return xR2[n&31];case 3:return nik[n&31]}return 0},ab=function(x,n){if(x.style.type===3){var Z=0,F=0,k=x.V.time+0,J="",Y="",v=k;
for(var L=1;L<=15;++L){var S=!1;for(var T=F?F:1;T<=32;++T){var U=x.B[L][T];if(U.Z!==0){Z===0&&(Z=L,F=T);S=String.fromCharCode(U.Z);var h=U.timestamp;h<k&&(k=h);U.timestamp=v;Y&&(J+=Y,Y="");J+=S;S=!0}if((U.Z===0||T===32)&&S){Y="\n";break}else if(F&&!S)break}if(Z&&!S)break}J&&n.U(Z,F,k,v,J)}else for(F=Z=0,J=k=x.V.time+0,Y=1;Y<=15;++Y)for(v="",L=1;L<=32;++L)if(T=x.B[Y][L],U=T.Z,U!==0&&(Z===0&&(Z=Y,F=L),S=String.fromCharCode(U),h=T.timestamp,h<=k&&(k=h),v+=S,T.reset()),L===32||U===0)v&&n.U(Z,F,k,J,v),
k=J,v="",F=Z=0},dD=function(x){return x.B[x.row][x.L]},QM=function(x,n,Z){n>=2&&x.L>1&&(--x.L,dD(x).Z=0);
var F=dD(x);F.timestamp=x.V.time+0;F.Z=Zjl(n,Z);x.L<32&&x.L++},Fpl=function(x,n,Z,F){for(let Y=0;Y<F;Y++)for(let v=0;v<=32;v++){var k=x.B[n+Y][v],J=x.B[Z+Y][v];
k.Z=J.Z;k.timestamp=J.timestamp}},Xo=function(x,n,Z){for(let F=0;F<Z;F++)for(let k=0;k<=32;k++)x.B[n+F][k].reset()},En=function(x){x.row=x.Z>0?x.Z:1;
x.L=1;Xo(x,0,15)},ije=function(x){x.style.set(1);
x.Z=x.U;x.Z.Z=0;x.Z.style=x.style;x.B.mode=1<<x.Z.U},zD=function(x,n,Z){var F=x.L,k=!1;
switch(x.style.get()){case 4:case 1:case 2:x.style.get()===4&&F.Z>0||(ab(F,Z),En(x.L),En(x.U),F.row=15,F.Z=n,k=!0)}x.style.set(3);x.Z=F;x.Z.style=x.style;x.B.mode=1<<F.U;k?F.L=1:F.Z!==n&&(F.Z>n?(ab(F,Z),Xo(F,F.row-F.Z,n)):F.row<n&&(n=F.Z),F.Z=n)},knt=function(x){x.style.set(4);
x.Z=x.text;x.Z.style=x.style;x.B.mode=1<<x.Z.U},rRi=function(x,n,Z,F){x.L.update();
n=cRu(n,Z,x.L);switch(n.result){case 0:return;case 1:case 2:return}var k=n.JS;n=n.Fj;if(32<=k||!k)x.Z.mode&x.Z.L&&(Z=k,Z&128&&(Z=127),n&128&&(n=127),x=x.U.Z,Z&96&&QM(x,0,Z),n&96&&QM(x,0,n),Z!==0&&n!==0&&x.style.type===3&&ab(x,F));else if(k&16)a:if(!x.L.matches(k,n)&&(Z=x.L,Z.JS=k,Z.Fj=n,Z.state=2,Z=k&8?x.O:x.B,x.U=Z,x.Z.mode=1<<(x.V<<2)+(Z.V<<1)+(Z.style.type===4?1:0),(x.Z.mode|1<<(x.V<<2)+(Z.V<<1)+(Z.style.type!==4?1:0))&x.Z.L))if(n&64){F=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(k&7)<<1|n>>5&1];
x=n&16?((n&14)>>1)*4:0;n=Z.Z;switch(Z.style.get()){case 4:F=n.row;break;case 3:if(F!==n.row){if(F<n.Z&&(F=n.Z,F===n.row))break;var J=1+n.row-n.Z;let Y=1+F-n.Z;Fpl(n,Y,J,n.Z);Z=J;k=n.Z;Y<J?(J=Y+k-J,J>0&&(Z+=J,k-=J)):(J=J+k-Y,J>0&&(k-=J));Xo(n,Z,k)}}n.row=F;n.L=x+1}else switch(k&7){case 1:switch(n&112){case 32:QM(Z.Z,0,32);break a;case 48:n===57?(F=Z.Z,dD(F).Z=0,F.L<32&&F.L++):QM(Z.Z,1,n&15)}break;case 2:n&32&&QM(Z.Z,2,n&31);break;case 3:n&32&&QM(Z.Z,3,n&31);break;case 4:case 5:if(32<=n&&n<=47)switch(n){case 32:ije(Z);
break;case 33:F=Z.Z;F.L>1&&(--F.L,dD(F).Z=0);break;case 36:F=Z.Z;x=dD(F);for(n=0;n<=15;n++)for(Z=0;Z<=32;Z++)if(F.B[n][Z]===x){for(;Z<=32;Z++)F.B[n][Z].reset();break}break;case 37:zD(Z,2,F);break;case 38:zD(Z,3,F);break;case 39:zD(Z,4,F);break;case 40:QM(Z.Z,0,32);break;case 41:F=Z;F.style.set(2);F.Z=F.L;F.Z.Z=0;F.Z.style=F.style;F.B.mode=1<<F.Z.U;break;case 42:F=Z;x=F.text;x.Z=15;x.style.set(4);En(x);knt(F);break;case 43:knt(Z);break;case 44:x=Z;n=x.L;switch(x.style.get()){case 1:case 2:case 3:ab(n,
F)}Xo(n,0,15);break;case 45:b:{n=Z;x=n.Z;switch(n.style.get()){default:case 2:case 1:break b;case 4:if(x.row<15){++x.row;x.L=1;break b}break;case 3:}x.Z<2&&(x.Z=2,x.row<x.Z&&(x.row=x.Z));n=x.row-x.Z+1;ab(x,F);Fpl(x,n,n+1,x.Z-1);Xo(x,x.row,1)}break;case 46:Xo(Z.U,0,15);break;case 47:x=Z,ab(x.L,F),x.U.updateTime(x.B.time+0),F=x.U,x.U=x.L,x.L=F,ije(x)}break;case 7:switch(n){case 33:case 34:case 35:F=Z.Z,(F.L+=n&3)>32&&(F.L=32)}}},Yyl=function(x,n,Z,F,k,J,Y){var v=J[0],L=Y[v.getAttribute("p")];
if(L.BC===1){var S=J[1],T=J[2];J=J[3];v.getAttribute("t");S.getAttribute("t");T.getAttribute("t");J.getAttribute("t");v.getAttribute("p");S.getAttribute("p");J.getAttribute("p");Y=Y[T.getAttribute("p")];v=JDo(v.textContent,S.textContent,T.textContent,J.textContent,Y);return new WO(x,n,k,Z,v,F,L)}switch(L.BC){case 9:case 10:L.textEmphasis=1;break;case 11:L.textEmphasis=2;break;case 12:L.textEmphasis=3;break;case 13:L.textEmphasis=4;break;case 14:L.textEmphasis=5}return new WO(x,n,k,Z,v.textContent||
"",F,L)},JDo=function(x,n,Z,F,k){var J=g.OT(),Y=J?g.Yf("DIV"):g.Yf("RUBY"),v=g.Yf("SPAN");
v.textContent=x;Y.appendChild(v);x=J?g.Yf("DIV"):g.Yf("RP");x.textContent=n;Y.appendChild(x);n=J?g.Yf("DIV"):g.Yf("RT");n.textContent=Z;Y.appendChild(n);Z=k.BC;if(Z===10||Z===11||Z===12||Z===13||Z===14)if(g.jd(n,"text-emphasis-style","filled circle"),g.jd(n,"text-emphasis-color","currentcolor"),g.jd(n,"webkit-text-emphasis","filled circle"),k.BC===11||k.BC===13)g.jd(n,"webkit-text-emphasis-position","under left"),g.jd(n,"text-emphasis-position","under left");Z=!0;if(k.BC===4||k.BC===7||k.BC===12||
k.BC===14)g.jd(Y,"ruby-position","over"),g.jd(Y,"-webkit-ruby-position","before");else if(k.BC===5||k.BC===6||k.BC===11||k.BC===13)g.jd(Y,"ruby-position","under"),g.jd(Y,"-webkit-ruby-position","after"),Z=!1;k=J?g.Yf("DIV"):g.Yf("RP");k.textContent=F;Y.appendChild(k);J&&(F=Z,g.jd(Y,{display:"inline-block",position:"relative"}),J=Y.firstElementChild.nextElementSibling,g.jd(J,"display","none"),J=J.nextElementSibling,g.jd(J,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.jd(Y.lastElementChild,"display","none"),F?(g.jd(Y,"padding-top","0.6em"),g.jd(J,"top","0")):(g.jd(Y,"padding-bottom","0.6em"),g.jd(J,"bottom","0")));return Y},vit=function(x){var n="_"+ob++;
return new m4(0,0x8000000000000,0,n,x)},GD=function(x,n){x=x.getAttribute(n);
if(x!=null)return Number(x)},lc=function(x,n){x=x.getAttribute(n);
if(x!=null)return x==="1"},C2=function(x,n){x=GD(x,n);
return x!==void 0?x:null},wD=function(x,n){x=x.getAttribute(n);
if(x!=null)return f2.test(x),x},LpJ=function(x,n){var Z={},F=n.getAttribute("ws");
Object.assign(Z,F?x.Y[F]:x.U);x=C2(n,"mh");x!=null&&(Z.Zk=x);x=C2(n,"ju");x!=null&&(Z.textAlign=x);x=C2(n,"pd");x!=null&&(Z.Yp=x);x=C2(n,"sd");x!=null&&(Z.GQ=x);x=wD(n,"wfc");x!=null&&(Z.windowColor=x);n=GD(n,"wfo");n!==void 0&&(Z.windowOpacity=n/255);return Z},Syt=function(x,n){var Z={},F=n.getAttribute("wp");
F&&Object.assign(Z,x.G[F]);x=C2(n,"ap");x!=null&&(Z.pC=x);x=GD(n,"cc");x!=null&&(Z.tI=x);x=GD(n,"ah");x!=null&&(Z.hs=x);x=GD(n,"rc");x!=null&&(Z.la=x);n=GD(n,"av");n!=null&&(Z.y9=n);return Z},THe=function(x,n,Z,F){var k={};
Object.assign(k,Syt(x,n));Object.assign(k,LpJ(x,n));F?g.De(k,x.U)?(F=x.V,k=x.U):F="_"+ob++:F=n.getAttribute("id")||"_"+ob++;x=GD(n,"t")+Z;n=GD(n,"d")||0x8000000000000;if(k.Yp===2||k.Yp===3)Z=k.la,k.la=k.tI,k.tI=Z;return new m4(x,n,0,F,k)},VM=function(x){x=g.la(Math.round(x),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-x.length)+x},UR6=function(x,n,Z,F,k){F===0&&(F=0x8000000000000);
var J={};n.wpWinPosId&&Object.assign(J,x.U.get(n.wpWinPosId));n.wsWinStyleId&&Object.assign(J,x.V.get(n.wsWinStyleId));x=n.rcRowCount;x!==void 0&&(J.la=x);n=n.ccColCount;n!==void 0&&(J.tI=n);if(J.Yp===2||J.Yp===3)n=J.la,J.la=J.tI,J.tI=n;return new m4(Z,F,0,k,J)},PO=function(x){var n=x.byteOffset;
x.byteOffset+=1;return x.Z.getUint8(n)},jF=function(x){var n=x.byteOffset;
x.byteOffset+=4;return x.Z.getUint32(n)},eSJ=function(x){if(typeof x==="string")return!1;
x=new us2(x,0);return hSe(x)},hSe=function(x){if(!(x.byteOffset<x.Z.byteLength)||jF(x)!==1380139777)return!1;
x.version=PO(x);if(x.version>1)return!1;PO(x);PO(x);PO(x);return!0},yDk=function(x,n){if(!n)return"";
x.U&&x.L.params.GQ!==1&&(n*=-1);return`translate${x.U?"X":"Y"}(${n}px)`},spo=function(x){x.VF=Array.from(x.element.getElementsByClassName("caption-visual-line"));
for(var n=x.L.params.la,Z=0,F=0,k=x.VF.length-1;Z<n&&k>-1;){var J=x.VF[k];F+=x.U?J.offsetWidth:J.offsetHeight;Z++;k--}x.K=F;n=Math;Z=n.max;isNaN(x.w$)&&((F=x.Z.tI)?(k=g.Yf("SPAN"),g.hM(k,"\u2013".repeat(F)),g.jd(k,Hto(x,x.Z.KH)),x.B.appendChild(k),x.w$=k.offsetWidth,x.B.removeChild(k)):x.w$=0);F=x.B;x.Hw=Z.call(n,x.w$,x.WD,(x.U?F.offsetHeight:F.offsetWidth)+1)},BHl=function(x,n){spo(x);
var Z=x.VF.reduce((F,k)=>(x.U?k.offsetWidth:k.offsetHeight)+F,0);
Z=x.K-Z;if(Z!==x.ie){let F=Z>0&&x.ie===0,k=Z<x.ie;n||isNaN(Z)||F||!k||(g.Eu(x.element,"ytp-rollup-mode"),x.X(x.element,"transitionend",x.RW));g.jd(x.B,"transform",yDk(x,Z));x.ie=Z}spo(x)},dRJ=function(x,n,Z,F){var {formatId:k,
mU:J,startTimeMs:Y,durationMs:v}=x.PV(n),L={formatId:k,startTimeMs:Y,durationMs:v,kV:J,QG:J},S=aS$(x.bb,L.startTimeMs),T=S>=0?x.bb[S]:null,U=T?T.startTimeMs+T.durationMs:0,h=L.startTimeMs+L.durationMs;!T||L.startTimeMs-U>x.U?x.bb.splice(S+1,0,L):(T.durationMs=Math.max(U,h)-T.startTimeMs,T.QG=Math.max(T.QG,L.QG));F(x.bb);F=g.i8(n);x=x.V;F=F.buffer.slice(F.byteOffset,F.byteLength+F.byteOffset);n=n.info.U;x.Hw?x.G==null?g.F0(x.logger,350058965,"Null loaded track meta data at captions data received"):
Z.j7(F,x.G,n*1E3):g.F0(x.logger,350058965,"Null Representation at captions data received")},Ei6=function(x,n){x.L=(Z,F)=>{if(x.S.J().experiments.yF("html5_sabr_live_support_subfragmented_captions"))(x.Z?x.Z=x.Z.V(Z):(x.Z=Z,Qpo(x.Z)),x.Z)?Z.info.uP&&(XGo(x.Z),dRJ(x,x.Z,n,F),x.Z=null):g.F0(x.logger,350058965,"Empty slice");
else if(Z.info.uP){var k=Z;if(x.Wx.length>0){for(k=x.Wx.shift();x.Wx.length>0;)k=k?.V(x.Wx.shift());k=k?.V(Z)}k?(Qpo(k),XGo(k),dRJ(x,k,n,F)):g.F0(x.logger,350058965,"Empty slice")}else x.Wx.push(Z)};
x.S.addEventListener("sabrCaptionsDataLoaded",x.L)},aS$=function(x,n){x=g.sk(x,{startTimeMs:n},(Z,F)=>Z.startTimeMs-F.startTimeMs);
return x>=0?x:-x-2},Qpo=function(x){try{var n=g.Yv(x)*1E3}catch(Z){n=x.info.segmentStartTime*1E3}n<0&&(n=x.info.segmentStartTime*1E3);
x.info.segmentStartTime=n/1E3;x.info.U=n/1E3},XGo=function(x){try{var n=g.mJc(x)*1E3}catch(Z){n=x.info.B*1E3}n<0&&(n=x.info.B*1E3);
x.info.B=n/1E3;x.info.O=n/1E3},zSs=function(x,n){if(!g.mY1(x)||x.Z!=null&&g.uF(n,x.Z)&&x.Z.Z.rawcc!=null)return!1;
n=!!x.Z&&x.Z.isManifestless&&Object.values(x.Z.Z).some(Z=>g.hX(Z,"386"));
x=!!x.Z&&!x.Z.isManifestless&&g.Goh(x.Z);return n||x},Wpz=function(x,n,Z){var F=[];
for(let k in x.L.Z){if(!x.L.Z.hasOwnProperty(k))continue;let J=x.L.Z[k];if(g.hX(J,Z||null)){let Y=J.info.captionTrack;Y&&Y.languageCode===n&&F.push(J)}}return F.length?F[0]:null},oiz=function(x,n){var Z=[];
for(let k in x.L.Z){if(!x.L.Z.hasOwnProperty(k))continue;var F=x.L.Z[k];if(g.hX(F,n||null)){let J=F.info.id,Y=J,v=`.${J}`,L="",S="";if(F=F.info.captionTrack)J=F.languageCode,Y=F.displayName,v=F.vssId,L=F.kind,S=F.id;Z.push(new g.KS({id:k,languageCode:J,languageName:Y,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:L,captionId:S}))}}return Z},Gnk=function(x){var n=mRt.length;
if(x.byteLength<n)return!1;x=new Uint8Array(x,0,n);for(let Z=0;Z<n;Z++)if(mRt[Z]!==x[Z])return!1;return!0},qM=function(x){x=x.split(":");
var n=0;for(let Z of x)n=n*60+Number(Z);return n*1E3},lSi=function(x,n,Z,F){F=Object.assign({Zk:0},F);
return new m4(x,n,Z,"_"+ob++,F)},Coi=function(x,n,Z,F,k,J,Y,v,L){switch(Y.tagName){case "b":v.bold=!0;
break;case "i":v.italic=!0;break;case "u":v.underline=!0}for(let T=0;T<Y.childNodes.length;T++){var S=Y.childNodes[T];if(S.nodeType===3)S=new WO(n,Z,F,k.id,S.nodeValue,J||T>0,g.c6(v)?void 0:v),L.push(S),k.Z.push(S);else{let U={};Object.assign(U,v);Coi(x,n,Z,F,k,!0,S,U,L)}}},wGe=function(x,n,Z){if(typeof n==="string"||eSJ(n))return[{trackData:n,
vl:Z}];if(typeof n==="string"&&n.substring(0,6)==="WEBVTT"||typeof n!=="string"&&Gnk(n))return[{trackData:n,vl:Z}];var F=new DataView(n);if(F.byteLength<=8||F.getUint32(4)!==1718909296)return[];var k=g.I9R(F);if(x.FY&&k){var J=g.G2Q(k),Y=g.l9K(k);k=k.segmentNumber;J&&k&&x.FY.hm(k,J,Y)}x=g.L_(F,1835295092);if(!x||!x.length||!x[0].size)return[];J=[];for(Y=0;Y<x.length;Y++)k=x[Y],k=new Uint8Array(n,k.dataOffset,k.size-(k.dataOffset-k.offset)),k=g.k4(k),J.push({trackData:k,vl:Z+Y*1E3});fSe(F,J,Z);return J=
J.filter(v=>!!v.trackData)},Pol=function(x,n,Z){x.Z||(x.Z=new V3J);
x=x.Z.B(n,Z);Math.random()<.01&&g.AQ(Error("Deprecated subtitles format in web player: WebVTT"));return x},fSe=function(x,n,Z){var F=g.i$(x,0,1836476516),k=9E4;
F&&(k=g.kP(F)||9E4);F=0;var J=g.L_(x,1836019558);for(let v=0;v<J.length;v++){var Y=J[v];v<n.length&&(Y=g.i$(x,Y.dataOffset,1953653094))&&(Y=g.i$(x,Y.dataOffset,1952867444))&&(Y=g.v1(Y)/k*1E3,v===0&&(F=Y),n[v].vl=Y-F+Z||Z*v*1E3)}},jpi=function(x){var n={};
if(x=g.Gk(x))n.lang=x,g.TL1.test(x)&&(n.Yp=1);return n},Ib=function(x){return x.B==="HLS"&&x.LT?!0:x.ue&&x.LT&&x.B!=="LIVE"&&x.B!=="SABR_LIVE"},qyJ=function(x){return!x.U&&x.ue&&x.X9&&(x.B==="LIVE"||x.B==="SABR_LIVE")},gD=function(x,n,Z=!1){var F=x.hZ.C("enable_player_captions_new_style_defaults")?ISs:gik,k=F.KH;
x.V={};Object.assign(x.V,F);x.V.KH={};Object.assign(x.V.KH,k);x.O={KH:{}};var J=n.backgroundOverride?x.O:x.V,Y=n.background||k.background;f2.test(Y);J.KH.background=Y;J=n.colorOverride?x.O:x.V;Y=n.color||k.color;f2.test(Y);J.KH.color=Y;J=n.windowColorOverride?x.O:x.V;Y=n.windowColor||F.windowColor;f2.test(Y);J.windowColor=Y;J=n.backgroundOpacityOverride?x.O:x.V;Y=n.backgroundOpacity;Y==null&&(Y=k.backgroundOpacity);J.KH.backgroundOpacity=Y;J=n.fontSizeIncrementOverride?x.O:x.V;Y=n.fontSizeIncrement;
Y==null&&(Y=k.fontSizeIncrement);J.KH.fontSizeIncrement=Y;Y=n.fontStyleOverride?x.O:x.V;J=n.fontStyle;J==null&&(J=k.bold&&k.italic?3:k.bold?1:k.italic?2:0);Y=Y.KH;switch(J){case 1:Y.bold=!0;delete Y.italic;break;case 2:delete Y.bold;Y.italic=!0;break;case 3:Y.bold=!0;Y.italic=!0;break;default:delete Y.bold,delete Y.italic}J=n.textOpacityOverride?x.O:x.V;Y=n.textOpacity;Y==null&&(Y=k.textOpacity);J.KH.textOpacity=Y;J=n.windowOpacityOverride?x.O:x.V;Y=n.windowOpacity;Y==null&&(Y=F.windowOpacity);J.windowOpacity=
Y;F=n.charEdgeStyleOverride?x.O:x.V;J=n.charEdgeStyle;J==null&&(J=k.charEdgeStyle);F.KH.charEdgeStyle=J;F=n.fontFamilyOverride?x.O:x.V;J=n.fontFamily;J==null&&(J=k.fontFamily);F.KH.fontFamily=J;x.loaded&&x.jq();Z&&g.zO("yt-player-caption-display-settings",n,2592E3)},$B=function(x,n,Z){n&&!x.Ze?(n=vit({Yp:0,
lang:"en"}),x.Ze=[n,new WO(n.start,n.end-n.start,0,n.id,Z??"Captions look like this")],x.player.Zr(x.Ze)):!n&&x.Ze&&($Ri(x,x.Ze),x.Ze=null)},Hji=function(x){if(x.hZ.C("enable_player_captions_persistence_state_machine")){var n=g.WA("yt-player-caption-persistence");
if(n==null){let Z=g.fK().eq(65);if(Z===!0)n=!1;else{let F=g.WU(x.hZ)?On(x):Oji(x);F!=null?n=!!F:Z===!1&&(n=!0)}n!==void 0&&HO(x,n)}return n}},On=function(x){if(!x.S.isInline())return g.WA("yt-player-sticky-caption")},Oji=function(x){if(!x.storage)return null;
try{var n=x.storage.get("module-enabled")}catch(Z){x.storage.remove("module-enabled")}return n},NM=function(x){if(x.hZ.C("enable_player_captions_persistence_state_machine"))return Hji(x);
var n=void 0,Z=g.fK().eq(65);if(g.WU(x.hZ)&&Z!=null){if(On(x)!=null)return!1;n=!Z}return n},NHe=function(x){if(x.hZ.aP===1||x.videoData.mD===1||g.i6(x.videoData,"yt:cc")==="alwayson")return!0;
if(x.videoData.captionTracks.length)var n=x.getAudioTrack().L;if(x.hZ.C("enable_player_captions_persistence_state_machine")){var Z=Hji(x);if(Z!==void 0)return!!Z}else if(x.hZ.aP===2&&(g.WU(x.hZ)?Z=On(x):Z=Oji(x),Z!=null))return!!Z;Z=eF(x.player.getAudioTrack(),g.WU(x.hZ));var F=g.i6(x.videoData,"yt:cc");if(NM(x)===void 0){if(Z==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return F?F==="on":!0;if(Z==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return F==="on"}else return F==="on";return n==="ON"||g.i6(x.videoData,
"yt:cc")==="on"},bc=function(x,n=!1){if(x.L&&!n||!x.videoData.captionTracks.length)return!1;
x=x.getAudioTrack();return!!x.Z||x.L==="FORCED_ON"},bjt=function(x,n){if(x.L){var Z=x.S.tJ().q6().textTracks,F=null;
x.B==="HLS"?F=x.L.getId():F=x.L.toString();for(let J=0;J<Z.length;J++){var k=Z[J];k.id===F&&(n?k.mode!=="showing"&&(k.mode="showing",k=x.L,x.WL(k,!!k,p2(x)?"g":x.N?"m":"s")):k.mode==="showing"&&(k.mode="disabled"))}}},p2=function(x){var n=K2(x);
return!!n&&x.L===n},pGe=function(x,n){if(x.B==="HLS")return!1;
g.U_(x.videoData)&&(n=!0);n||(n=x.B==="TTS"?!1:x.B==="INNERTUBE"?!1:!0);return n||x.hZ.C("web_watch_disable_account_level_captions_settings")&&g.WU(x.hZ)?!0:!!g.fK().eq(66)},K2=function(x){return x.Y&&x.Y.Z},MM=function(x,n){if(!x.Z)return null;
if(x.Y&&x.Y.U)return x.Y.U;n=pGe(x,n);n=g.KW(x.Z.Z,n);var Z=null;if(o0i(x.hZ)){var F=x.S.isInline()?void 0:g.WA("yt-player-caption-sticky-language");var k=[F,x.videoData.captionsLanguagePreference,x.hZ.captionsLanguagePreference,g.i6(x.videoData,"yt:cc_default_lang")];let v=!1;for(let L=0;L<k.length;L++){let S=k[L];if(S){v=!0;for(var J=0;J<n.length;J++)if(g.Gk(n[J])===S)return n[J];for(J=0;J<n.length;J++)if(g.Gk(n[J]).split("-")[0]===S.split("-")[0])return n[J]}}if(v&&x.Z&&(k=x.Z.Y,k.length))for(var Y of k)if(Y.languageCode===
F){Z=Y;break}}else for(Y=[x.videoData.captionsLanguagePreference,x.hZ.captionsLanguagePreference,g.i6(x.videoData,"yt:cc_default_lang")],F=0;F<Y.length;F++)for(k=0;k<n.length;k++)if(g.Gk(n[k])===Y[F])return n[k];Y=null;x.Y&&x.Y.B&&(Y=x.Y.B);Y||(Y=n.find(v=>v.isDefault)||null);
Y||(Y=n[0]||K2(x));Y&&Z&&g.Gk(Y).split("-")[0]!==Z.languageCode.split("-")[0]&&(Y=W36(Y,Z));return Y},Dq=function(x,n,Z){x.loaded&&x.unload();
Z!=null&&(x.N=Z,x.N&&(x.hZ.C("enable_player_captions_persistence_state_machine")?HO(x,!!n):g.WU(x.hZ)?cO(x,!!n):rD(x,!!n)));n!==null||bc(x,!0)||x.WL(n,!!n,x.N?"m":"s");x.L=n;bc(x)&&(x.L=K2(x));Rb(x,x.L??void 0);x.load()},HO=function(x,n){x.hZ.C("enable_player_captions_persistence_state_machine")&&g.zO("yt-player-caption-persistence",n,3122064E3)},cO=function(x,n){x.S.isInline()||g.zO("yt-player-sticky-caption",n,2592E3)},rD=function(x,n){if(x.storage)try{x.storage.set("module-enabled",n)}catch(Z){}},
Rb=function(x,n){x.hZ.C("html5_modify_caption_vss_logging")&&(x.videoData.Ji=n)},M3z=function(x,n){var Z=x.cw[n.id];
Z&&Z.L!==n&&(Z.dispose(),delete x.cw[n.id],Z=null);Z||(Z=Kpi(x,n))&&(x.cw[n.id]=Z)},cDk=function(x,n){var Z=n.windowId;
x.C6[Z]||(x.C6[Z]=[]);x.C6[Z].push(n)},Kpi=function(x,n){var Z=rD6(x);
if(!Z)return null;var F=x.L?g.Gk(x.L):null;F&&g.TL1.test(F)&&(n.params.Yp=1);var k=x.RW.getPlayerSize();F=k.height*x.Hw.height;k=k.width*x.Hw.width;x.hZ.playerStyle!=="google-live"||x.V.isDefault||Object.assign(n.params,x.V);switch(n.params.Zk!=null?n.params.Zk:n.Z.length>1?1:0){case 1:return new RSe(n,x.V,x.O,Z.width,Z.height,k,F,x.hZ.experiments,x.n6.bind(x),x.S);case 2:return new DR6(n,x.V,x.O,Z.width,Z.height,k,F,x.hZ.experiments,x.n6.bind(x),x.S);default:return new tl(n,x.V,x.O,Z.width,Z.height,
k,F,x.hZ.experiments,x.n6.bind(x),x.S)}},rD6=function(x){var n=x.RW.getVideoContentRect(!0).height,Z=x.RW.getVideoContentRect(!0).width;
if(!n||!Z)return null;n*=x.Hw.height;Z*=x.Hw.width;return{width:Z,height:n}},$Ri=function(x,n){x.player.St(n);
for(let Z of n)g.Ze(x.w$,Z);hl(x.oW)},t3e=function(x,n){if(!x.Z)return{};
if(n){g.c6(n)||x.gZ(n.vss_id,"m");if(x.U&&x.B!=="HLS"||!g.Xr(n))return;if(g.c6(n)){Dq(x,null,!0);return}let F;var Z=g.KW(x.Z.Z,!0);for(let k=0;k<Z.length;k++){let J=Z[k];J.languageCode!==n.languageCode||F&&(J.languageName!==n.languageName||(J.captionId||"")!==(n.captionId||"")||g.oh(J)!==n.displayName)||(F=n.translationLanguage?W36(J,n.translationLanguage):J)}x.KS(n.position);!F||F===x.L&&x.loaded||(n=g.Qp(),Z=g.Gk(F),n.length&&Z===n[n.length-1]||(n.push(Z),g.zO("yt-player-caption-language-preferences",
n)),o0i(x.hZ)&&!x.S.isInline()&&g.zO("yt-player-caption-sticky-language",Z,2592E3),Dq(x,F,!0))}else return x.loaded&&x.L&&!p2(x)?g.mE(x.L):{};return""};
g.nm.prototype.hm=g.iI(68,function(x,n,Z){this.L.set(x,{Zu:n,cP:Z})});
g.Zb.prototype.hm=g.iI(67,function(x,n,Z){this.Hw.hm(x,n,Z)});
g.HH.prototype.K=g.iI(66,function(){return!1});
g.HH.prototype.U=g.iI(65,function(){});
g.Nx.prototype.U=g.iI(64,function(x,n,Z){this.MX();n=this.O(x,n);var F=this.le.J().C("html5_report_captions_ctmp_qoe"),k=(0,g.K)();this.B();zai(this,n,{format:"RAW",onSuccess:J=>{this.L=null;if(F){var Y=(J.responseText.length/1024).toFixed();let v=(0,g.K)();this.videoData.L6("capresp",{ms:v-k,kb:Y})}Y=J.getResponseHeader&&J.getResponseHeader("Content-Length")?Number(J.getResponseHeader("Content-Length")):0;Z.j7(J.responseText,x,void 0,void 0,Y)},
onError:F?J=>{this.videoData.L6("capfail",{status:J?.status??0})}:void 0,
withCredentials:!0})});
g.bs.prototype.U=g.iI(63,function(x,n,Z){this.MX();n=this.O(x,n);this.B();this.L=g.sT(n,{format:"RAW",onSuccess:F=>{this.L=null;var k=F.getResponseHeader&&F.getResponseHeader("Content-Length")?Number(F.getResponseHeader("Content-Length")):0;Z.j7(F.responseText,x,void 0,void 0,k)},
withCredentials:!0})});
g.m6.prototype.N=g.iI(62,function(){this.mediaElement.N()});
g.EJ.prototype.N=g.iI(61,function(){var x=g.r5(document,"track",void 0,this.Z);for(let n=0;n<x.length;n++)g.U3(x[n])});
g.m6.prototype.oW=g.iI(60,function(){return this.mediaElement.oW()});
g.EJ.prototype.oW=g.iI(59,function(){return!(!this.Z.textTracks||!this.Z.textTracks.addEventListener)});
g.m6.prototype.w$=g.iI(58,function(){return this.mediaElement.w$()});
g.EJ.prototype.w$=g.iI(57,function(){return!!this.Z.textTracks});
g.m6.prototype.Ze=g.iI(56,function(x){this.mediaElement.Ze(x)});
g.EJ.prototype.Ze=g.iI(55,function(x){for(let n=0;n<x.length;n++)this.Z.appendChild(x[n])});
g.BH.prototype.gZ=g.iI(42,function(x,n){this.app.JZ().gZ(x,n)});
g.M0.prototype.gZ=g.iI(41,function(x,n){this.ER.gZ(x,n)});
g.VN.prototype.gZ=g.iI(40,function(x,n){x=[x,n];g.uu(this,g.y8(this.provider),"cfi",x)});
g.jK.prototype.gZ=g.iI(39,function(x,n){this.qoe&&this.qoe.gZ(x,n)});
g.xY.prototype.gZ=g.iI(38,function(x,n){this.T1.gZ(x,n)});
g.DN.prototype.gZ=g.iI(37,function(){});
g.BH.prototype.WL=g.iI(36,function(x,n,Z){this.app.JZ().WL(x,n,Z)});
g.M0.prototype.WL=g.iI(35,function(x,n,Z){this.ER.WL(x,n,Z)});
g.VN.prototype.WL=g.iI(34,function(x,n,Z){if(this.ue!==x||this.Zc!==n)n=n==="rawcc"?"":n,Z=[x,n,this.ue,Z],g.uu(this,g.y8(this.provider),"cfs",Z),this.ue=x,this.Zc=n});
g.jK.prototype.WL=g.iI(33,function(x,n,Z){this.qoe&&this.qoe.WL(x,n,Z)});
g.xY.prototype.WL=g.iI(32,function(x,n,Z){this.T1.WL(x,n,Z)});
g.DN.prototype.WL=g.iI(31,function(){});
g.Ya.prototype.lN=g.iI(10,function(x){return(x=this.B(x))?x.Z:0});
g.Lf.prototype.lN=g.iI(9,function(){return 0});
g.KS.prototype.L=g.iI(8,function(){return this.vssId});
var Cgk=/#(.)(.)(.)/,l4J=/^#(?:[0-9a-f]{3}){1,2}$/i,ADe={en:"English"},x2k=class extends g.HH{constructor(x){super(x);this.L=new Set}V(x){var n=this.le.tJ();if(n&&n.q6()){n=n.q6().textTracks;for(let Z of n)Z.kind==="subtitles"&&!this.L.has(Z.language)&&Z.language&&(g.UU(this.Z,new g.KS({languageCode:Z.language,languageName:Z.language,kind:Z.kind,id:Z.id,displayName:ADe[Z.label]||Z.label,vss_id:`.${Z.language}`})),this.L.add(Z.language))}g.KW(this.Z).length>0&&x.jb()}},nwt=class{constructor(){this.segments=
[]}contains(x){x=g.sk(this.segments,x);return x>=0||x<0&&(-x-1)%2===1}length(){return this.segments.length/2}},Z$i=class extends g.sO{constructor(x,n,Z,F,k,J){super();this.policy=x;this.player=n;this.p6=Z;this.G=F;this.V=k;this.K=J;this.U=new nwt;this.O=-1;this.L=this.B=this.Z=null;this.Hw=0;this.N=new g.eP(this.Ze,1E3,this);this.events=new g.EE(this);g.G(this,this.N);g.G(this,this.events);this.events.X(n,"SEEK_COMPLETE",this.Y);this.Y();this.Ze()}Bw(){super.Bw();this.L&&this.L.cancel()}Y(){this.seekTo(this.player.getCurrentTime())}seekTo(x){x-=
this.player.Qd();var n=this.Z;this.Z=g.$R(this.p6.O(x).g$);n!==this.Z&&this.K&&this.K()}reset(){this.U=new nwt;this.O=-1;this.L&&(this.L.cancel(),this.L=null)}Ze(){this.MX();var x;if(x=this.Z!=null)x=this.Z,x=x.p6.U(x);if(x&&!this.L&&!(this.Z&&this.Z.segmentStartTime-this.player.getCurrentTime()>30)){x=this.Z;x=x.p6.oW(x);let k=x.g$[0];if(this.player.getVideoData()?.enableServerStitchedDai){var n=this.player.PY();if(n){var Z=k.p6.info.id;let J=k.mU;var F=x.g$[0].U;if(this.policy.w$){if(n=g.n6r(n,
F,J,Z,3))x.U=n}else if(Z=n.sI(F,J,Z,3))if(F=2,n.gN.has(J)?F=0:g.tb(n,J)&&(F=1),n=F,n===0)Z&&(x.Z=new g.jo(Z));else if(n===2){this.N.start();Vce(this)&&this.seekTo(this.player.getCurrentTime());return}}}k.p6.index.pG(k.mU)?(this.U.contains(x.g$[0].mU)||Pgz(this,x),this.Z=g.$R(x.g$)):Vce(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()}},FTk=class extends g.HH{constructor(x,n){super(n);this.L=x;this.S=n;this.G=null;this.Ze=!1;this.logger=new g.Za("caps");this.Hw=g.uF(this.S,this.L)}U(x,
n,Z){this.B();n=jEk(this,x.getId());n||(n=x.languageCode,n=this.L.isManifestless?qOl(this,n,"386"):qOl(this,n));if(n){var F=(n.index.lN(n.index.Uy())-n.index.getStartTime(n.index.Uy()))*1E3,k=new g.XqR(this.S.J());this.G=new Z$i(k,this.S,n,(J,Y)=>{Z.j7(J,x,Y,F)},this.Hw||g.u9(n.info),()=>{this.G&&this.G.reset();
this.Ze=!0})}}K(){var x=this.Ze;
this.Ze=!1;return x}V(x){var n=this.S.J().C("html5_fallback_if_rawcc_missing");var Z=this.L.Z.rawcc!=null;if(!this.Hw||!Z&&n)n=this.L.isManifestless?I42(this,"386"):I42(this);else{if(!Z){g.F0(this.logger,386248249,"rawcc used but unavailable");return}n=[new g.KS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.KS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let F of n)g.UU(this.Z,
F);x.jb()}B(){this.G&&(this.G.dispose(),this.G=null)}O(){return""}},f2=/^#(?:[0-9a-f]{3}){1,2}$/i;var i$2=["left","right","center","justify"];var WO=class extends g.Zu{constructor(x,n,Z,F,k,J=!1,Y=null){super(x,x+n,{priority:Z,namespace:"captions"});this.windowId=F;this.text=k;this.append=J;this.Z=Y}toString(){return super.toString()}};var tl=class extends g.t{constructor(x,n,Z,F,k,J,Y,v,L,S){var T=S.isInline()&&!0,U={};Object.assign(U,n);Object.assign(U,x.params);Object.assign(U,Z);var h={};Object.assign(h,n.KH);x.params.KH&&Object.assign(h,x.params.KH);Object.assign(h,Z.KH);T&&(U.windowOpacity=.6,h.backgroundOpacity=0);U.KH=h;var u=U.Yp===1,d=[{D:"span",W:"captions-text",A:{style:"word-wrap: normal; display: block;"}}],m=v.yF("caption_edit_on_hover")&&S.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
m&&d.unshift({D:"button",W:"caption-edit",A:{tabindex:"0","aria-label":f4s()},j:[{D:"svg",A:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},j:[{D:"path",A:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({D:"div",W:"caption-window",A:{id:`caption-window-${x.id}`,dir:u?"rtl":"ltr",tabindex:"0",lang:U.lang},j:d});this.experiments=
v;this.N=[];this.oW=!1;this.L=x;this.Pw=this.ue=null;this.V_=J;this.hN=Y;this.V=null;this.maxWidth=J*.96;this.maxHeight=Y*.96;this.Z=U;this.Oc=Z;this.cw=n;this.B=this.Sq("captions-text");x=this.B.style;this.C6=v.yF("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in x||"WebkitBoxDecorationBreak"in x);this.tZ=g0l(F,k,J,Y);this.oy=L;m&&(this.O=this.Sq("caption-edit"),this.X(this.O,"click",()=>{this.oy()}));
this.type=0;this.n6=this.tZ*$V$(h);this.SG=T;this.X9=v.yF("enable_centered_caption_for_tvfilm_video")&&S.getVideoData().isTvfilmVideo;this.Y=S.J().QF().Z.eq(g.rfI);F=new g.MH(this.element,!0);g.G(this,F);F.subscribe("dragstart",this.Kx,this);F.subscribe("dragmove",this.k6,this);F.subscribe("dragend",this.Nj,this);this.jq=this.AZ=this.LT=this.Zc=0;F="";this.Z.windowOpacity&&(F=yM(this.Z.windowColor),F="rgba("+F[0]+","+F[1]+","+F[2]+","+this.Z.windowOpacity+")");k={"background-color":F,display:this.Z.isVisible===
!1?"none":"","text-align":i$2[this.Z.textAlign]};this.C6&&(k["border-radius"]=F?`${this.n6*.375}px`:"");(this.U=this.L.params.Yp===2||this.L.params.Yp===3)&&Otl(this,this.element);g.jd(this.element,k);T&&this.element.parentElement?.style.setProperty("--caption-window-color",F);switch(this.Z.pC){case 0:case 1:case 2:g.Eu(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Eu(this.element,"ytp-caption-window-bottom")}}Kx(x,n){this.AZ=x;this.jq=n;var Z=g.tM(this.element,this.element.parentElement);
this.Zc=x-Z.x;this.LT=n-Z.y}k6(x,n){if(x!==this.AZ||n!==this.jq){g.X6(this.element,"ytp-dragging")||g.Eu(this.element,"ytp-dragging");var Z=g.xd(this.element);x=x-this.Zc-.02*this.V_;var F=n-this.LT-.02*this.hN,k=(x+Z.width/2)/this.maxWidth*3;k=Math.floor(g.la(k,0,2));var J=(F+Z.height/2)/this.maxHeight*3;J=Math.floor(g.la(J,0,2));n=k+J*3;x=(x+k/2*Z.width)/this.maxWidth;x=g.la(x,0,1)*100;Z=(F+J/2*Z.height)/this.maxHeight;Z=g.la(Z,0,1)*100;this.L.params.pC=n;this.L.params.y9=Z;this.L.params.hs=x;this.L.params.isDefault=
!1;this.Z.pC=n;this.Z.y9=Z;this.Z.hs=x;this.Z.isDefault=!1;this.cw.pC=n;this.cw.y9=Z;this.cw.hs=x;this.cw.isDefault=!1;this.M6()}}Nj(){g.WC(this.element,"ytp-dragging")}M6(){this.G(this.N)}G(x){var n=this.SG?0:Math.min(this.kH(),this.maxWidth),Z=this.G1(),F=this.SG;if(F){var k=getComputedStyle(this.B.parentNode);k=BO(k.borderLeftWidth)+BO(k.borderRightWidth)+BO(k.paddingLeft)+BO(k.paddingRight)}else k=0;var J=k;k="";this.L.params.Yp===3&&(k="rotate(180deg)");var Y=F?`calc(96% - ${J}px)`:"96%";g.jd(this.element,
{top:0,left:0,right:"",bottom:"",width:n?`${n}px`:"",height:Z?`${Z}px`:"","max-width":Y,"max-height":Y,margin:"",transform:""});this.r$(x);k={transform:k,top:"",left:"",width:n?`${n}px`:"",height:Z?`${Z}px`:"","max-width":"","max-height":""};Y=this.Z.pC;var v=this.Z.hs,L=this.Z.y9;this.X9&&Y!=null&&(v=50,Y=Math.floor(Y/3)*3+1);v=v*.96+2;switch(Y){case 0:case 3:case 6:(F=this.Z.KH.fontSizeIncrement)&&F>0&&this.Z.Yp!==2&&this.Z.Yp!==3&&(v=Math.max(v/(1+F*2),2));k.left=`${v}%`;break;case 1:case 4:case 7:k.left=
`${v}%`;v=0;this.Y||(v=this.B.offsetWidth);n||v?(n=n||v+1,k.width=`${n}px`,k["margin-left"]=F?`${n/-2-J/2}px`:`${n/-2}px`):(this.Y&&(k.width="max-content"),k.transform+=" translateX(-50%)");break;case 2:case 5:case 8:k.right=`${100-v}%`}F=L*.96+2;switch(Y){case 0:case 1:case 2:k.top=`${F}%`;break;case 3:case 4:case 5:k.top=`${F}%`;F=0;this.Y||(F=this.element.clientHeight);(Z=Z||F)?(k.height=`${Z}px`,k["margin-top"]=`${Z/-2}px`):k.transform+=" translateY(-50%)";break;case 6:case 7:case 8:k.bottom=
`${100-F}%`}g.jd(this.element,k);this.O&&(this.Y?Z=this.n6:(x=NWl(this,x),Z=this.X9?x>0?this.B.offsetHeight/x:0:this.B.offsetHeight/x),this.O.style.height=`${Z}px`,this.O.style.width=`${Z}px`,this.element.style.paddingLeft=`${Z+5}px`,this.element.style.paddingRight=`${Z+5}px`,this.Y||(x=Number(this.element.style.marginLeft.replace("px",""))-Z-5,Z=Number(this.element.style.marginRight.replace("px",""))-Z-5,this.element.style.marginLeft=`${x}px`,this.element.style.marginRight=`${Z}px`))}r$(x){if(this.type===
0&&this.L.params.la!==void 0&&this.experiments.yF("web_enable_popon_asr_captions")){var n=x,Z=this.L.params.la;if(n.length===0||Z<=0)x=[];else{x=[];for(let k=n.length-1;k>=0;k--){var F=n[k];x.unshift(F);let J=NWl(this,x);if(J>Z){x.shift();typeof F.text==="string"&&(n=F.text.split("\n"),Z=J-Z,n.length-Z>0&&(Z=n.slice(Z),F=new WO(F.start,F.end-F.start,F.priority||0,F.windowId,Z.join("\n"),F.append,F.Z),x.unshift(F)));break}}}}for(F=0;F<x.length&&x[F]===this.N[F];F++);if(this.oW||this.N.length>F)F=0,
this.oW=!1,this.N=[],this.V=this.Pw=this.ue=null,g.Sd(this.B);for(;F<x.length;F++)K3o(this,x[F])}kH(){return 0}G1(){return 0}toString(){return super.toString()}};var JsJ=class{constructor(){this.B=this.time=this.mode=this.L=0;this.U=new k3t(this);this.V=new k3t(this);this.Z=[];this.clear()}clear(){this.B=this.time=this.mode=0;this.Z=[];this.reset()}reset(){this.mode=0;this.U.reset(0);this.V.reset(1)}},Mce=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],Y92=class{constructor(){this.type=0}set(x){this.type=x}get(){return this.type}},vw$=class{constructor(){this.state=this.Fj=this.JS=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}lP(){return this.state!==0}matches(x,n){return this.lP()&&x===this.JS&&n===this.Fj}},LTu=class{constructor(){this.timestamp=this.Z=0}reset(){this.timestamp=
this.Z=0}},Al=class{constructor(x){this.V=x;this.B=[];this.Z=this.L=this.row=0;this.style=new Y92;this.U=0;for(x=0;x<=15;x++){this.B[x]=[];for(let n=0;n<=32;n++)this.B[x][n]=new LTu}}updateTime(x){for(let n=1;n<=15;++n)for(let Z=1;Z<=32;++Z)this.B[n][Z].timestamp=x}debugString(){var x="\n";for(let n=1;n<=15;++n){for(let Z=1;Z<=32;++Z){let F=this.B[n][Z];x=F.Z===0?x+"_":x+String.fromCharCode(F.Z)}x+="\n"}return x}reset(x){for(let n=0;n<=15;n++)for(let Z=0;Z<=32;Z++)this.B[n][Z].reset();this.U=x;this.Z=
0;this.L=this.row=1}},tci=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],AR$=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],xR2=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],nik=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],S9u=class{constructor(x){this.B=x;this.V=0;this.style=new Y92;this.O=new Al(this.B);this.N=new Al(this.B);this.text=new Al(this.B);this.L=this.O;this.U=this.N;this.Z=this.L}reset(x,n){this.V=n;this.style.set(2);this.L=this.O;this.U=this.N;this.Z=this.L;var Z=(x<<2)+(n<<1);this.O.reset(Z);this.N.reset(Z);this.text.reset((x<<
2)+(n<<1)+1)}},k3t=class{constructor(x){this.Z=x;this.V=0;this.B=new S9u(this.Z);this.O=new S9u(this.Z);this.L=new vw$;this.U=this.B}reset(x){this.V=x;this.L.clear();this.U=this.B;this.B.reset(x,0);this.O.reset(x,1)}};var TAe=class{U(){}};var xC=class extends g.sO{reset(){}};var m4=class extends g.Zu{constructor(x,n,Z,F,k){super(x,x+n,{priority:Z,namespace:"captions"});this.id=F;this.params=k;this.Z=[]}toString(){return super.toString()}},ob=0;var U2l=class extends xC{constructor(x){super();this.U=x;this.pens={};this.G={};this.Y={};this.V="_"+ob++;this.N={};this.L=this.Z=null;this.O=!0}reset(){this.N={};this.L=this.Z=null;this.O=!0}B(x,n){x=x.firstChild;x.getAttribute("format");n=n||0;Number.isFinite(n);x=Array.from(x.childNodes);for(var Z of x)if(Z.nodeType===1)switch(Z.tagName){case "head":var F=Z;break;case "body":var k=Z}if(F){F=Array.from(F.childNodes);for(var J of F)if(J.nodeType===1)switch(J.tagName){case "pen":Z=J.getAttribute("id");
F=this.pens;x={};var Y=J.getAttribute("p");Y&&Object.assign(x,this.pens[Y]);Y=lc(J,"b");Y!=null&&(x.bold=Y);Y=lc(J,"i");Y!=null&&(x.italic=Y);Y=lc(J,"u");Y!=null&&(x.underline=Y);Y=C2(J,"et");Y!=null&&(x.charEdgeStyle=Y);Y=C2(J,"of");Y!=null&&(x.offset=Y);Y=wD(J,"bc");Y!=null&&(x.background=Y);Y=wD(J,"ec");Y!=null&&(x.aS=Y);Y=wD(J,"fc");Y!=null&&(x.color=Y);Y=C2(J,"fs");Y!=null&&Y!==0&&(x.fontFamily=Y);Y=GD(J,"sz");Y!==void 0&&(x.fontSizeIncrement=Y/100-1);Y=GD(J,"bo");Y!==void 0&&(x.backgroundOpacity=
Y/255);Y=GD(J,"fo");Y!==void 0&&(x.textOpacity=Y/255);Y=C2(J,"rb");Y!=null&&Y!==10&&Y!==0&&(x.BC=Y>10?Y-1:Y);Y=C2(J,"hg");Y!=null&&(x.LK=Y);F[Z]=x;break;case "ws":F=J.getAttribute("id");this.Y[F]=LpJ(this,J);break;case "wp":F=J.getAttribute("id"),this.G[F]=Syt(this,J)}}if(k){J=[];k=Array.from(k.childNodes);for(m of k)if(m.nodeType===1)switch(m.tagName){case "w":this.Z=THe(this,m,n,!1);(k=this.N[this.Z.id])&&k.end>this.Z.start&&(k.end=this.Z.start);this.N[this.Z.id]=this.Z;J.push(this.Z);break;case "p":var v=
m;x=n;k=[];F=v.getAttribute("w")||this.V;Z=!!lc(v,"a");x=(GD(v,"t")||0)+x;Y=GD(v,"d")||5E3;Z||(!this.O&&this.L&&this.L.windowId===F&&this.L.end>x&&(this.L.end=x),this.L&&this.L.text==="\n"&&(this.L.text=""));let P=Z?6:5;var L=v.getAttribute("p");L=L?this.pens[L]:null;let H=Array.from(v.childNodes);H.length&&(this.O=v.getAttribute("d")!=null);for(v=0;v<H.length;v++){var S=H[v],T=void 0;v>0&&(Z=!0);let N;S.nodeType===1&&(N=S);if(N&&N.tagName==="s"){if((S=(S=N.getAttribute("p"))?this.pens[S]:null)&&
S.BC&&(S.BC===1?(S=H.slice(v,v+4),S.length===4&&(T=Yyl(x,Y,F,Z,P,S,this.pens),v+=3)):T=Yyl(x,Y,F,Z,P,[N],this.pens)),!T){var U=N;T=x;S=Y;var h=F,u=Z;let b=U.textContent?U.textContent:"";var d=U.getAttribute("p");d=d?this.pens[d]:null;U=GD(U,"t")||0;T=new WO(T+U,S-U,P,h,b,u,d)}}else T=new WO(x,Y,P,F,S.textContent||"",Z,L);k.push(T);this.L=T}if(k.length>0){k[0].windowId===this.V&&(this.Z=THe(this,m,n,!0),J.push(this.Z));for(let N of k)N.windowId=this.Z.id,this.Z.Z.push(N),J.push(N)}}var m=J}else m=
[];return m}};var uce=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),h4J=class extends xC{constructor(x){super();this.O=x;this.Z=new Map;this.U=new Map;this.V=new Map;this.L=new Map}reset(){this.L.clear()}B(x,n){x=JSON.parse(x);if(!x)return[];if(x.pens){var Z=x.pens,F=0;for(var k of Z){Z={};var J=k.pParentId;J&&Object.assign(Z,this.Z.get(J));k.bAttr&&(Z.bold=!0);k.iAttr&&(Z.italic=!0);k.uAttr&&(Z.underline=!0);J=k.ofOffset;J!=null&&(Z.offset=J);k.szPenSize!==void 0&&(Z.fontSizeIncrement=k.szPenSize/100-1);
J=k.etEdgeType;J!=null&&(Z.charEdgeStyle=J);k.ecEdgeColor!==void 0&&(Z.aS=VM(k.ecEdgeColor));J=k.fsFontStyle;J!=null&&J!==0&&(Z.fontFamily=J);k.fcForeColor!==void 0&&(Z.color=VM(k.fcForeColor));k.foForeAlpha!==void 0&&(Z.textOpacity=k.foForeAlpha/255);k.bcBackColor!==void 0&&(Z.background=VM(k.bcBackColor));k.boBackAlpha!==void 0&&(Z.backgroundOpacity=k.boBackAlpha/255);(J=k.rbRuby)&&J!==10&&(Z.BC=J>10?J-1:J,Z.textEmphasis=uce.get(Z.BC));k.hgHorizGroup&&(Z.LK=k.hgHorizGroup);this.Z.set(F++,Z)}}if(x.wsWinStyles){F=
x.wsWinStyles;k=0;for(var Y of F)F={},(Z=Y.wsParentId)?Object.assign(F,this.V.get(Z)):Object.assign(F,this.O),Y.mhModeHint!==void 0&&(F.Zk=Y.mhModeHint),Y.juJustifCode!==void 0&&(F.textAlign=Y.juJustifCode),Y.pdPrintDir!==void 0&&(F.Yp=Y.pdPrintDir),Y.sdScrollDir!==void 0&&(F.GQ=Y.sdScrollDir),Y.wfcWinFillColor!==void 0&&(F.windowColor=VM(Y.wfcWinFillColor)),Y.wfoWinFillAlpha!==void 0&&(F.windowOpacity=Y.wfoWinFillAlpha/255),this.V.set(k++,F)}if(x.wpWinPositions){k=x.wpWinPositions;Y=0;for(var v of k)k=
{},(F=v.wpParentId)&&Object.assign(k,this.U.get(F)),v.ahHorPos!==void 0&&(k.hs=v.ahHorPos),v.apPoint!==void 0&&(k.pC=v.apPoint),v.avVerPos!==void 0&&(k.y9=v.avVerPos),v.ccCols!==void 0&&(k.tI=v.ccCols),v.rcRows!==void 0&&(k.la=v.rcRows),this.U.set(Y++,k)}if(x.events){x=x.events;v=[];for(let M of x)if(Y=(M.tStartMs||0)+n,k=M.dDurationMs||0,M.id)F=String(M.id),x=UR6(this,M,Y,k,F),v.push(x),this.L.set(F,x);else{M.wWinId?F=M.wWinId.toString():(F="_"+ob++,x=UR6(this,M,Y,k,F),v.push(x),this.L.set(F,x));
x=v;var L=M;k===0&&(k=5E3);Z=this.L.get(F);let nn=(J=!!L.aAppend)?6:5,yO=L.segs,mq=null;L.pPenId&&(mq=this.Z.get(L.pPenId));for(L=0;L<yO.length;L++){var S=yO[L],T=S.utf8;if(T){var U=S.tOffsetMs||0;let jT=null;S.pPenId&&(jT=this.Z.get(S.pPenId));if((Z.params.Zk!=null?Z.params.Zk:Z.Z.length>1?1:0)===2&&J&&T==="\n")continue;S=null;var h=[],u;if(u=jT&&jT.BC===1)a:{u=yO;var d=L;if(d+3>=u.length||!u[d+1].pPenId||!u[d+2].pPenId||!u[d+3].pPenId){u=!1;break a}var m=u[d+1].pPenId;(m=this.Z.get(m))&&m.BC&&m.BC===
2?(m=u[d+2].pPenId,m=this.Z.get(m),!m||!m.BC||m.BC<3?u=!1:(m=u[d+3].pPenId,u=(m=this.Z.get(m))&&m.BC&&m.BC===2?!0:!1)):u=!1}if(u)U=yO[L+1].utf8,S=yO[L+3].utf8,u=yO[L+2].utf8,d=this.Z.get(yO[L+2].pPenId),T=JDo(T,U,u,S,d),S=new WO(Y,k,nn,F,T,J,jT),L+=3;else{if(T.indexOf("<")>-1){h=jT;u=mq;d=Y;m=k;var P=U,H=nn,N=J;let pn=[];var b=g.nJ(`<html>${T}</html>`);if(!b.getElementsByTagName("parsererror").length&&b.firstChild?.childNodes.length)for(let tg of b.firstChild.childNodes){b=tg.textContent?.replace(/\n/g,
"")??"";if(tg.nodeType===3&&(!b||b.match(/^ *$/)!=null))continue;let fY={};Object.assign(fY,h||u);switch(tg?.tagName){case "b":fY.bold=!0;break;case "i":fY.italic=!0;break;case "u":fY.underline=!0}pn.push(new WO(d+P,m-P,H,Z.id,b,N,fY))}h=pn}h.length||(h=[new WO(Y+U,k-U,nn,Z.id,T,J,jT||mq)])}if(h.length)for(let pn of h)x.push(pn),Z.Z.push(pn);else S&&(x.push(S),Z.Z.push(S))}J=!0}}n=v}else n=[];return n}};var e4k=class extends g.HH{constructor(x,n,Z){super(x);this.videoData=n;this.audioTrack=Z;this.Y=n.M9}U(x,n,Z){GT2(this.videoData.videoId,x.vssId,Z.j7)}V(x){if(this.audioTrack)for(let n of this.audioTrack.captionTracks)g.UU(this.Z,n);x.jb()}};var RSe=class extends tl{constructor(x,n,Z,F,k,J,Y,v,L,S){super(x,n,Z,F,k,J,Y,v,L,S);this.type=1}r$(x){var n=this.L.Z;super.r$(x);for(x=x.length;x<n.length;x++){let k=n[x],J;if(F&&k.Z===Z)J=F;else{J={};Object.assign(J,k.Z);Object.assign(J,ysz);var Z=k.Z;var F=J}K3o(this,k,J)}}},ysz={FV:!0};var us2=class extends TAe{constructor(x,n){super();this.trackData=x;this.O=n;this.version=this.V=this.B=this.byteOffset=0;this.L=[];this.Z=new DataView(this.trackData)}U(x,n,Z,F,k){if(Z<F){let J="_"+ob++;Z=Z/1E3-this.O;F=F/1E3-this.O;x=new m4(Z,F-Z,5,J,{textAlign:0,pC:0,hs:n*2.5,y9:x*5.33});k=new WO(Z,F-Z,5,J,k);this.L.push(x);this.L.push(k)}}},s9e=class extends xC{constructor(x,n){super();this.L=x;this.U=n;this.track=this.U.languageName==="CC3"?4:0;this.Z=new JsJ;this.Z.L=1<<this.track}B(x){x=new us2(x,
this.L);if(hSe(x)){for(;x.byteOffset<x.Z.byteLength;)for(x.version===0?x.B=jF(x)*(1E3/45):x.version===1&&(x.B=jF(x)*4294967296+jF(x)),x.V=PO(x);x.V>0;x.V--){var n=PO(x);let Z=PO(x),F=PO(x);n&4&&(n&3)===this.track&&(this.track===0||this.track===1)&&(n=this.Z,n.Z.push({time:x.B,type:this.track,Mo:Z,fm:F,order:n.Z.length}))}DVl(this.Z,x);return x.L}return[]}reset(){this.Z.clear()}};var DR6=class extends tl{constructor(x,n,Z,F,k,J,Y,v,L,S){super(x,n,Z,F,k,J,Y,v,L,S);this.type=2;this.VF=[];this.Hw=this.K=this.ie=0;this.w$=NaN;this.WD=0;this.YH=null;this.yd=new g.eP(this.RW,433,this);this.O&&(S.createClientVe(this.O,this,167342),this.X(this.O,"click",()=>{S.logClick(this.O)}),x=new g.MH(this.element,!0),g.G(this,x),x.subscribe("hoverstart",()=>{S.logVisibility(this.O,!0)},this));
g.Eu(this.element,"ytp-caption-window-rollup");g.G(this,this.yd);g.jd(this.element,"overflow","hidden")}M6(){g.BC(this.yd)}RW(){this.element.removeEventListener("transitionend",this.RW,!1);g.WC(this.element,"ytp-rollup-mode");this.G(this.YH,!0)}G1(){return this.U?this.Hw:this.K}kH(){return this.U?this.K:this.Hw}G(x,n){this.YH=x;if(this.L.params.la){var Z=0;for(let F=0;F<this.N.length&&Z<x.length;F++)this.N[F]===x[Z]&&Z++;Z>0&&Z<x.length&&(x=this.N.concat(x.slice(Z)));this.WD=this.Hw;this.K=this.Hw=
0;super.G(x);BHl(this,n)}super.G(x)}};var BAo=class{constructor(x,n,Z,F){this.S=x;this.V=n;this.logger=Z;this.Dc=F;this.bb=[];this.Z=null;this.B=[];this.Wx=[];this.L=null;this.z1={hPF:()=>this.L,
wZ:()=>this.bb,
qSR:k=>{this.B=k},
EVj:()=>this.B};
x=g.eL(this.S.J().experiments,"html5_override_micro_discontinuities_threshold_ms");this.U=x>0?x:10}unload(){this.L!=null&&(this.S.removeEventListener("sabrCaptionsDataLoaded",this.L),this.L=null);this.bb=[];this.Z=null;this.B=[];this.S.publish("sabrCaptionsBufferedRangesUpdated",this.bb)}PV(x){return{formatId:g.ex(x.info.p6.info,this.Dc),mU:x.info.mU+(this.Dc?0:1),startTimeMs:x.info.U*1E3,durationMs:x.info.O*1E3}}};var akt=class extends g.HH{constructor(x,n){super(n);this.L=x;this.S=n;this.logger=new g.Za("caps");this.G=this.Hw=null;this.Ze=new BAo(this.S,this,this.logger,this.L.Dc)}U(x,n,Z){this.B();n=x.getId();n=n!=null&&n in this.L.Z?this.L.Z[n]:null;n||(n=x.languageCode,n=this.L.isManifestless?Wpz(this,n,"386"):Wpz(this,n));n&&(this.G=x,this.Hw=n,Ei6(this.Ze,Z),this.S.publish("sabrCaptionsTrackChanged",g.ex(n.info,this.L.Dc)))}V(x){var n=this.L.isManifestless?oiz(this,"386"):oiz(this);for(let Z of n)g.UU(this.Z,
Z);x.jb()}B(){this.G&&(this.G=this.Hw=null,this.Ze.unload(),this.S.publish("sabrCaptionsTrackChanged",null))}O(){return""}};var mRt="WEBVTT".split("").map(x=>x.charCodeAt(0)),V3J=class extends xC{constructor(){super()}B(x,n){x instanceof ArrayBuffer&&(x=g.k4(new Uint8Array(x)));
var Z=[];x=x.split(d2l);for(let d=1;d<x.length;d++){var F=x[d],k=n;if(F!==""&&!Q9u.test(F)){var J=ni.exec(F);if(J&&J.length>=4){var Y=qM(J[1]),v=qM(J[2])-Y;Y+=k;var L=(J=J[3])?J.split(" "):[];J={};var S=null;var T="";var U=null,h="";for(let m of L){L=m.split(":");if(L.length!==2)continue;var u=L[1];switch(L[0]){case "line":L=u.split(",");L[0].endsWith("%")&&(S=L[0],J.y9=Number.parseInt(S,10),L.length===2&&(T=L[1].trim()));break;case "position":L=u.split(",");U=L[0];J.hs=Number.parseInt(U,10);L.length===
2&&(h=L[1].trim());break;case "align":switch(u){case "start":J.textAlign=0;break;case "middle":J.textAlign=2;break;case "end":J.textAlign=1}}}S||T||(T="end");if(!U)switch(J.textAlign){case 0:J.hs=0;break;case 1:J.hs=100;break;case 2:J.hs=50}if(J.textAlign!=null){S=0;switch(T){case "center":S+=3;break;case "end":S+=6;break;default:S+=0}switch(h){case "line-left":S+=0;break;case "center":S+=1;break;case "line-right":S+=2;break;default:switch(J.textAlign){case 0:S+=0;break;case 2:S+=1;break;case 1:S+=
2}}T=S<0||S>8?7:S;J.pC=T}F=F.substring(ni.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");h=J;J={};if(F.indexOf("<")<0&&F.indexOf("&")<0)k=lSi(Y,v,5,h),Y=new WO(Y,v,5,k.id,F,!1,g.c6(J)?void 0:J),Z.push(k),Z.push(Y),k.Z.push(Y);else for(T=F.split(XI6),T.length===1?(F=5,h=lSi(Y,v,F,h)):(S=F=6,h=Object.assign({tI:32},h),h=new m4(Y,v,S,"_"+ob++,h)),Z.push(h),S=Y,U=0;U<T.length;U++)if(L=T[U],U%2===0){u=g.nJ(`<html>${L}</html>`);let m;u.getElementsByTagName("parsererror").length?(m=u.createElement("span"),
m.appendChild(u.createTextNode(L))):m=u.firstChild;Coi(this,S,v-(S-Y),F,h,U>0,m,J,Z)}else S=qM(L)+k}ni.lastIndex=0}}return Z}},Q9u=/^NOTE/,d2l=/(?:\r\n|\r|\n){2,}/,ni=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),XI6=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var Ewu=class extends g.sO{constructor(x,n){super();this.S=x;this.hZ=n;this.Z=null;this.FY=this.S.PY();this.logger=new g.Za("caps")}clear(){this.Z&&this.Z.dispose();this.Z=null}reset(){this.Z&&this.Z.reset()}Bw(){super.Bw();this.clear()}};var gik={windowColor:"#080808",windowOpacity:0,textAlign:2,pC:7,hs:50,y9:100,isDefault:!0,KH:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},ISs={windowColor:"#080808",windowOpacity:0,textAlign:0,pC:7,hs:50,y9:100,isDefault:!0,KH:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.T1("captions",class extends g.Oe{constructor(x){super(x);this.S=x;this.w$=[];this.cw={};this.C6={};this.N=!1;this.B="NONE";this.Z=this.Y=this.Ze=this.ie=this.tZ=null;this.AZ={jb:()=>{this.jb()},
j7:(F,k,J,Y,v=0)=>{var L=Number(this.videoData.J().QF().Z.eq(g.YZQ)??0);v>0&&L>0&&this.videoData.lengthSeconds>0&&v/this.videoData.lengthSeconds>L?this.S.L6("tts",{dropcap:v}):this.j7(F,k,J,Y)}};
this.L=null;this.Zc="";this.hZ=this.S.J();this.videoData=this.S.getVideoData();this.RW=this.S.YP();this.V={KH:{}};this.O={KH:{}};this.videoData.fT()?this.B="OFFLINE":g.rXu(this.videoData,this.S)?this.B="HLS":zSs(this.videoData,this.S)?this.B="SABR_LIVE":g.RMc(this.videoData,this.S)?this.B="LIVE":this.videoData.captionTracks.length?this.B="INNERTUBE":this.videoData.LT&&(this.B="TTS");this.ue=this.hZ.controlsType==="3";this.r$=new Ewu(this.S,this.hZ);this.VF=new g.EE(this);this.G=new g.t({D:"div",W:"ytp-caption-window-container",
A:{id:"ytp-caption-window-container"}});this.Hw={top:0,right:0,bottom:0,left:0,width:1,height:1};var n=null,Z=g.AK("yt-html5-player-modules::subtitlesModuleData");Z&&(n=new g.bd(Z));this.storage=n;n=x.tJ();this.LT=!!n?.w$();this.X9=!!n?.oW();this.U=Ib(this);this.K=qyJ(this);g.G(this,this.r$);this.U?this.Pw=this.oW=null:(this.oW=new g.hK(this.SG,void 0,this),g.G(this,this.oW),this.Pw=new g.eP(this.yd,2E3,this),g.G(this,this.Pw));g.G(this,this.VF);g.KD(this.player,this.G.element,4);g.G(this,this.G);
this.U||this.VF.X(x,"resize",this.jq);n=g.un(this.hZ)&&!g.Uv()&&!this.S.isFullscreen();Z=this.hZ.QF().Z.eq(g.oKK)&&g.Zp(this.hZ)&&g.Wn;(this.fT=(n||Z)&&!this.U&&!this.K)&&this.VF.X(x,n?"resize":"fullscreentoggled",this.kH);this.VF.X(x,"onPlaybackAudioChange",this.G1);this.VF.X(x,g.OY("captions"),F=>{this.onCueRangeEnter(F)});
this.VF.X(x,g.HK("captions"),F=>{this.onCueRangeExit(F)});
gD(this,sn()||{});g.l6(this.player,"onCaptionsModuleAvailable");this.B==="HLS"&&this.U&&(x=this.S.tJ().q6(),this.X9&&this.VF.X(x.textTracks,"addtrack",this.WD))}Bw(){if(this.U||this.K){let x=this.S.tJ();x&&!x.MX()&&x.N()}else $B(this,!1);super.Bw()}OJ(){return this.hZ.C("html5_honor_caption_availabilities_in_audio_track")&&this.B!=="LIVE"&&this.B!=="SABR_LIVE"}Gu(){if(this.ue)return this.U||this.K;if(this.B==="HLS")return this.U;var x=this.getAudioTrack();if(this.OJ()){if(!x.captionTracks.length)return!1;
if(!this.Z)return!0}x=eF(x,g.WU(this.hZ));return x==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:x==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?bc(this):NM(this)||bc(this)?!0:NHe(this)}load(){super.load();this.Y=this.getAudioTrack();if(this.Z)this.L&&(this.r$.clear(),this.U?bjt(this,!0):this.player.getPresentingPlayerType()!==3&&this.Z.U(this.L,"json3",this.AZ),this.B!=="HLS"&&this.U||this.K||p2(this)||g.l6(this.player,"captionschanged",g.mE(this.L)));else{let x;this.B==="OFFLINE"?x=new e4k(this.player,this.videoData,
this.getAudioTrack()):this.B==="SABR_LIVE"?x=new akt(this.videoData.Z,this.player):this.B==="HLS"?x=new x2k(this.player):this.B==="LIVE"?x=new FTk(this.videoData.Z,this.player):this.B==="INNERTUBE"?x=new g.Nx(this.player,this.videoData,this.getAudioTrack()):x=new g.bs(this.player,this.videoData.LT,this.videoData.videoId,g.CvI(this.videoData),this.videoData.YV,this.videoData.eventId);this.Z=x;g.G(this,this.Z);this.Z.V(this.AZ)}}unload(){this.U&&this.L?bjt(this,!1):(this.Pw&&this.Pw.DR(),this.player.fH("captions"),
this.w$=[],this.Z&&this.Z.B(),this.r$.clear(),this.Ze&&this.player.Zr(this.Ze),this.jq());super.unload();this.player.zL();g.l6(this.player,"captionschanged",{})}create(){this.Gu()&&this.load();var x;a:{if(this.hZ.C("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(x=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let n of x)if(n.kind==="asr"&&n.languageCode===
"en"){x=!0;break a}x=!1}x&&this.S.publish("showpromotooltip",this.G.element)}jb(){var x=eF(this.player.getAudioTrack(),g.WU(this.hZ));var n=x==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?MM(this,this.N):x==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&bc(this)?K2(this):NM(this)||this.N||NHe(this)?MM(this,this.N):bc(this)?K2(this):null;if(this.B!=="HLS"&&this.U||this.K){let Z=g.KW(this.Z.Z,!0);x=[];for(let F=0;F<Z.length;F++){let k=Z[F],J=g.Yf("TRACK");J.setAttribute("kind","subtitles");J.setAttribute("label",
g.oh(k));J.setAttribute("srclang",g.Gk(k));J.setAttribute("id",k.toString());this.K||J.setAttribute("src",this.Z.O(k,"vtt"));k===n&&J.setAttribute("default","1");x.push(J)}n=this.S.tJ();n.Ze(x);x=n.q6();this.X9&&this.VF.X(x.textTracks,"change",this.M6)}else!this.L&&n&&Dq(this,n),g.l6(this.player,"onCaptionsTrackListChanged"),g.CD(this.player,"onApiChange")}getTrackById(x){var n=g.KW(this.Z.Z,!0);for(let Z=0;Z<n.length;Z++)if(n[Z].toString()===x)return n[Z];return null}M6(){var x=this.S.tJ().q6().textTracks,
n=null;for(let Z=0;Z<x.length;Z++)x[Z].mode==="showing"&&(n=this.getTrackById(x[Z].id));(this.loaded?this.L:null)!==n&&Dq(this,n,!0)}WD(){this.Z?.V(this.AZ)}BX(){!this.L&&this.U||this.unload()}j7(x,n,Z,F){if(x){Rb(this,this.L??void 0);this.Z.K()&&(this.w$=[],this.S.fH("captions"),hl(this.oW),this.r$.reset());a:{var k=this.r$;F=F||0;Z=wGe(k,x,Z||0);x=[];try{for(let H of Z){let N=H.trackData,b=H.vl,M=k.hZ.C("safari_live_drm_captions_fix");if(typeof N!=="string"){Z=x;var J=Z.concat;if(M&&Gnk(N))var Y=
Pol(k,N,b);else{var v=k,L=n,S=N,T=b,U=F;if(!eSJ(S))throw Error("Invalid binary caption track data");v.Z||(v.Z=new s9e(U,L));Y=v.Z.B(S,T)}var h=J.call(Z,Y)}else{if(N.substring(0,6)==="WEBVTT")var u=x.concat(Pol(k,N,b));else{Z=x;var d=Z.concat;b:{L=k;v=n;if(N[0]==="{")try{L.Z||(L.Z=new h4J(jpi(v)));var m=L.Z.B(N,b);break b}catch(mq){g.Dz(mq);m=[];break b}let nn=g.nJ(N);if(!nn||!nn.firstChild){let mq=Error("Invalid caption track data");mq.params=N;throw mq;}if(nn.firstChild.tagName==="timedtext"){if(Number(nn.firstChild.getAttribute("format"))===
3){S=nn;L.Z||(L.Z=new U2l(jpi(v)));m=L.Z.B(S,b);break b}let mq=Error("Unsupported subtitles format in web player (Format2)");mq.params=N;throw mq;}if(nn.firstChild.tagName==="transcript"){let mq=Error("Unsupported subtitles format in web player (Format1)");mq.params=N;throw mq;}let yO=Error("Invalid caption track data");yO.params=N;throw yO;}u=d.call(Z,m)}h=u}x=h}var P=x;break a}catch(H){g.F0(k.logger,187101178,`Captions parsing failed: ${H.message}. `);k.clear();P=[];break a}P=void 0}this.hZ.C("html5_sabr_live_support_subfragmented_captions")&&
this.Z instanceof akt&&(n=this.Z.Ze,k=[],P.length>0&&(k=P.slice(n.B.length)),n.B=!n.Z||n.Z.info.uP?[]:P,P=k);n=this.hZ.QF().Z.eq(g.eW1);P.length>0&&(!n||this.Zc!==this.L?.L())&&(k=this.L,this.WL(k,!!k,p2(this)?"g":this.N?"m":"s"),n&&(this.Zc=this.L?.L()||""));this.player.Zr(P,void 0,this.B==="LIVE"||this.B==="SABR_LIVE");!this.N||this.K||p2(this)||g.o1(this.hZ)||g.UI(this.hZ)||g.si(this.hZ)||this.hZ.VF==="shortspage"||this.player.isInline()||(this.Pw.DR(),P=vit({pC:0,hs:5,y9:5,la:2,textAlign:0,Yp:0,
lang:"en"}),this.ie=[P],n=["Click "," for settings"],this.tZ||(k=new g.$W(g.cV()),g.G(this,k),this.tZ=k.element),k=P.end-P.start,(h=g.oh(this.L))&&this.ie.push(new WO(P.start,k,0,P.id,h)),this.ie.push(new WO(P.start,k,0,P.id,n[0]),new WO(P.start,k,0,P.id,this.tZ,!0),new WO(P.start,k,0,P.id,n[1],!0)),this.player.Zr(this.ie),g.yq(this.Pw));!this.N||this.K||p2(this)||(this.hZ.C("enable_player_captions_persistence_state_machine")?HO(this,!0):g.WU(this.hZ)?cO(this,!0):rD(this,!0),this.Y&&(this.Y.U=this.L),
this.player.zL());this.N=!1}}onCueRangeEnter(x){this.w$.push(x);hl(this.oW)}onCueRangeExit(x){g.Ze(this.w$,x);this.Z instanceof FTk&&this.Z.Hw&&this.player.St([x]);hl(this.oW)}getCaptionWindowContainerId(){return this.G.element.id}yd(){$Ri(this,this.ie);this.ie=null}SG(){if(!this.fT||!this.U){this.oW.stop();g.rt(this.C6);this.w$.sort(g.$H);var x=this.w$;if(this.Ze){let n=g.HN(x,function(Z){return this.Ze.indexOf(Z)===-1},this);
n.length&&(x=n)}for(let n of x)n instanceof m4?M3z(this,n):cDk(this,n);for(let [n,Z]of Object.entries(this.cw)){let F=n,k=Z;this.C6[F]?(k.element.parentNode||(k instanceof DR6||k instanceof RSe||g.Gu(this.cw,(J,Y)=>{Y!==F&&J.L.params.pC===k.L.params.pC&&J.L.params.hs===k.L.params.hs&&J.L.params.y9===k.L.params.y9&&(J.dispose(),delete this.cw[Y]);return Y===F},this),this.G.element.appendChild(k.element)),k.G(this.C6[F])):(k.dispose(),delete this.cw[F])}}}UV(){gD(this,{},!0);
g.l6(this.player,"captionssettingschanged")}O6(){var x=this.hZ.C("enable_player_captions_new_style_defaults")?ISs:gik,n=x.KH;x={background:n.background,backgroundOpacity:n.backgroundOpacity,charEdgeStyle:n.charEdgeStyle,color:n.color,fontFamily:n.fontFamily,fontSizeIncrement:n.fontSizeIncrement,fontStyle:n.bold&&n.italic?3:n.bold?1:n.italic?2:0,textOpacity:n.textOpacity,windowColor:x.windowColor,windowOpacity:x.windowOpacity};n=sn()||{};n.background!=null&&(x.background=n.background);n.backgroundOverride!=
null&&(x.backgroundOverride=n.backgroundOverride);n.backgroundOpacity!=null&&(x.backgroundOpacity=n.backgroundOpacity);n.backgroundOpacityOverride!=null&&(x.backgroundOpacityOverride=n.backgroundOpacityOverride);n.charEdgeStyle!=null&&(x.charEdgeStyle=n.charEdgeStyle);n.charEdgeStyleOverride!=null&&(x.charEdgeStyleOverride=n.charEdgeStyleOverride);n.color!=null&&(x.color=n.color);n.colorOverride!=null&&(x.colorOverride=n.colorOverride);n.fontFamily!=null&&(x.fontFamily=n.fontFamily);n.fontFamilyOverride!=
null&&(x.fontFamilyOverride=n.fontFamilyOverride);n.fontSizeIncrement!=null&&(x.fontSizeIncrement=n.fontSizeIncrement);n.fontSizeIncrementOverride!=null&&(x.fontSizeIncrementOverride=n.fontSizeIncrementOverride);n.fontStyle!=null&&(x.fontStyle=n.fontStyle);n.fontStyleOverride!=null&&(x.fontStyleOverride=n.fontStyleOverride);n.textOpacity!=null&&(x.textOpacity=n.textOpacity);n.textOpacityOverride!=null&&(x.textOpacityOverride=n.textOpacityOverride);n.windowColor!=null&&(x.windowColor=n.windowColor);
n.windowColorOverride!=null&&(x.windowColorOverride=n.windowColorOverride);n.windowOpacity!=null&&(x.windowOpacity=n.windowOpacity);n.windowOpacityOverride!=null&&(x.windowOpacityOverride=n.windowOpacityOverride);return x}FZ(x,n){var Z={};Object.assign(Z,sn());Object.assign(Z,x);gD(this,Z,n);g.l6(this.player,"captionssettingschanged")}jq(){!this.U&&this.loaded&&(g.W6(this.cw,function(x,n){x.dispose();delete this.cw[n]},this),this.SG())}SC(x,n){switch(x){case "fontSize":if(isNaN(n))break;
x=g.la(n,-2,4);this.FZ({fontSizeIncrement:x});return x;case "reload":n&&!this.U&&Dq(this,this.L,!0);break;case "stickyLoading":n!==void 0&&this.hZ.Ze&&(this.hZ.C("enable_player_captions_persistence_state_machine")?HO(this,!(!n||!n.userInitiated)):g.WU(this.hZ)?cO(this,!!n):rD(this,!!n));break;case "track":return t3e(this,n);case "tracklist":return this.Z?g.NK(g.KW(this.Z.Z,!(!n||!n.includeAsr)),Z=>g.mE(Z)):[];
case "translationLanguages":return this.Z?this.Z.Y.map(Z=>Object.assign({},Z)):[];
case "sampleSubtitles":this.U||n===void 0||$B(this,!!n);break;case "sampleSubtitlesCustomized":this.U||$B(this,!!n,n);break;case "recommendedTranslationLanguages":return g.Qp();case "defaultTranslationSourceTrackIndices":return this.Z?this.Z.cw:[]}}getOptions(){var x="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.hZ.Ze&&x.push("stickyLoading");return x}VK(){var x=this.L;if(this.S.DH("captions")){if(this.hZ.C("html5_modify_caption_vss_logging"))return(x=this.videoData.Ji??
null)?{cc:g.nDO(x)}:{};if(x){let n=x.vssId;x.translationLanguage&&n&&(n=`t${n}.${g.Gk(x)}`);return{cc:n}}}return{}}Ad(x){this.isSubtitlesOn()?(this.hZ.C("enable_player_captions_persistence_state_machine")&&x?HO(this,!1):g.WU(this.hZ)?cO(this,!1):rD(this,!1),Rb(this),Dq(this,null,!0)):this.wS(x)}wS(x){var n=p2(this)||!this.L?MM(this,!0):this.L;n&&this.gZ(n.vssId,"m");this.isSubtitlesOn()||Dq(this,n,this.hZ.C("enable_player_captions_persistence_state_machine")?x:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.L&&!p2(this)}G1(){var x=p2(this);bc(this,x)?Dq(this,this.getAudioTrack().Z,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.OJ()&&(this.N=!1,this.L=null,this.Z&&(this.Z.dispose(),this.Z=null)),this.Gu()&&(x?Dq(this,MM(this,!1),!1):this.load()))}KS(x){x&&(this.Hw={top:x.top,right:x.right,bottom:x.bottom,left:x.left,width:1-x.left-x.right,height:1-x.top-x.bottom},this.G.element.style.top=`${this.Hw.top*100}%`,this.G.element.style.left=`${this.Hw.left*100}%`,this.G.element.style.width=
`${this.Hw.width*100}%`,this.G.element.style.height=`${this.Hw.height*100}%`,this.G.element.style.position="absolute",x=rD6(this))&&(this.G.element.style.width=`${x.width}px`,this.G.element.style.height=`${x.height}px`)}onVideoDataChange(x,n){x==="newdata"&&(this.videoData=n,this.loaded&&this.unload(),this.N=!1,this.L=null,this.Z&&(this.Z.dispose(),this.Z=null,g.l6(this.player,"captionschanged",{})),this.Gu()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}kH(){if(this.hZ.QF().Z.eq(g.oKK)){if(this.loaded&&
this.unload(),this.ue=this.S.isFullscreen()||this.hZ.controlsType==="3",this.U=Ib(this),this.K=qyJ(this),this.U||this.K){var x=this.S.tJ();x&&!x.MX()&&x.N();this.jb()}}else(x=this.S.tJ())&&!x.MX()&&x.N(),this.S.isFullscreen()?(this.U=this.ue=!0,this.loaded&&this.jb()):(this.ue=this.hZ.controlsType==="3",this.U=Ib(this));Dq(this,this.L)}n6(){var x=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;x&&g.Wf(this.player,"innertubeCommand",x)}WL(x,n,Z){var F=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,k="";x&&(k=x.vssId,k=k.replace(F,""));var J="";if(x&&x.getId()&&this.hZ.QF().Z.eq(g.eW1))if(J=x.getId()||"",J.includes(";"))J=J.split(";").map(v=>v.replace(F,"")).join(";");
else{J=J.replace(F,"");var Y="";x.getXtags()&&(Y=x.getXtags(),Y=Y.replace(F,""),J=J.concat(`;${Y}`))}else x&&x.getId()&&(J=x.getId()||""),Y="",x&&x.getXtags()&&(Y=x.getXtags(),Y=Y.replace(F,""),J=J.concat(`;${Y}`));this.B==="HLS"&&(J="");this.S.WL(n?k:"",n?J:"",Z)}gZ(x,n){x=(x||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");x.length>0&&this.S.gZ(x,n)}});})(_yt_player);
