(function(g){var window=this;'use strict';var Mnl=function(x,n){g.Wf(x,"onAutonavCoundownStarted",n)},cst=function(x){return x.isBackground()&&x.G6()},rsk=function(x,n){n=n.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
x.K=n?.navigationEndpoint;n=n?.trackingParams;x.playButton&&n&&x.S.setTrackingParams(x.playButton.element,n)},UH=function(x){var n=SX(x),Z=Math,F=Z.min;
var k=x.N?Date.now()-x.N:0;Z=F.call(Z,k,n);Tq(x,Math.ceil((n-Z)/1E3));n-Z<=500&&x.Z()?x.select(!0):x.Z()&&x.G.start()},uT=function(x){var n=x.S.Px(!0,x.S.isFullscreen());
g.mu(x.container.element,"ytp-autonav-endscreen-small-mode",x.JF(n));g.mu(x.container.element,"ytp-autonav-endscreen-is-premium",!!x.suggestion&&!!x.suggestion.d9);g.mu(x.S.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!x.S.lL());g.mu(x.S.getRootNode(),"countdown-running",x.Z());g.mu(x.container.element,"ytp-player-content",x.S.lL());x.S.C("web_post_play_autonav_embiggening")||g.jd(x.overlay.element,{width:`${n.width}px`});if(x.S.C("web_post_play_autonav_embiggening")){var Z=x.S.getRootNode().getBoundingClientRect();
n=Math.min(720,Z.width*.5);var F=n*.5625;Z=Z.height-36-60;F>Z&&(F=Z,n=16/9*F);g.jd(x.L.Sq("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${F}px`,width:`${n}px`});g.jd(x.container.element,{width:`${n}px`})}x.Z()||(x.S.lL()?Tq(x,Math.round(SX(x)/1E3)):Tq(x),n=!!x.suggestion&&!!x.suggestion.Rs,F=x.S.getVideoData(),F=F?.autonavState===1&&F?.Nj&&x.S.lL()?!1:x.S.lL()||!(x.suggestion&&x.suggestion.Rs),g.mu(x.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!F&&n),g.mu(x.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",F&&!n),x.O.Jh(x.S.lL()))},Tq=function(x,n=-1){x=x.L.Sq("ytp-autonav-endscreen-upnext-header");
g.Sd(x);if(n>=0){n=String(n);let F="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],k="Up next in $SECONDS".indexOf(F);if(k>=0){var Z=g.v3("Up next in $SECONDS".slice(0,k));x.appendChild(Z);Z=g.Yf("span");g.Qq(Z,"ytp-autonav-endscreen-upnext-header-countdown-number");g.hM(Z,n);x.appendChild(Z);n=g.v3("Up next in $SECONDS".slice(k+F.length));x.appendChild(n);return}}g.hM(x,"Up next")},SX=function(x){return x.S.isFullscreen()?(x=x.S.getVideoData()?.QW,x===-1||x===void 0?8E3:x):x.S.E2()>=0?
x.S.E2():g.eL(x.S.J().experiments,"autoplay_time")||1E4},hF=function(x,n){n=R4l(x,n);
var Z=Math,F=Z.min;var k=(0,g.K)()-x.N;Z=F.call(Z,k,n);n=n===0?1:Math.min(Z/n,1);x.w$.setAttribute("stroke-dashoffset",`${-211*(n+1)}`);n>=1&&x.Z()&&!x.isCasting()?x.select(!0):x.Z()&&x.L.start()},R4l=function(x,n){return n?n:x.api.isFullscreen()?(x=x.api.getVideoData()?.QW,x===-1||x===void 0?8E3:x):x.api.E2()>=0?x.api.E2():g.eL(x.api.J().experiments,"autoplay_time")||1E4},eX=function(x){return g.MA(x.player)&&x.G()&&!x.U},y4=function(x){var n=x.lL();
n!==x.Y&&(x.Y=n,x.player.publish("autonavvisibility"))},sH=function(x){return g.MA(x.player)&&x.G()&&!x.V},B2=function(x){var n=x.lL();
n!==x.Hw&&(x.Hw=n,x.player.publish("autonavvisibility"))},D26=function(x){x=x.J();
return x.Nj&&!x.disableOrganicUi},tnt=function(x){var n=x.player.getVideoData();
if(!n||x.Z===n.SG)return!1;x.Z=n.SG;return!0},Aso=function(x){x.player.fH("endscreen");
var n=x.player.getVideoData();n=new g.Zu(Math.max((n.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var Z=new g.Zu(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});x.player.Zr([n,Z])};
g.BH.prototype.E2=g.iI(16,function(){return this.app.E2()});
g.i3.prototype.E2=g.iI(15,function(){return this.getVideoData().Jx});
g.se.prototype.RI=g.iI(14,function(x){this.Tz().RI(x)});
g.J4.prototype.RI=g.iI(13,function(x){this.Uf!==x&&(this.Uf=x,this.sQ())});
var aV=class extends g.t{constructor(x){super({D:"div",W:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.K=void 0;this.N=0;x.C("web_post_play_autonav_embiggening")&&g.Eu(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.t({D:"div",W:"ytp-autonav-endscreen-countdown-container"});g.G(this,this.container);this.container.kP(this.element);var n=x.J(),Z=n.U;this.S=x;this.suggestion=null;this.onVideoDataChange("newdata",this.S.getVideoData());this.X(x,"videodatachange",
this.onVideoDataChange);this.L=new g.t({D:"div",W:"ytp-autonav-endscreen-upnext-container",A:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{D:"div",W:"ytp-autonav-endscreen-topbar-container",j:[{D:"div",W:"ytp-autonav-endscreen-upnext-header"},{D:"div",W:"ytp-autonav-endscreen-upnext-alternative-header",UR:"{{autoplayAlternativeHeader}}"}]},{D:"a",W:"ytp-autonav-endscreen-link-container",
A:{href:"{{url}}",target:Z?n.K:""},j:[{D:"div",W:"ytp-autonav-endscreen-upnext-thumbnail",A:{style:"{{background}}"},j:[{D:"div",A:{"aria-label":"{{timestamp}}"},sR:["ytp-autonav-timestamp"],UR:"{{duration}}"},{D:"div",sR:["ytp-autonav-live-stamp"],UR:"Live"},{D:"div",sR:["ytp-autonav-upcoming-stamp"],UR:"Upcoming"}]},{D:"div",W:"ytp-autonav-endscreen-video-info",j:[{D:"div",W:"ytp-autonav-endscreen-premium-badge"},{D:"div",W:"ytp-autonav-endscreen-upnext-title",UR:"{{title}}"},{D:"div",W:"ytp-autonav-endscreen-upnext-author",
UR:"{{author}}"},{D:"div",W:"ytp-autonav-view-and-date",UR:"{{views_and_publish_time}}"},{D:"div",W:"ytp-autonav-author-and-view",UR:"{{author_and_views}}"}]}]}]});g.G(this,this.L);this.L.kP(this.container.element);Z||this.X(this.L.Sq("ytp-autonav-endscreen-link-container"),"click",this.VF);this.S.createClientVe(this.container.element,this,115127);this.S.createClientVe(this.L.Sq("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.t({D:"button",W:"ytp-autonav-endscreen-upnext-header-close-button",
A:{"aria-label":"Cancel autoplay"}});g.G(this,this.closeButton);x.C("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.cw,this),this.S.createClientVe(this.closeButton.element,this,115129),this.L.Sq("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.t({D:"div",W:"ytp-autonav-overlay"});g.G(this,this.overlay);this.overlay.kP(this.container.element);this.O=new g.t({D:"div",W:"ytp-autonav-endscreen-button-container"});g.G(this,
this.O);this.O.kP(this.container.element);this.cancelButton=new g.t({D:"button",sR:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],A:{"aria-label":"Cancel autoplay"},UR:"Cancel"});g.G(this,this.cancelButton);this.cancelButton.kP(this.O.element);this.cancelButton.listen("click",this.cw,this);this.S.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.t({D:"a",sR:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],A:{href:"{{url}}",role:"button","aria-label":"Play next video"},UR:"Play Now"});g.G(this,this.playButton);this.playButton.kP(this.O.element);this.playButton.listen("click",this.VF,this);this.S.createServerVe(this.playButton.element,this.playButton,!0);(n=this.S.getVideoData())&&rsk(this,n);this.G=new g.eP(()=>{UH(this)},500);
g.G(this,this.G);this.Hw();this.X(x,"autonavvisibility",this.Hw)}Y(x){this.suggestion!==x&&(this.suggestion=x,g.tZ(this.L,x),this.playButton.updateValue("url",this.suggestion.Y3()),uT(this))}Z(){return this.N>0}V(){this.Z()||(this.N=Date.now(),UH(this),Mnl(this.S,SX(this)),g.mu(this.S.getRootNode(),"countdown-running",this.Z()))}U(){this.B();UH(this);var x=this.L.Sq("ytp-autonav-endscreen-upnext-header");x&&g.hM(x,"Up next")}B(){this.Z()&&(this.G.stop(),this.N=0)}select(x=!1){this.S.nextVideo(!1,
x);this.B()}VF(x){g.Je(x,this.S)&&(x.currentTarget===this.playButton.element?this.S.logClick(this.playButton.element):x.currentTarget===this.L.Sq("ytp-autonav-endscreen-link-container")&&(x=this.L.Sq("ytp-autonav-endscreen-link-container"),this.S.logVisibility(x,!0),this.S.logClick(x)),this.K?(g.Wf(this.S,"innertubeCommand",this.K),this.B()):this.select())}cw(){this.S.logClick(this.cancelButton.element);g.$e(this.S,!0);this.cancelCommand&&g.Wf(this.S,"innertubeCommand",this.cancelCommand)}onVideoDataChange(x,
n){rsk(this,n);this.cancelCommand=n.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}Hw(){var x=this.S.lL();this.Vd!==x&&this.Jh(x);uT(this);this.S.logVisibility(this.container.element,x);this.S.logVisibility(this.cancelButton.element,x);this.S.logVisibility(this.L.Sq("ytp-autonav-endscreen-link-container"),x);this.S.logVisibility(this.playButton.element,x)}JF(x){return x.width<400||x.height<459}};var d2=class extends g.t{constructor(x,n){super({D:"div",sR:["html5-endscreen","ytp-player-content",n||"base-endscreen"]});this.created=!1;this.player=x}create(){this.created=!0}destroy(){this.created=!1}G(){return!1}lL(){return!1}K(){return!1}};var xjJ=class extends g.t{constructor(x){super({D:"div",sR:["ytp-upnext","ytp-player-content"],A:{"aria-label":"{{aria_label}}"},j:[{D:"div",W:"ytp-cued-thumbnail-overlay-image",A:{style:"{{background}}"}},{D:"span",W:"ytp-upnext-top",j:[{D:"span",W:"ytp-upnext-header",UR:"Up Next"},{D:"span",W:"ytp-upnext-title",UR:"{{title}}"},{D:"span",W:"ytp-upnext-author",UR:"{{author}}"}]},{D:"a",W:"ytp-upnext-autoplay-icon",A:{role:"button",href:"{{url}}","aria-label":"Play next video"},j:[{D:"svg",A:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},j:[{D:"circle",W:"ytp-svg-autoplay-circle",A:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",W:"ytp-svg-autoplay-ring",A:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",W:"ytp-svg-fill",A:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",W:"ytp-upnext-bottom",j:[{D:"span",W:"ytp-upnext-cancel"},
{D:"span",W:"ytp-upnext-paused",UR:"Autoplay is paused"}]}]});this.api=x;this.cancelButton=null;this.w$=this.Sq("ytp-svg-autoplay-ring");this.G=this.notification=this.L=this.suggestion=null;this.K=new g.eP(this.O,5E3,this);this.N=0;var n=this.Sq("ytp-upnext-cancel");this.cancelButton=new g.t({D:"button",sR:["ytp-upnext-cancel-button","ytp-button"],A:{tabindex:"0","aria-label":"Cancel autoplay"},UR:"Cancel"});g.G(this,this.cancelButton);this.cancelButton.listen("click",this.cw,this);this.cancelButton.kP(n);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.G(this,this.K);this.api.createClientVe(this.element,this,18788);n=this.Sq("ytp-upnext-autoplay-icon");this.X(n,"click",this.VF);this.api.createClientVe(n,this,115130);this.Hw();this.X(x,"autonavvisibility",this.Hw);this.X(x,"mdxnowautoplaying",this.oW);this.X(x,"mdxautoplaycanceled",this.ue);g.mu(this.element,"ytp-upnext-mobile",this.api.J().B)}O(){this.notification&&(this.K.stop(),this.nx(this.G),this.G=null,this.notification.close(),
this.notification=null)}Y(x){this.suggestion=x;g.tZ(this,x,"hqdefault.jpg")}Hw(){this.Jh(this.api.lL());this.api.logVisibility(this.element,this.api.lL());this.api.logVisibility(this.Sq("ytp-upnext-autoplay-icon"),this.api.lL());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.lL())}Pw(){window.focus();this.O()}V(x){this.Z()||(g.zJ("a11y-announce",`Up Next ${this.suggestion.title}`),this.N=(0,g.K)(),this.L=new g.eP(()=>{hF(this,x)},25),hF(this,x),Mnl(this.api,R4l(this,
x)));
g.WC(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}Z(){return!!this.L}isCasting(){return this.api.getPresentingPlayerType()===3}U(){this.B();this.N=(0,g.K)();hF(this);g.Eu(this.element,"ytp-upnext-autoplay-paused")}B(){this.Z()&&(this.L.dispose(),this.L=null)}select(x=!1){if(this.api.J().C("autonav_notifications")&&x&&window.Notification&&typeof document.hasFocus==="function"){let n=Notification.permission;n==="default"?Notification.requestPermission():n!=="granted"||document.hasFocus()||
(this.O(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.r_()}),this.G=this.X(this.notification,"click",this.Pw),this.K.start())}this.B();this.api.nextVideo(!1,x)}VF(x){!g.uR(this.cancelButton.element,x.target)&&g.Je(x,this.api)&&(this.api.lL()&&this.api.logClick(this.Sq("ytp-upnext-autoplay-icon")),this.select())}cw(){this.api.lL()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.$e(this.api,!0)}oW(x){this.isCasting();this.show();this.V(x)}ue(){this.isCasting();
this.B();this.hide()}Bw(){this.B();this.O();super.Bw()}};var nSt=class extends d2{constructor(x){super(x,"videowall-endscreen");this.S=x;this.stills=[];this.U=this.videoData=null;this.V=this.Y=!1;this.Hw=null;g.Eu(this.element,"modern-videowall-endscreen");this.L=new g.EE(this);g.G(this,this.L);this.O=new g.eP(()=>{g.Eu(this.element,"ytp-show-tiles")},0);
g.G(this,this.O);this.table=new g.$W({D:"div",W:"ytp-modern-endscreen-content"});g.G(this,this.table);this.table.kP(this.element);x.getVideoData().SG?this.Z=new aV(x):this.Z=new xjJ(x);g.G(this,this.Z);g.KD(this.player,this.Z.element,4);x.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var x=this.player.getVideoData();x&&(this.videoData=x);this.B();this.L.X(this.player,"appresize",this.B);this.L.X(this.player,"onVideoAreaChange",this.B);this.L.X(this.player,"videodatachange",
this.onVideoDataChange);this.L.X(this.player,"autonavchange",this.N);this.L.X(this.player,"onAutonavCancelled",this.cw);x=this.videoData.autonavState;x!==this.Hw&&this.N(x,!1);this.L.X(this.element,"transitionend",this.VF)}destroy(){this.L.L();g.ec(this.stills);this.stills=[];super.destroy();g.WC(this.element,"ytp-show-tiles");this.O.stop();this.Hw=this.videoData.autonavState}G(){return this.videoData?.Nj||this.videoData.autonavState!==1}show(){var x=this.Vd;super.show();g.WC(this.element,"ytp-show-tiles");
this.player.J().B?g.BC(this.O):this.O.start();(this.V||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.$e(this.player,!1);eX(this)?(y4(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||cst(this.player.kp())&&this.player.C("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.V():this.videoData.autonavState===3&&this.Z.U()):(g.$e(this.player,!0),y4(this));x!==this.Vd&&this.player.logVisibility(this.element,!0)}hide(){var x=this.Vd;super.hide();this.Z.U();y4(this);
x!==this.Vd&&this.player.logVisibility(this.element,!1)}VF(x){x.target===this.element&&this.B()}B(){var x=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.Ze()];if(x.length){var n=this.S.Px(!0,this.S.isFullscreen()),Z=Math.floor((n.width-64+16)/(g.la(n.width*.27,250,450)+16));n=Math.min(3,Math.floor((n.height-64)/((n.width-64-(Z-1)*16)/Z*.5625+70)));g.ow(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Eu(this.element,`ytp-modern-endscreen-limit-rows-${n}`);g.mu(this.element,"ytp-modern-endscreen-single-item",Z===1);g.mu(this.element,"ytp-modern-endscreen-row-0",n===0);Z=this.table.element;Z.ariaLive="polite";this.Z.Y(this.videoData.Ze());this.Z instanceof aV&&uT(this.Z);g.mu(this.element,"ytp-endscreen-takeover",eX(this));y4(this);n=0;Z.ariaBusy="true";var F=x.length;for(let k=0;k<F;k++){let J=k%F,Y=this.stills[k];Y||(Y=new g.hUl(this.player),this.stills[k]=Y,Z.appendChild(Y.element));g.G1q(Y,
x[J]);n++}this.stills.length=n}}onVideoDataChange(){var x=this.player.getVideoData({playerType:1});this.videoData!==x&&(x?.Ze()?(this.videoData=x,this.B()):this.player.L6("missg",{vid:x?.videoId||"",cpn:x?.clientPlaybackNonce||""}))}K(){return this.Z.Z()}N(x,n=!1){var Z=this.videoData?.Nj;if(x===1){if(!Z||n)this.V=!1,this.U=this.videoData.clientPlaybackNonce;this.Z.B();this.Vd&&this.B()}else this.V=!0,this.Vd&&eX(this)&&(x===2?this.Z.V():x===3&&this.Z.U())}cw(x){if(x){for(x=0;x<this.stills.length;x++)this.S.logVisibility(this.stills[x].element,
!0);this.N(1,!0)}else this.U=null,this.V=!1;this.B()}lL(){return this.Vd&&eX(this)}};var ZQk=class extends g.t{constructor(x){var n=x.J(),Z=g.mC||g.CS?{style:"will-change: opacity"}:void 0,F=n.U,k=["ytp-videowall-still"];n.B&&k.push("ytp-videowall-show-text");super({D:"a",sR:k,A:{href:"{{url}}",target:F?n.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},j:[{D:"div",W:"ytp-videowall-still-image",A:{style:"{{background}}"}},{D:"span",W:"ytp-videowall-still-info",A:{"aria-hidden":"true"},j:[{D:"span",W:"ytp-videowall-still-info-bg",
j:[{D:"span",W:"ytp-videowall-still-info-content",A:Z,j:[{D:"span",W:"ytp-videowall-still-info-title",UR:"{{title}}"},{D:"span",W:"ytp-videowall-still-info-author",UR:"{{author_and_views}}"},{D:"span",W:"ytp-videowall-still-info-live",UR:"Live"},{D:"span",W:"ytp-videowall-still-info-duration",UR:"{{duration}}"}]}]}]},{D:"span",sR:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],A:{"aria-hidden":"true"},j:[{D:"span",W:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",
W:"ytp-videowall-still-listlabel-length",j:[" (",{D:"span",UR:"{{playlist_length}}"},")"]}]},{D:"span",sR:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],A:{"aria-hidden":"true"},j:[{D:"span",W:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",W:"ytp-videowall-still-listlabel-length",UR:" (50+)"}]}]});this.suggestion=null;this.L=F;this.api=x;this.Z=new g.EE(this);g.G(this,this.Z);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.Z.X(x,"videodatachange",
this.onVideoDataChange);x.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.Iu(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Al||void 0)&&this.api.logClick(this.element)}onClick(x){if(g.yv(this.api.J())&&this.api.C("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let n=this.suggestion.Y3(),Z={};g.b6(this.api,Z);n=g.f4(n,Z);g.YF(n,this.api,x)}else g.Je(x,this.api,
this.L,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(x){switch(x.keyCode){case 13:case 32:x.defaultPrevented||(this.select(),x.preventDefault())}}onVideoDataChange(){var x=this.api.getVideoData(),n=this.api.J();this.L=x.B7?!1:n.U}};var Fn6=class extends d2{constructor(x){super(x,"videowall-endscreen");this.S=x;this.U=0;this.stills=[];this.V=this.videoData=null;this.O=this.Hw=!1;this.cw=null;this.B=new g.EE(this);g.G(this,this.B);this.N=new g.eP(()=>{g.Eu(this.element,"ytp-show-tiles")},0);
g.G(this,this.N);var n=new g.t({D:"button",sR:["ytp-button","ytp-endscreen-previous"],A:{"aria-label":"Previous"},j:[g.jV()]});g.G(this,n);n.kP(this.element);n.listen("click",this.oW,this);this.table=new g.$W({D:"div",W:"ytp-endscreen-content"});g.G(this,this.table);this.table.kP(this.element);n=new g.t({D:"button",sR:["ytp-button","ytp-endscreen-next"],A:{"aria-label":"Next"},j:[g.qT()]});g.G(this,n);n.kP(this.element);n.listen("click",this.w$,this);x.getVideoData().SG?this.Z=new aV(x):this.Z=new xjJ(x);
g.G(this,this.Z);g.KD(this.player,this.Z.element,4);x.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var x=this.player.getVideoData();x&&(this.videoData=x);this.L();this.B.X(this.player,"appresize",this.L);this.B.X(this.player,"onVideoAreaChange",this.L);this.B.X(this.player,"videodatachange",this.onVideoDataChange);this.B.X(this.player,"autonavchange",this.Y);this.B.X(this.player,"onAutonavCancelled",this.VF);x=this.videoData.autonavState;x!==this.cw&&this.Y(x,!1);this.B.X(this.element,
"transitionend",this.ue)}destroy(){this.B.L();g.ec(this.stills);this.stills=[];super.destroy();g.WC(this.element,"ytp-show-tiles");this.N.stop();this.cw=this.videoData.autonavState}G(){return this.videoData?.Nj||this.videoData?.autonavState!==1}show(){var x=this.Vd;super.show();g.WC(this.element,"ytp-show-tiles");this.player.J().B?g.BC(this.N):this.N.start();(this.O||this.V&&this.V!==this.videoData.clientPlaybackNonce)&&g.$e(this.player,!1);sH(this)?(B2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||cst(this.player.kp())&&this.player.C("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.V():this.videoData.autonavState===3&&this.Z.U()):(g.$e(this.player,!0),B2(this));x!==this.Vd&&this.player.logVisibility(this.element,!0)}hide(){var x=this.Vd;super.hide();this.Z.U();B2(this);x!==this.Vd&&this.player.logVisibility(this.element,!1)}ue(x){x.target===this.element&&this.L()}L(){var x=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.Ze()];if(x.length){g.Eu(this.element,
"ytp-endscreen-paginate");var n=this.S.Px(!0,this.S.isFullscreen()),Z=g.wY(this.S);Z&&(Z=Z.dZ()?48:32,n.width-=Z*2);var F=n.width/n.height,k=96/54,J=Z=2,Y=Math.max(n.width/96,2),v=Math.max(n.height/54,2),L=x.length;var S=L*4;for(S-=4;S>0&&(Z<Y||J<v);){var T=Z/2,U=J/2,h=Z<=Y-2&&S>=U*4,u=J<=v-2&&S>=T*4;if((T+1)/U*k/F>F/(T/(U+1)*k)&&u)S-=T*4,J+=2;else if(h)S-=U*4,Z+=2;else if(u)S-=T*4,J+=2;else break}k=!1;S>=12&&L*4-S<=6&&(J>=4||Z>=4)&&(k=!0);S=Z*96;Y=J*54;F=S/Y<F?n.height/Y:n.width/S;F=Math.min(F,2);
S=Math.floor(Math.min(n.width,S*F));Y=Math.floor(Math.min(n.height,Y*F));n=this.table.element;n.ariaLive="polite";g.AM(n,S,Y);g.jd(n,{marginLeft:`${S/-2}px`,marginTop:`${Y/-2}px`});this.Z.Y(this.videoData.Ze());this.Z instanceof aV&&uT(this.Z);g.mu(this.element,"ytp-endscreen-takeover",sH(this));B2(this);S+=4;Y+=4;F=0;n.ariaBusy="true";for(v=0;v<Z;v++)for(T=0;T<J;T++)if(h=F,u=0,k&&v>=Z-2&&T>=J-2?u=1:T%2===0&&v%2===0&&(T<2&&v<2?T===0&&v===0&&(u=2):u=2),h=g.CU(h+this.U,L),u!==0){U=this.stills[F];U||
(U=new ZQk(this.player),this.stills[F]=U,n.appendChild(U.element));var d=Math.floor(Y*T/J);let m=Math.floor(S*v/Z),P=Math.floor(Y*(T+u)/J)-d-4,H=Math.floor(S*(v+u)/Z)-m-4;g.px(U.element,m,d);g.AM(U.element,H,P);g.jd(U.element,"transitionDelay",(T+v)/20+"s");g.mu(U.element,"ytp-videowall-still-mini",u===1);g.mu(U.element,"ytp-videowall-still-large",u>2);u=Math.max(H,P);g.mu(U.element,"ytp-videowall-still-round-large",u>=256);g.mu(U.element,"ytp-videowall-still-round-medium",u>96&&u<256);g.mu(U.element,
"ytp-videowall-still-round-small",u<=96);h=x[h];U.suggestion!==h&&(U.suggestion=h,u=U.api.J(),d=g.X6(U.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.tZ(U,h,d),g.yv(u)&&!U.api.C("web_player_log_click_before_generating_ve_conversion_params")&&(u=h.Y3(),d={},g.Gp(U.api,"addEmbedsConversionTrackingParams",[d]),u=g.f4(u,d),U.updateValue("url",u)),(h=(h=h.sessionData)&&h.itct)&&U.api.setTrackingParams(U.element,h));F++}n.ariaBusy="false";g.mu(this.element,"ytp-endscreen-paginate",
F<L);for(x=this.stills.length-1;x>=F;x--)Z=this.stills[x],g.U3(Z.element),g.hR(Z);this.stills.length=F}}onVideoDataChange(){var x=this.player.getVideoData({playerType:1});this.videoData!==x&&(x?.Ze()?(this.U=0,this.videoData=x,this.L()):this.player.L6("missg",{vid:x?.videoId||"",cpn:x?.clientPlaybackNonce||""}))}w$(){this.U+=this.stills.length;this.L()}oW(){this.U-=this.stills.length;this.L()}K(){return this.Z.Z()}Y(x,n=!1){var Z=this.videoData?.Nj;if(x===1){if(!Z||n)this.O=!1,this.V=this.videoData.clientPlaybackNonce;
this.Z.B();this.Vd&&this.L()}else this.O=!0,this.Vd&&sH(this)&&(x===2?this.Z.V():x===3&&this.Z.U())}VF(x){if(x){for(x=0;x<this.stills.length;x++)this.S.logVisibility(this.stills[x].element,!0);this.Y(1,!0)}else this.V=null,this.O=!1;this.L()}lL(){return this.Vd&&sH(this)}};var iQs=class extends g.t{constructor(x){super({D:"button",sR:["ytp-watch-on-youtube-button","ytp-button"],UR:"{{content}}"});this.S=x;this.buttonType=this.buttonType=1;this.Z();this.buttonType===2&&g.Eu(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Z);this.Jh(!0)}Z(){switch(this.buttonType){case 1:var x="Watch again on YouTube";var n=156915;break;case 2:x="Continue watching on YouTube";n=156942;break;default:x="Continue watching on YouTube",
n=156942}this.update({content:x});this.S.hasVe(this.element)&&this.S.destroyVe(this.element);this.S.createClientVe(this.element,this,n)}onClick(x){this.S.C("web_player_log_click_before_generating_ve_conversion_params")&&this.S.logClick(this.element);g.YF(this.getVideoUrl(),this.S,x);this.S.C("web_player_log_click_before_generating_ve_conversion_params")||this.S.logClick(this.element)}getVideoUrl(){var x=!0;switch(this.buttonType){case 1:x=!0;break;case 2:x=!1}x=this.S.getVideoUrl(x,!1,!1,!0);var n=
this.S.J();if(g.yv(n)){let Z={};g.yv(n)&&g.Gp(this.S,"addEmbedsConversionTrackingParams",[Z]);x=g.f4(x,Z)}return x}logVisibility(){this.S.logVisibility(this.element,this.Vd&&this.Ze)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}So(x){super.So(x);this.logVisibility()}};var kPt=class extends d2{constructor(x){super(x,"watch-again-on-youtube-endscreen");this.watchButton=new iQs(x);g.G(this,this.watchButton);this.watchButton.kP(this.element);g.Ibn(x)&&(this.Z=new g.c9$(x),g.G(this,this.Z),this.L=new g.t({D:"div",sR:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],A:{tabIndex:"-1"},j:[this.Z]}),g.G(this,this.L),this.Z.kP(this.L.element),this.L.kP(this.element));x.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.Z?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let n=this.L;if(n){var x=this.Z.hasSuggestions();g.mu(this.element,"ytp-shorts-branded-ui",x);x?n.show():n.hide()}g.wY(this.player)?.RI(!0);this.player.logVisibility(this.element,!0);this.watchButton.So(!0)}}hide(){super.hide();g.wY(this.player)?.RI(!1);this.player.logVisibility(this.element,!1);this.watchButton.So(!1)}};g.T1("endscreen",class extends g.Oe{constructor(x){super(x);this.endScreen=null;this.Z=this.L=!1;this.listeners=new g.EE(this);g.G(this,this.listeners);var n=x.J();x.isEmbedsShortsMode()?this.endScreen=new kPt(x):D26(x)?(this.L=!0,tnt(this),n.C("delhi_modern_endscreen")?this.endScreen=new nSt(x):this.endScreen=new Fn6(x)):this.endScreen=new d2(x);g.G(this,this.endScreen);g.KD(x,this.endScreen.element,4);Aso(this);this.listeners.X(x,"videodatachange",this.onVideoDataChange,this);this.listeners.X(x,
g.OY("endscreen"),Z=>{this.onCueRangeEnter(Z)});
this.listeners.X(x,g.HK("endscreen"),Z=>{this.onCueRangeExit(Z)})}Gu(){var x=this.player.getVideoData(),n=x.mutedAutoplay&&(x.limitedPlaybackDurationInSeconds>0||x.endSeconds>0||x.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!n)return!0;var Z=!(!x?.Ze()&&!x?.suggestions?.length);Z=!D26(this.player)||Z;var F=x.HU,k=this.player.L0();return(Z||!!x?.Nj)&&!F&&!k&&!n}lL(){return this.endScreen.lL()}jm(){return this.lL()?this.endScreen.K():!1}Bw(){this.player.fH("endscreen");super.Bw()}load(){{let Z=this.player.getVideoData(),F=Z.transitionEndpointAtEndOfStream;if(F&&F.videoId){var x=this.player.PD().uL.get("heartbeat");var n=Z.Ze();!n||F.videoId!==n.videoId||Z.eE?(this.player.Iu(F.videoId,
void 0,void 0,!0,!0,F),x&&x.Op("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),x=!0):x=!1}else x=!1}x||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(x){this.Gu()&&(this.endScreen.created||this.endScreen.create(),x.getId()==="load"&&this.load())}onCueRangeExit(x){x.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){Aso(this);this.L&&tnt(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new Fn6(this.player),g.G(this,this.endScreen),g.KD(this.player,this.endScreen.element,4))}});})(_yt_player);
